#!/usr/bin/env python3
"""build_overlay_rf.py - RF source evidence placed on the rf_hall break-even surfaces (overlay_rf_v1).

Registered follow-on ``fo_rf_breakeven_overlay`` (trigger T_RF_OVERLAY). Produces CONDITIONAL INEQUALITIES for
``rf_hall`` against ``hall_only`` on the common boundary ``bus_power_boundary_v1``: no prediction, no ranking, no
architecture is named as preferred, nothing is set aside (setting an arm aside is done only by hard gates).

Outputs (this directory):
  overlay_rf_v1.json          the overlay (authoritative for every number)
  RF_BREAKEVEN_OVERLAY.md     narrative; the block between the GENERATED markers is written by this script

Usage:
  python docs/architecture_comparison/overlays/rf/build_overlay_rf.py             # write JSON + generated MD block
  python docs/architecture_comparison/overlays/rf/build_overlay_rf.py --check     # rebuild in memory, byte-compare
  ... [--input-root DIR ...]                                                      # extra roots to search for inputs

Inputs are read READ-ONLY and are pinned by sha256 (INPUTS below). Each is looked up by its repository-relative path,
first in this checkout, then under every --input-root, then in the sibling git worktrees of this checkout; only a file
whose sha256 matches the pin is accepted, so the result does not depend on where an input was found. A missing input
raises OverlayInputError with the list of places searched (no silent fallback, CLAUDE.md rule 3). After the input
lanes merge, the inputs are found in this checkout and nothing else is needed. To move to a newer input, change its
pin here deliberately and regenerate.

The break-even algebra comes from abep_sim/breakeven.py (breakeven_v1), loaded at run time by file path from the
checkout that holds the pinned file (under a private module name, never copied). Y, X and the fixed-overhead supremum
are breakeven_v1 values. The coupled X-Y interval is the exact cubic form of the same master inequality; it is
cross-checked against breakeven_v1.place_evidence and, through two bus_power_boundary_v1-format ledgers, against
overhead_from_boundary_ledgers + achievable_delivered_share + evaluate_arm. The closed forms of BREAKEVEN_DERIVATION.md
are evaluated independently as self-checks; the build refuses to write if any fails. This script is pure: it is not
wired into archengine and moves no golden.
"""
from __future__ import annotations

import argparse
import glob
import hashlib
import importlib
import importlib.util
import json
import math
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", "..", ".."))
OUT_JSON = os.path.join(HERE, "overlay_rf_v1.json")
OUT_MD = os.path.join(HERE, "RF_BREAKEVEN_OVERLAY.md")
MD_BEGIN = "<!-- BEGIN GENERATED by build_overlay_rf.py: do not edit by hand -->"
MD_END = "<!-- END GENERATED -->"
SCRIPT_REL = "docs/architecture_comparison/overlays/rf/build_overlay_rf.py"

OVERLAY_VERSION = "overlay_rf_v1"
BOUNDARY_VERSION = "bus_power_boundary_v1"
ARCH = "rf_hall"
REFERENCE_ARCH = "hall_only"
PREPARED = "2026-09-26"

# ---------------------------------------------------------------------------------------------------- pinned inputs
INPUTS = {
    "breakeven_module": {
        "path": "abep_sim/breakeven.py",
        "sha256": "fad317b74c3f1359d849c62a7b487f2e26d8ccb3be05a35c15b515ea6d948767",
        "lane": "lane_28_break_even", "branch": "worktree-wf_15f0f2f8-8d4-1", "commit": "2ad4c463d7"},
    "breakeven_derivation": {
        "path": "docs/architecture_comparison/breakeven/BREAKEVEN_DERIVATION.md",
        "sha256": "e65c28c040c1fbd9b079d4d4872316441e4f4114f37ff70e79138aab8c134d86",
        "lane": "lane_28_break_even", "branch": "worktree-wf_15f0f2f8-8d4-1", "commit": "2ad4c463d7"},
    "rf_evidence_matrix": {
        "path": "docs/evidence/rf_source/rf_evidence_matrix.json",
        "sha256": "5f6d4e0ede8b2e21e45b740c28ac9320e7ddd6cfd70ef05012f85712ae0ac8e8",
        "lane": "lane_07_rf_evidence", "branch": "worktree-wf_2bcadd98-5ff-1", "commit": "336d548042"},
    "interstage_module": {
        "path": "abep_sim/interstage.py",
        "sha256": "bc4b9987a832209d1417f6646d2a44c72b8d79bac18f896089647bcd1ed93174",
        "lane": "lane_18_interstage", "branch": "worktree-wf_15f0f2f8-8d4-2", "commit": "870514285c"},
    "interstage_model_doc": {
        "path": "docs/architecture_comparison/interstage/INTERSTAGE_MODEL.md",
        "sha256": "2a08e8045d1cb61a121e84dc9f7bba268a1ec7b66476057d9093b4e044f6d616",
        "lane": "lane_18_interstage", "branch": "worktree-wf_15f0f2f8-8d4-2", "commit": "870514285c"},
    "electrical_closure_data": {
        "path": "docs/architecture_comparison/electrical_closure/electrical_closure_data_v1.json",
        "sha256": "d56f700198a64a919d736c8659b6e0aaaa01cd56521885772d2f5a40de374501",
        "lane": "lane_20_ppu_magnet", "branch": "worktree-wf_15f0f2f8-8d4-3", "commit": "f7c226848d"},
    "constants_module": {
        "path": "abep_sim/constants.py",
        "sha256": "dd1c564324c139471bb361d27ef0f75b0f84de1878d100d4313aed12677f33d7",
        "lane": "base checkout (identical on every input lane)", "branch": "main", "commit": "a170c1faa4"},
}
PINNED_MODULE_NAME = "abep_sim._overlay_rf_pinned_breakeven"   # private name: never shadows abep_sim.breakeven


class OverlayInputError(RuntimeError):
    """A pinned input is missing or differs from its pin (no silent fallback)."""


class OverlaySelfCheckError(RuntimeError):
    """A self-check failed; nothing is written."""


def sha256_file(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        h.update(f.read())
    return h.hexdigest()


def candidate_roots(extra_roots):
    roots = [ROOT] + [os.path.abspath(r) for r in extra_roots]
    env = os.environ.get("ABEP_OVERLAY_INPUT_ROOTS", "")
    roots += [os.path.abspath(r) for r in env.split(os.pathsep) if r.strip()]
    parent = os.path.dirname(ROOT)
    if os.path.basename(parent) == "worktrees":            # ROOT is a git worktree: search its siblings
        roots += sorted(p for p in glob.glob(os.path.join(parent, "*")) if os.path.isdir(p))
        main = os.path.dirname(os.path.dirname(parent))      # <main>/.claude/worktrees/<wt> -> <main>
        roots.append(main)
    out, seen = [], set()
    for r in roots:
        if r not in seen:
            seen.add(r)
            out.append(r)
    return out


def resolve_inputs(extra_roots):
    found, report = {}, {}
    roots = candidate_roots(extra_roots)
    for key, pin in INPUTS.items():
        tried = []
        for r in roots:
            p = os.path.join(r, pin["path"])
            if os.path.isfile(p):
                h = sha256_file(p)
                tried.append(f"{p} (sha256 {h[:12]}...)")
                if h == pin["sha256"]:
                    found[key] = (r, p)
                    break
        if key not in found:
            report[key] = tried
    if report:
        lines = [f"  {k}: {INPUTS[k]['path']} pinned sha256 {INPUTS[k]['sha256'][:12]}... from {INPUTS[k]['lane']} "
                 f"(commit {INPUTS[k]['commit']}); candidates: {v or 'none found'}" for k, v in report.items()]
        raise OverlayInputError("pinned overlay inputs not found (pass --input-root DIR, or set "
                                "ABEP_OVERLAY_INPUT_ROOTS, or merge the input lanes):\n" + "\n".join(lines))
    return found


def load_constants():
    """This checkout's abep_sim.constants (pinned). The pinned breakeven module imports it relatively."""
    if ROOT not in sys.path:
        sys.path.insert(0, ROOT)
    K = importlib.import_module("abep_sim.constants")
    if sha256_file(K.__file__) != INPUTS["constants_module"]["sha256"]:
        raise OverlayInputError(f"abep_sim.constants resolved to {K.__file__}, which differs from its pin")
    return K


def load_breakeven(found):
    """Load the pinned abep_sim/breakeven.py by file path under a private module name inside this checkout's abep_sim
    package (its only relative import, .constants, must be byte-identical to the one next to it in its own checkout)."""
    root, path = found["breakeven_module"]
    K = load_constants()
    sibling = os.path.join(root, "abep_sim", "constants.py")
    if not os.path.isfile(sibling) or sha256_file(sibling) != INPUTS["constants_module"]["sha256"]:
        raise OverlayInputError(f"{sibling}: constants next to the pinned breakeven module differ from the pin")
    b = sys.modules.get(PINNED_MODULE_NAME)
    if b is None:
        spec = importlib.util.spec_from_file_location(PINNED_MODULE_NAME, path)
        b = importlib.util.module_from_spec(spec)
        sys.modules[PINNED_MODULE_NAME] = b          # dataclasses resolve their module through sys.modules
        try:
            spec.loader.exec_module(b)
        except Exception:
            del sys.modules[PINNED_MODULE_NAME]
            raise
    if sha256_file(b.__file__) != INPUTS["breakeven_module"]["sha256"]:
        raise OverlayInputError(f"pinned breakeven module resolved to {b.__file__}, which differs from its pin")
    if b.BOUNDARY_VERSION != BOUNDARY_VERSION or b.BREAKEVEN_VERSION != "breakeven_v1":
        raise OverlayInputError(f"breakeven versions {b.BREAKEVEN_VERSION}/{b.BOUNDARY_VERSION} not as pinned")
    return b, K


# ---------------------------------------------------------------------------------------------------- formatting
def g6(x):
    if x is None:
        return None
    if isinstance(x, float) and not math.isfinite(x):
        return None
    return float(f"{float(x):.6g}")


def fmt(x, nd=4):
    if x is None:
        return "unbounded"
    if 1e4 <= abs(x) < 1e9:
        return f"{x:.0f}"
    return f"{x:.{nd}g}"


# ---------------------------------------------------------------------------------------------------- declared ranges
PROPOSED = "PROPOSED analysis range (assumed; not a prediction, not a design value; owner to confirm)"
V_D = [150.0, 200.0, 250.0, 300.0, 350.0, 400.0, 450.0]
V_D_SLICES = [150.0, 300.0, 450.0]
ETA_B = [0.5, 0.7, 0.9]
ETA_U0 = [0.3, 0.6, 0.9]
ETA_V = [0.7, 0.8, 0.9, 1.0]
ETA_T = [round(0.1 * i, 1) for i in range(1, 11)]
OMEGA = [round(0.05 * i, 2) for i in range(19)]                 # 0 - 0.90
OMEGA_F = [0.0, 0.01, 0.02, 0.05, 0.1, 0.2]
OMEGA_F_COUPLED = [0.0, 0.02, 0.05, 0.1]
C_NORM = [round(0.1 * i, 1) for i in range(1, 21)]             # C_del / Pi_H = 0.1 - 2.0
C_SRC_GRID = [25.0, 50.0, 100.0, 150.0, 200.0, 300.0, 400.0, 500.0, 700.0, 1000.0, 1500.0, 2000.0]
GAMMA_REF = 0.9                                                 # enters no break-even quantity (breakeven_v1 self-check)
CASES = {
    "add_only": {"alpha": 1.0, "chi": 0.0, "eta_v_delivered": "= eta_v",
                 "meaning": "delivered ions add to the beam; each costs the full Hall price V_d/eta_b"},
    "cost_offset": {"alpha": 1.0, "chi": 1.0, "eta_v_delivered": "= eta_v",
                    "meaning": "delivered ions add to the beam and avoid the Hall's per-ion electron-current overhead"},
    "optimistic_bound": {"alpha": 1.0, "chi": 1.0, "eta_v_delivered": 1.0,
                         "meaning": "most favourable corner of the declared box alpha, chi in [0,1], eta_v_S in "
                                    "[eta_v, 1] at equal mix (breakeven_v1 self-check: dominates the box)"},
}
CASE_ORDER = ["add_only", "cost_offset", "optimistic_bound"]
PLACEMENTS = ("CLEARLY_ABOVE_BREAKEVEN", "CLEARLY_BELOW", "STRADDLES", "NOT_PLACEABLE")


def variants(case):
    """(eta_b, eta_v) combinations on which the normalized coefficients of a case depend."""
    if case == "add_only":
        return [(None, None)]
    if case == "cost_offset":
        return [(eb, None) for eb in ETA_B]
    return [(eb, ev) for eb in ETA_B for ev in (0.7, 0.9, 1.0)]


def vkey(case, eb, ev):
    s = case
    if eb is not None:
        s += f"|eta_b={eb}"
    if ev is not None:
        s += f"|eta_v={ev}"
    return s


# ---------------------------------------------------------------------------------------------------- breakeven glue
class Glue:
    def __init__(self, b, amu_kg, m_n2_u):
        self.b = b
        self.mix = b.IonMix((b.IonSpecies("N2+", m_n2_u, 1, 1.0),))
        self.amu = amu_kg

    def ref(self, V, eta_u0, eta_b, eta_v, eta_ppu, mdot=1.0e-6):
        return self.b.HallReference(mdot_kg_s=mdot, V_d_V=V, eta_u=eta_u0, eta_b=eta_b, eta_v=eta_v,
                                    gamma_div=GAMMA_REF, eta_ppu_discharge=eta_ppu, mix=self.mix)

    def resp(self, case, ref):
        c = CASES[case]
        evs = ref.eta_v if c["eta_v_delivered"] == "= eta_v" else c["eta_v_delivered"]
        return self.b.PreionResponse(alpha=c["alpha"], chi=c["chi"], eta_v_delivered=evs, mix_delivered=ref.mix)

    def overhead(self, P):
        b = self.b
        return b.BusOverhead(arch=ARCH, source_bus_W={"rf_source": P},
                             delta_common_bus_W={k: 0.0 for k in b.COMMON_NON_DISCHARGE},
                             interstage_loss_bus_W=0.0, extra_ppu_bus_W=0.0)

    def Y(self, case, V, eta_b, eta_v, eta_ppu):
        """Largest payable bus W per A of DELIVERED ions (no fixed overhead): the supremum = marginal limit."""
        r = self.ref(V, 0.6, eta_b, eta_v, eta_ppu)
        return self.b.marginal_breakeven_delivered_cost(r, self.resp(case, r))


def closed_form_c(case, eta_b, eta_v):
    """BREAKEVEN_DERIVATION.md section 6.1 marginal C_del*,0 / Pi_H at equal mix (self-check only)."""
    if case == "add_only":
        return 1.0
    if case == "cost_offset":
        return 2.0 - eta_b
    return 2.0 / math.sqrt(eta_v) - eta_b


def n_d(case, eta_b, eta_v):
    """Normalized two-population coefficients for alpha = 1 at equal mix: R(x) = (1 + n x)^2 / (1 + d x),
    x = delta_s / eta_u0 (BREAKEVEN_DERIVATION.md section 5: n1 = R_T, d1 = R_P for alpha = 1)."""
    c = CASES[case]
    evs = eta_v if c["eta_v_delivered"] == "= eta_v" else c["eta_v_delivered"]
    n = math.sqrt(evs / eta_v)
    d = eta_b * (1.0 + (1.0 - c["chi"]) * (1.0 / eta_b - 1.0))
    return n, d


MARGINAL_TOL = 1e-12        # |2n - d - c| below this counts as exactly marginal: pays only in the limit x -> 0


def payable_poly(n, d, c, wf):
    """Coefficients (a3, a2, a1, a0) of F(x) = (1 + n x)^2 (1 - wf - c x) - (1 + d x) with the constant 1 cancelled
    analytically (F = x q(x) - wf (1 + n x)^2, q(x) = (2n - c - d) + (n^2 - 2nc) x - n^2 c x^2), so F is evaluated
    without cancellation near x = 0. F >= 0 <=> R(x)(1 - wf - c x) >= 1 (breakeven_v1 master condition at equal mix)."""
    return (-n * n * c, n * n - 2.0 * n * c - wf * n * n, 2.0 * n - c - d - 2.0 * wf * n, -wf)


def payable_x_interval(n, d, c, wf):
    """[x_lo, x_hi] (uncapped; x = delta_s/eta_u0) where a source whose delivered-ion bus cost is c * Pi_H breaks even
    with fixed overhead wf * P_d,bus0; None if no x > 0 pays. F is a cubic with a negative leading coefficient and
    F(0) = -wf <= 0, so on x > 0 the payable set is empty or ONE interval (contiguous by construction): with wf = 0 it
    is (0, x+] with x+ the positive root of q; with wf > 0 it lies between the two roots that bracket the local maximum
    of F, found by bisection on [0, x_max] and [x_max, (1 - wf)/c] (F < 0 at both outer ends)."""
    a3, a2, a1, a0 = payable_poly(n, d, c, wf)
    F = lambda x: ((a3 * x + a2) * x + a1) * x + a0
    if wf == 0.0:
        q0 = 2.0 * n - c - d
        if q0 <= MARGINAL_TOL:
            return None
        A, B = n * n * c, n * n - 2.0 * n * c
        return [0.0, (B + math.sqrt(B * B + 4.0 * A * q0)) / (2.0 * A)]
    x_end = (1.0 - wf) / c
    disc = 4.0 * a2 * a2 - 12.0 * a3 * a1
    if x_end <= 0.0 or disc < 0.0:
        return None
    x_max = max((-2.0 * a2 + sg * math.sqrt(disc)) / (6.0 * a3) for sg in (-1.0, 1.0))   # local maximum of F
    if not (0.0 < x_max < x_end) or F(x_max) < 0.0:
        return None

    def root(a, bb):            # F(a) and F(bb) have opposite signs
        fa = F(a) >= 0.0
        for _ in range(200):
            m = 0.5 * (a + bb)
            if (F(m) >= 0.0) == fa:
                a = m
            else:
                bb = m
        return 0.5 * (a + bb)
    return [root(0.0, x_max), root(x_max, x_end)]


# ---------------------------------------------------------------------------------------------------- evidence reads
def matrix_entry_summary(e):
    src = e.get("source") or {}
    return {"id": e["id"], "quantity": e.get("quantity"), "value": e.get("value"), "units": e.get("units"),
            "evidence_class": e.get("evidence_class"), "evidence_level": e.get("evidence_level"),
            "access": src.get("access"), "locator": e.get("locator"), "citation": src.get("citation"),
            "doi_or_url": src.get("doi_or_url"),
            "regime_match": (e.get("applicability_to_abep") or {}).get("regime_match")}


def electrical_evidence(elec):
    hd = elec["components"]["hall_discharge"]
    series = [e for e in hd["entries"] if e.get("role") == "efficiency-candidate" and e.get("value_kind") == "series"]
    effs = [pt["efficiency"] for e in series for pt in e["value"]]
    pows = [pt["P_out_W"] for e in series for pt in e["value"]]
    ppu = {"range": [min(effs), max(effs)], "ids": [e["id"] for e in series],
           "evidence_class": sorted({e["evidence_class"] for e in series}),
           "evidence_level": sorted({e["evidence_level"] for e in series}),
           "chain_stage": series[0]["chain_stage"], "source_ids": sorted({s for e in series for s in e["source_ids"]}),
           "P_out_W_span": [min(pows), max(pows)],
           "applicability": series[0]["applicability"],
           "validation_status": series[0]["validation_status"],
           "use": "eta_ppu,d range for bus-referencing the Hall discharge price Pi_H = V_d/(eta_b eta_ppu,d); "
                  "breakeven_v1's single analysis value 0.9 lies inside it. Applicability-limited: 200-1000 W "
                  "output, 250/400 V output, 24-34 V bus breadboard; V_d = 150 V is below the measured output range"}
    rf = elec["components"]["rf_source"]
    cand = {e["id"]: e for e in rf["entries"]}
    gen_vals = []
    for eid in ("RF-NEWORBIT25", "RF-VOLKMAR18"):
        v = cand[eid]["value"]
        gen_vals += [v] if isinstance(v, (int, float)) else [v["min"], v["max"]]
    gen = {"range": [min(gen_vals), max(gen_vals)],
           "entries": [{"id": eid, "value": cand[eid]["value"], "chain_stage": cand[eid]["chain_stage"],
                        "evidence_class": cand[eid]["evidence_class"], "evidence_level": cand[eid]["evidence_level"],
                        "uncertainty": cand[eid]["uncertainty"], "source_ids": cand[eid]["source_ids"]}
                       for eid in ("RF-NEWORBIT25", "RF-VOLKMAR18")],
           "tbd": [{"id": eid, "quantity": cand[eid]["quantity"], "tbd_requires": cand[eid]["tbd_requires"]}
                   for eid in ("RF-MATCH-LOSS", "RF-LOAD")],
           "load_plane": rf["load_plane"],
           "note": "0.92 is an RF-generator-stage nominal (bus -> RFG output) and is therefore an UPPER bound on the "
                   "bus -> coil-feed chain (electrical_closure rule: stage-only efficiencies bound the chain); 0.60-0.70 "
                   "is RFG DC input -> coil feed at low xenon flow. Matching/cable loss is TBD (RF-MATCH-LOSS)."}
    rules = elec.get("rules", [])
    return ppu, gen, rules, elec.get("open_questions_for_owner", [])


def interstage_basis(inter_py_text, inter_md_text):
    mv = re.search(r'^MODEL_VERSION\s*=\s*"([^"]+)"', inter_py_text, re.M)
    if not mv:
        raise OverlayInputError("interstage.py: MODEL_VERSION not found")
    must = ['H_STRONG_B = "strong_axial_B_no_radial_loss"', "def compare_with_required", "def eta_transport_evidence"]
    for m in must:
        if m not in inter_py_text:
            raise OverlayInputError(f"interstage.py: expected text {m!r} not found (pin mismatch?)")
    if "valid T < 1200 K" not in inter_md_text:
        raise OverlayInputError("INTERSTAGE_MODEL.md: expected DR-rate validity statement not found")
    return {
        "model": mv.group(1),
        "range": [ETA_T[0], ETA_T[-1]],
        "range_class": PROPOSED,
        "air_value": "TBD - interstage_v1 refuses every realistic air case: the only sourced N2+/O2+ dissociative-"
                     "recombination rates are valid below 1200 K (0.103 eV), far below the interstage T_e; the "
                     "junction ion-capture fraction, a magnetized wall-flux closure, N/O wall recombination and the "
                     "RF source exit state are also TBD (INTERSTAGE_MODEL.md sections 1, 6 and 9)",
        "upper_bound_basis": "eta_t <= 1 on the ion-current basis for a source-free duct (breakeven_v1 accepts "
                             "0 < eta_t <= 1; in-duct ionization, eta_t > 1, is refused there). interstage_v1's "
                             "strong_axial_B_no_radial_loss closure (h = 0, Lieberman short course slide 53) with junction "
                             "capture 1 is the idealized upper limit on duct transmission, not a prediction",
        "lower_bound_basis": "0.1 is the lower end of the owner-requested analysis span (breakeven_v1 ETA_T); it is "
                             "NOT a physical bound. eta_t below 0.1 only moves every placement towards "
                             "CLEARLY_ABOVE_BREAKEVEN",
        "ion_basis": "eta_t = ion CURRENT delivered into the Hall channel / ion current leaving the source; it pairs "
                     "with costs in W per A (INTERSTAGE_MODEL.md section 8); a cost per ion COUNT pairs with "
                     "eta_transport_particle",
        "evidence_class": "assumed (analysis range); no measured or model-derived air value exists",
    }


# ---------------------------------------------------------------------------------------------------- evidence units
def absorbed_per_beam_A(P_W, mdot_mg_s, eta_u, ion_mass_kg, e_c):
    """Absorbed W per A of singly charged beam ions: P / (eta_u * mdot / m_ion * e)."""
    I = eta_u * mdot_mg_s * 1e-6 / ion_mass_kg * e_c
    return P_W / I


def energy_per_injected(P_W, mdot_mg_s, feed_mass_kg, e_c):
    return P_W / (mdot_mg_s * 1e-6 / feed_mass_kg) / e_c


def build_units(M, gen, K):
    """Placement units: one per published cost that can be put on a W-per-A basis, plus NOT_PLACEABLE records for
    every other entry of the cost-relevant topics."""
    e_c, amu = K["E_CHARGE"], K["AMU"]
    mN2, mO, mO2 = K["M_N2"], K["M_O"], K["M_O2"]
    g_lo, g_hi = gen["range"]
    units = []

    # --- NewOrbit gridded RF ion engine on 50:50 N2/O2 (bus-referred at the RFG input)
    P = M["RF-NO25-02"]["value"]
    I_mA = M["RF-NO25-09"]["value"]
    c_lo, c_hi = P["min"] / (I_mA["max"] * 1e-3), P["max"] / (I_mA["min"] * 1e-3)
    d1 = M["RF-NO25-D1"]["value"]
    units.append({
        "unit_id": "U-RF-NO25-air-gridded",
        "matrix_ids": ["RF-NO25-D1", "RF-NO25-02", "RF-NO25-09", "RF-NO25-01"],
        "gas": M["RF-NO25-02"]["conditions"]["gas"],
        "reported": {"value": [d1["min"], d1["max"]], "units": "W/A",
                     "quantity": M["RF-NO25-D1"]["quantity"],
                     "evidence_class": M["RF-NO25-D1"]["evidence_class"], "evidence_level": M["RF-NO25-D1"]["evidence_level"],
                     "recomputed_from_ranges": [c_lo, c_hi]},
        "power_reference": "bus",
        "power_reference_note": "RF-generator DC input drawn from the unregulated 26-32 V bus (RF-NO25-01: 'from the "
                                "unregulated bus to RF'); in bus_power_boundary_v1 this is P_bus[rf_source] when the RF "
                                "generator is fed directly from the propulsion DC bus",
        "ion_basis_reported": "A of grid-extracted beam (screen current, V_sc = 2000 V)",
        "conversion_chain": [
            {"step": "power reference -> P_bus[rf_source]", "status": "sourced", "factor": [1.0, 1.0],
             "evidence": ["RF-NO25-01 (measured, level 3)", "electrical_closure RF-NEWORBIT25"],
             "condition": "RF generator draws directly from the propulsion DC bus as in the source. If Vyovrinda "
                          "inserts a bus -> RFG converter, divide by its efficiency (TBD, <= 1; the bus voltage is an "
                          "open owner question in electrical_closure_data_v1): that can only RAISE the cost"},
            {"step": "ion basis: extracted beam A -> A of ions leaving a gridless source exit", "status": "missing",
             "factor": [0.0, 1.0], "direction": "can only LOWER the cost (multiply by I_beam/I_exit <= 1) at the "
                                                "SAME discharge state",
             "missing_quantity": "ion extraction fraction I_beam/I_exit (effective screen-grid ion transparency) at the "
                                 "reported set points; also whether the gridded discharge regime transfers to a "
                                 "pre-ionizer regime (regime_match 'partial'): removing the grids changes neutral "
                                 "confinement, so the same RFG power need not give the same discharge state. The upper "
                                 "bound hi is conditional on that transfer"},
            {"step": "set-point pairing", "status": "missing", "factor": [1.0, 1.0],
             "direction": "narrows the interval, no shift",
             "missing_quantity": "per-set-point (P_RFG, I_beam) pairs; only ranges are in the text (source Fig. 14 or "
                                 "data needed; the corner bound spans the whole interval)"},
        ],
        "C_src_bus_W_per_A": {"lo": 0.0, "hi": c_hi, "lo_open": True,
                              "basis": "bus W per A of source-exit ions; lo -> 0 because the ion-basis factor is "
                                       "unbounded below; hi = corner bound (max P / min I)",
                              "conditional_on": ["the gridded discharge state transfers to the gridless pre-ionizer "
                                                 "(hi)", "the RF generator is fed directly from the propulsion DC bus "
                                                 "(otherwise divide by a bus -> RFG converter efficiency <= 1, which "
                                                 "raises hi)"]},
        "C_src_if_missing_factors_equal_1": [c_lo, c_hi],
        "caveats": ["inferred corner bound from ranges; true per-set-point values lie inside",
                    "gridded RF ion engine, not a pre-ionizer; extracted current is not ion production",
                    "50:50 N2/O2 mix; beam species/charge split unknown (RF-NO25-05 hints monatomic ions); breakeven "
                    "surfaces assume equal delivered and Hall-born mix (A8)",
                    "preprint (Research Square, CC BY 4.0) of IEPC-2025-378"],
    })

    # --- Zhou et al. 2024 HYPHEN model points (absorbed power, model-derived, level 6)
    zhou = [
        ("U-RF-ZHOU24-N2-1500W", ["RF-ZHOU24-D1", "RF-ZHOU24-05", "RF-ZHOU24-06"], "RF-ZHOU24-05", "N2", 1500.0,
         M["RF-ZHOU24-05"]["value"], "Table 5 value", mN2, [("N2+ (all molecular)", mN2), ("N+ (all atomic)", mN2 / 2)],
         "RF-ZHOU24-D1"),
        ("U-RF-ZHOU24-N2-2000W", ["RF-ZHOU24-D2", "RF-ZHOU24-07", "RF-ZHOU24-01", "RF-ZHOU24-08"], "RF-ZHOU24-07", "N2",
         2000.0, M["RF-ZHOU24-07"]["value"], "Table 5 value", mN2,
         [("N2+ (all molecular)", mN2), ("N+ (all atomic)", mN2 / 2)], "RF-ZHOU24-D2"),
        ("U-RF-ZHOU24-N2-1400W-eta_u75", ["RF-ZHOU24-03"], "RF-ZHOU24-03", "N2", float(M["RF-ZHOU24-03"]["value"]), 0.75,
         "'eta_u ~ 75 %' as stated in the entry (text value, approximate)", mN2,
         [("N2+ (all molecular)", mN2), ("N+ (all atomic)", mN2 / 2)], None),
        ("U-RF-ZHOU24-O-1500W", ["RF-ZHOU24-D3", "RF-ZHOU24-09", "RF-ZHOU24-10"], "RF-ZHOU24-09", "O", 1500.0,
         M["RF-ZHOU24-09"]["value"], "Table 5 value", mO, [("O+", mO)], "RF-ZHOU24-D3"),
        ("U-RF-ZHOU24-O-700W-eta_u75", ["RF-ZHOU24-04"], "RF-ZHOU24-04", "O", float(M["RF-ZHOU24-04"]["value"]), 0.75,
         "'eta_u ~ 75 %' as stated in the entry (text value, approximate)", mO, [("O+", mO)], None),
        ("U-RF-ZHOU24-O2-1500W", ["RF-ZHOU24-11"], "RF-ZHOU24-11", "O2", 1500.0, M["RF-ZHOU24-11"]["value"],
         "Table 5 value", mO2, [("O2+ (all molecular)", mO2), ("O+ (all atomic)", mO2 / 2)], None),
    ]
    for uid, ids, anchor, gas, P_W, eta_u, eta_u_basis, m_feed, ions, d_id in zhou:
        cond = M[anchor]["conditions"]
        mdot = float(cond["mass_flow_mg_s"])
        E_inj = energy_per_injected(P_W, mdot, m_feed, e_c)
        per_ion = {lab: absorbed_per_beam_A(P_W, mdot, eta_u, m_i, e_c) for lab, m_i in ions}
        a_lo, a_hi = min(per_ion.values()), max(per_ion.values())
        rep = {"value": E_inj, "units": "eV per injected " + ("molecule" if gas in ("N2", "O2") else "atom"),
               "quantity": f"absorbed power {P_W:g} W at {mdot:g} mg/s {gas}, eta_u {eta_u:g} ({eta_u_basis})",
               "evidence_class": "model-derived (set point, eta_u); energy per particle inferred by our arithmetic",
               "evidence_level": M[anchor]["evidence_level"]}
        if d_id:
            rep["matrix_value_check"] = {"id": d_id, "matrix_value": M[d_id]["value"]}
        units.append({
            "unit_id": uid, "matrix_ids": ids, "gas": gas,
            "reported": rep,
            "power_reference": "absorbed",
            "power_reference_note": "plasma-absorbed power P_a prescribed in the HYPHEN simulation (before any RF-chain "
                                    "loss); Xe-fitted anomalous transport reused for air (RF-ZHOU24-14, level 6)",
            "ion_basis_reported": "beam ions leaving the simulated electrodeless thruster (mass-based eta_u)",
            "absorbed_W_per_beam_A_by_ion_assumption": {k: v for k, v in per_ion.items()},
            "conversion_chain": [
                {"step": "absorbed energy per injected particle -> absorbed W per A of beam ions", "status":
                 "inferred (our arithmetic on model-derived set points)",
                 "formula": "P_a / (eta_u * mdot / m_ion * e), singly charged ions",
                 "factor_note": "the beam species split is not given per case: bounded by the all-molecular and "
                                "all-atomic singly charged beams" if len(ions) > 1 else "single atomic ion species",
                 "missing_quantity": "beam species and charge-state split (Z = 1 is ASSUMED; multiply charged ions "
                                     "would lower the W per A; verify in the source)"},
                {"step": "absorbed -> net RF at the coil feed (divide by antenna coupling eta_ant = P_abs/P_coil)",
                 "status": "missing", "factor": [1.0, None], "direction": "can only RAISE the cost (eta_ant <= 1)",
                 "missing_quantity": "antenna/plasma coupling on air at the operating point (forward, reflected, "
                                     "matching-network and antenna loss; RF_SOURCE_EVIDENCE.md section 4 item 3)",
                 "non_applicable_candidates": ["RF-TAKA22-D1 0.8756-0.9067 (Ar, 5 kW, R-method; regime_match 'no')",
                                               "RF-ANDR24-01 0.8 (assumed constant transferred from Xe/I2 work)",
                                               "RF-IPG6S-04 <= 0.25 (air; calorimetric plume power / supply active "
                                               "power: a different definition, not a coupling efficiency)"]},
                {"step": "coil feed -> P_bus[rf_source] (divide by eta_rf_source, bus -> coil feed)",
                 "status": "sourced (evidence range, applicability-limited)", "factor": [1.0 / g_hi, 1.0 / g_lo],
                 "range_eta": [g_lo, g_hi],
                 "evidence": ["electrical_closure RF-NEWORBIT25 (0.92 nominal, bus -> RFG output; upper bound on the "
                              "chain)", "electrical_closure RF-VOLKMAR18 (0.60-0.70, RFG DC input -> coil feed, Xe, "
                              "low flow)", "RF-NO25-01", "RF-VOLK18-D1"],
                 "missing_quantity": "matching-network and cable loss on air across the ABEP flow range (electrical_"
                                     "closure RF-MATCH-LOSS: TBD)"},
                {"step": "fixed rf_source loads", "status": "not applied (conservative for the lower bound)",
                 "note": "the model has an applied field (B = 0.12 T, a model input). If an electromagnet produces "
                         "it (not stated in the matrix entries; verify in the source), its power is not in P_a. "
                         "bus_power_boundary_v1 has no RF magnet component, so it would be booked inside rf_source "
                         "as a non-ion-scaling (fixed) load, which LOWERS the payable cost (Y_sup_fixed_overhead_"
                         "normalized); leaving it out keeps the lower bound of C_src valid"},
            ],
            "C_src_bus_W_per_A": {"lo": a_lo / g_hi, "hi": None, "lo_open": False,
                                  "basis": f"bus W per A of source-exit ions; lo = absorbed / {g_hi:g} with eta_ant <= 1 "
                                           "and the all-atomic singly charged beam; hi unbounded (eta_ant TBD)",
                                  "conditional_on": ["singly charged beam ions (Z = 1 ASSUMED; a multiply charged share "
                                                     "would lower lo, by at most a factor Z)",
                                                     "the model point itself (level 6; prescribed power deposition, "
                                                     "Xe-fitted transport reused for air)"]},
            "C_src_if_missing_factors_equal_1": [a_lo / g_hi, a_hi / g_lo],
            "caveats": ["model-derived (level 6): Xe-fitted anomalous transport reused for air; not measured",
                        "a whole electrodeless thruster (magnetic nozzle), not a pre-ionizer feeding a Hall channel",
                        f"feed {gas} at {mdot:g} mg/s; ABEP inlet state TBD (ICD)",
                        "equal delivered/Hall-born mix assumed by the surfaces (A8)"],
        })

    for u in units:
        lo, hi = u["C_src_bus_W_per_A"]["lo"], u["C_src_bus_W_per_A"]["hi"]
        u["C_src_bus_W_per_A"]["lo"] = g6(lo)
        u["C_src_bus_W_per_A"]["hi"] = g6(hi) if hi is not None else None
        u["C_src_if_missing_factors_equal_1"] = [g6(x) for x in u["C_src_if_missing_factors_equal_1"]]
        if "recomputed_from_ranges" in u["reported"]:
            u["reported"]["recomputed_from_ranges"] = [g6(x) for x in u["reported"]["recomputed_from_ranges"]]
        if isinstance(u["reported"]["value"], float):
            u["reported"]["value"] = g6(u["reported"]["value"])
        if "absorbed_W_per_beam_A_by_ion_assumption" in u:
            u["absorbed_W_per_beam_A_by_ion_assumption"] = {k: g6(v) for k, v in
                                                          u["absorbed_W_per_beam_A_by_ion_assumption"].items()}
        for st in u["conversion_chain"]:
            if "factor" in st and isinstance(st["factor"], list):
                st["factor"] = [g6(x) if x is not None else None for x in st["factor"]]
    return units


NOT_PLACEABLE = [
    ("RF-NO25-03", "electron current extracted from an RF plasma cathode, not ion production",
     "ion current leaving the cathode plasma (or its ion production rate) per bus W"),
    ("RF-NO25-D2", "bus W per A of extracted ELECTRON current (cathode), not an ion production cost",
     "ion current leaving the cathode plasma per bus W"),
    ("RF-ZHOU24-06", "share of absorbed power in inelastic collisions; the set point is placed as U-RF-ZHOU24-N2-1500W",
     "an ion current (a power fraction carries none); the same set point is placed through its eta_u"),
    ("RF-ZHOU24-08", "share of absorbed power in inelastic collisions; the set point is placed as U-RF-ZHOU24-N2-2000W",
     "an ion current (a power fraction carries none); the same set point is placed through its eta_u"),
    ("RF-ZHOU24-10", "share of absorbed power in inelastic collisions; the set point is placed as U-RF-ZHOU24-O-1500W",
     "an ion current (a power fraction carries none); the same set point is placed through its eta_u"),
    ("RF-ZHOU24-02", "absorbed power at the model's maximum thrust efficiency on atomic O (1250 W, 1 mg/s)",
     "propellant utilization eta_u (or beam current) at that set point"),
    ("RF-IPG6S-08", "ionization degree of the IPG6-S air/O2 plasma was not measured (value TBD in the source)",
     "ion current or ionization fraction with the flow and power at the bus"),
    ("RF-SCHU24-D2", "ionization fraction n_e/n_n of an 80/20 N2/O2 ICP at 10 Pa, 800 W: a density ratio, no ion outflow",
     "ion current leaving the source (or wall ion-loss flux) at a stated bus power; the generator/matchbox losses are "
     "not separated either (RF-SCHU24-05)"),
    ("RF-TAKA22-05", "thrust efficiency of the Michigan RF plasma thruster as re-tabulated (secondary; gas not stated)",
     "ion beam current or mass utilization and the gas; primary not accessed"),
    ("RF-DUPP26-02", "review-table thrust-to-power range (assumed; not supported by an accessed primary)",
     "any measured ion current per power"),
    ("RF-SITA19-02", "RAM-EP thrust of a double-stage device whose ionization stage the performance model powers "
                     "by a discharge voltage; no RF source is described (RF-SITA19-01)",
     "an RF-source quantity (this entry is outside the RF evidence scope)"),
]


# ---------------------------------------------------------------------------------------------------- classification
def classify(lo, hi, lo_open, Y_lo, Y_hi, et_lo, et_hi):
    """Placement of a C_src interval [lo, hi] (hi None = unbounded; lo_open: lo itself excluded) against the payable
    condition C_src <= eta_t * Y with Y in [Y_lo, Y_hi] and eta_t in [et_lo, et_hi]."""
    top = et_hi * Y_hi
    if lo > top or (lo_open and lo >= top):
        return "ABOVE"
    if hi is not None and hi <= et_lo * Y_lo:
        return "BELOW"
    return "STRADDLES"


def overall(per_case):
    if all(per_case[c] == "ABOVE" for c in CASE_ORDER):
        return "CLEARLY_ABOVE_BREAKEVEN", None
    for c in CASE_ORDER:
        if per_case[c] == "BELOW":
            return "CLEARLY_BELOW", c
    return "STRADDLES", None


# ---------------------------------------------------------------------------------------------------- build
def build(extra_roots):
    found = resolve_inputs(extra_roots)
    b, K_mod = load_breakeven(found)
    K = {"E_CHARGE": K_mod.E_CHARGE, "AMU": K_mod.AMU, "M_N2": K_mod.M_SPECIES["N2"], "M_O": K_mod.M_SPECIES["O"],
         "M_O2": K_mod.M_SPECIES["O2"]}
    with open(found["rf_evidence_matrix"][1]) as f:
        rfm = json.load(f)
    M = {e["id"]: e for e in rfm["entries"]}
    with open(found["electrical_closure_data"][1]) as f:
        elec = json.load(f)
    with open(found["interstage_module"][1]) as f:
        inter_py = f.read()
    with open(found["interstage_model_doc"][1]) as f:
        inter_md = f.read()
    with open(found["breakeven_derivation"][1]) as f:
        bd_md = f.read()
    for needle in ("C_del*,0 = Π_H (ρ_H/ρ_S) (2R_T − R_P − (1 − α))", "C_src* = η_t · C_del*"):
        if needle not in bd_md:
            raise OverlayInputError(f"BREAKEVEN_DERIVATION.md: expected relation {needle!r} not found")
    if elec.get("boundary_version") != BOUNDARY_VERSION:
        raise OverlayInputError("electrical_closure_data_v1 boundary_version is not bus_power_boundary_v1")

    G = Glue(b, K["AMU"], K["M_N2"] / K["AMU"])
    ppu, gen, elec_rules, elec_questions = electrical_evidence(elec)
    ppu_lo, ppu_hi = ppu["range"]
    eta_t = interstage_basis(inter_py, inter_md)
    et_lo, et_hi = eta_t["range"]
    checks = {}

    # ---------- normalized payable delivered cost c_k = Y / Pi_H (no fixed overhead)
    c_norm, worst = {}, 0.0
    for case in CASE_ORDER:
        for eb in ETA_B:
            for ev in ETA_V:
                r = G.ref(1.0, 0.6, eb, ev, 1.0)
                rs = G.resp(case, r)
                Pi = 1.0 / eb
                c_marg = b.marginal_breakeven_delivered_cost(r, rs) / Pi
                sup = b.supremum_breakeven_delivered_cost(r, rs, 0.0, 64)["sup_W_per_A"] / Pi
                cf = closed_form_c(case, eb, ev)
                worst = max(worst, abs(c_marg - cf), abs(sup - c_marg))
                c_norm.setdefault(case, {})[f"eta_b={eb}|eta_v={ev}"] = g6(c_marg)
    checks["c_norm_matches_closed_form_and_supremum"] = {"max_abs_diff": worst, "pass": worst < 1e-9}

    # ---------- Y: payable bus W per delivered A over the declared box
    Ytab, box = {}, {}
    for case in CASE_ORDER:
        evs = ETA_V if case == "optimistic_bound" else [0.9]
        allv = []
        for V in V_D:
            for eb in ETA_B:
                vals = [G.Y(case, V, eb, ev, pp) for ev in evs for pp in (ppu_lo, ppu_hi)]
                Ytab.setdefault(case, {}).setdefault(f"V_d={V:g}", {})[f"eta_b={eb}"] = [g6(min(vals)), g6(max(vals))]
                allv += vals
        box[case] = [min(allv), max(allv)]
    Y_min_box, Y_max_box = box["add_only"][0], box["optimistic_bound"][1]
    # ordering add <= cost <= optimistic at every point (equal mix)
    order_ok = all(Ytab["add_only"][v][e][1] <= Ytab["cost_offset"][v][e][1] + 1e-9 and
                   Ytab["cost_offset"][v][e][1] <= Ytab["optimistic_bound"][v][e][1] + 1e-9
                   for v in Ytab["add_only"] for e in Ytab["add_only"][v])
    checks["case_ordering_add_le_cost_le_optimistic"] = {"pass": order_ok}

    # ---------- X: required relative utilization gain x* = d_eta_u*/eta_u0 vs total overhead fraction omega
    Xtab, worst = {}, 0.0
    for case in CASE_ORDER:
        for eb, ev in variants(case):
            ebv = eb if eb is not None else 0.7
            evv = ev if ev is not None else 0.9
            rows = []
            for w in OMEGA:
                xs, capped = [], []
                for u0 in ETA_U0:
                    r = G.ref(300.0, u0, ebv, evv, 0.9)
                    P0b = b.hall_only_state(r)["P_d_bus_W"]
                    out = b.required_utilization_gain(r, G.resp(case, r), G.overhead(w * P0b))
                    xs.append(out["delta_s_star"] / u0 if out["delta_s_star"] is not None else None)
                    if out["status"] == "INFEASIBLE_UTILIZATION_CAP":
                        capped.append(u0)
                    elif not out["status"].startswith("OK"):
                        raise OverlaySelfCheckError(f"unexpected status {out['status']} in X table")
                if any(x is None for x in xs) or max(xs) - min(xs) > 1e-9 * max(1.0, max(xs)):
                    raise OverlaySelfCheckError("x* should not depend on eta_u0 except through the cap")
                if case == "add_only":
                    worst = max(worst, abs(xs[0] - (w / (1.0 - w))))
                rows.append([w, g6(xs[0]), capped])
            Xtab[vkey(case, eb, ev)] = rows
    checks["add_only_X_equals_omega_over_1_minus_omega"] = {"max_abs_diff": worst, "pass": worst < 1e-9}

    # ---------- coupled X-Y: payable relative gain interval for a delivered-cost ratio c and fixed overhead omega_f
    coupled, worst, worst_root = {}, 0.0, 0.0
    for case in CASE_ORDER:
        for eb, ev in variants(case):
            n, d = n_d(case, eb if eb is not None else 0.7, ev if ev is not None else 0.9)
            tab = {}
            for wf in OMEGA_F_COUPLED:
                rows = []
                for c in C_NORM:
                    iv = payable_x_interval(n, d, c, wf)
                    rows.append([c] + ([g6(iv[0]), g6(iv[1])] if iv else [None, None]))
                    if iv:              # endpoints are roots of the unfactored inequality, the middle pays
                        g = lambda x: (1.0 + n * x) ** 2 * (1.0 - wf - c * x) - (1.0 + d * x)
                        ends = [iv[1]] if wf == 0.0 else iv
                        worst_root = max([worst_root] + [abs(g(x)) for x in ends])
                        if g(0.5 * (iv[0] + iv[1])) <= 0.0:
                            worst_root = math.inf
                    if case == "add_only" and iv:
                        A = 1.0 - wf - c
                        disc = A * A - 4.0 * c * wf
                        lo_cf = 0.0 if wf == 0.0 else (A - math.sqrt(disc)) / (2.0 * c)
                        hi_cf = (A + math.sqrt(disc)) / (2.0 * c)
                        worst = max(worst, abs(iv[0] - lo_cf), abs(iv[1] - hi_cf))
                tab[f"omega_f={wf}"] = rows
            coupled[vkey(case, eb, ev)] = tab
    checks["coupled_interval_endpoints_are_roots"] = {"max_abs_diff": worst_root, "pass": worst_root < 1e-9}
    checks["add_only_coupled_interval_matches_quadratic"] = {"max_abs_diff": worst, "pass": worst < 1e-9}
    # cross-check the coupled solver and the R(x) algebra against breakeven_v1 directly
    worst = 0.0
    for case in CASE_ORDER:
        for eb, ev in variants(case):
            ebv, evv = (eb if eb is not None else 0.7), (ev if ev is not None else 0.9)
            n, d = n_d(case, ebv, evv)
            r = G.ref(300.0, 0.3, ebv, evv, 0.9)
            rs = G.resp(case, r)
            for x in (0.01, 0.1, 0.5, 1.0):
                R_mod = b.efficiency_ratio(r, rs, x * 0.3)
                worst = max(worst, abs(R_mod - (1 + n * x) ** 2 / (1 + d * x)))
    checks["R_of_x_matches_breakeven_efficiency_ratio"] = {"max_abs_diff": worst, "pass": worst < 1e-12}
    # the coupled interval against breakeven_v1.place_evidence (self-check values, eta_u0 = 0.3, eta_t = 1)
    pe = []
    for case, c, wf in (("add_only", 0.5, 0.0), ("cost_offset", 0.8, 0.02), ("optimistic_bound", 0.7, 0.05),
                        ("optimistic_bound", 1.2, 0.05)):
        r = G.ref(300.0, 0.3, 0.7, 0.9, 0.9)
        rs = G.resp(case, r)
        h = b.hall_only_state(r)
        C = c * h["Pi_H_bus_W_per_A"]
        res = b.place_evidence(r, rs, wf * h["P_d_bus_W"], b.Evidenced(C, "W/A", "assumed", "overlay self-check"),
                               b.Evidenced(1.0, "1", "assumed", "overlay self-check"), 400)
        n, d = n_d(case, 0.7, 0.9)
        iv = payable_x_interval(n, d, c, wf)
        cap = (1.0 - 0.3) / 0.3
        mine = [iv[0] * 0.3, min(iv[1], cap) * 0.3] if iv and iv[0] <= cap else None
        theirs = res.get("payable_delta_s")
        if mine is None:
            ok = res["status"] != "BREAK_EVEN_POSSIBLE"
        else:
            ok = bool(theirs) and all(abs(a - bb) <= 2e-3 * max(1e-3, abs(bb)) for a, bb in zip(mine, theirs))
        pe.append({"case": case, "c": c, "omega_f": wf,
                   "overlay_delta_s": [g6(x) for x in mine] if mine else None,
                   "breakeven_place_evidence_delta_s": [g6(x) for x in theirs] if theirs else None,
                   "status": res["status"], "pass": ok})
    checks["coupled_solver_matches_place_evidence"] = {"cases": pe, "pass": all(p["pass"] for p in pe)}

    # supply side through two bus_power_boundary_v1-format ledgers: overhead_from_boundary_ledgers ->
    # achievable_delivered_share -> evaluate_arm must agree with the coupled inequality (self-check values only)
    led = []
    for case, c, et, frac, wf in (("add_only", 0.6, 0.8, 0.05, 0.0), ("cost_offset", 0.9, 0.7, 0.1, 0.02),
                                  ("optimistic_bound", 0.9, 0.9, 0.08, 0.03), ("add_only", 1.1, 0.5, 0.1, 0.0)):
        r = G.ref(300.0, 0.3, 0.7, 0.9, 0.9)
        rs = G.resp(case, r)
        h = b.hall_only_state(r)
        P0b, Pi = h["P_d_bus_W"], h["Pi_H_bus_W_per_A"]
        C_src = c * et * Pi                       # so that C_del = C_src / eta_t = c * Pi_H
        P_gen = frac * P0b
        sup = b.achievable_delivered_share(r, rs, P_gen, C_src, et)
        hall_items = [{"component": k, "P_bus_W": P0b if k == "hall_discharge" else 1.0} for k in b.COMMON_COMPONENTS]
        arm_items = [{"component": k, "P_bus_W": P0b if k == "hall_discharge" else
                      1.0 + (wf * P0b if k == "housekeeping" else 0.0)} for k in b.COMMON_COMPONENTS]
        arm_items.append({"component": "rf_source", "P_bus_W": P_gen})
        ov = b.overhead_from_boundary_ledgers(
            {"boundary_version": BOUNDARY_VERSION, "architecture": ARCH, "items": arm_items},
            {"boundary_version": BOUNDARY_VERSION, "architecture": REFERENCE_ARCH, "items": hall_items})
        ev = b.evaluate_arm(r, rs, ov, sup["delta_s"])
        x = sup["delta_s"] / 0.3
        n, d = n_d(case, 0.7, 0.9)
        mine = (1.0 + n * x) ** 2 * (1.0 - wf - c * x) >= 1.0 + d * x
        ok = (mine == ev["master_breaks_even"] and abs(ev["omega"] - (wf + c * x)) < 1e-9
              and ov.boundary_v1_conformant and abs(ev["equal_bus_power"]["ledger_residual_W"]) < 1e-9 * P0b
              and abs(sup["delivered_cost_W_per_A"] - c * Pi) < 1e-9 * Pi)
        led.append({"case": case, "c": c, "eta_t": et, "rf_source_over_P_d_bus0": frac, "omega_f": wf,
                    "x": g6(x), "overlay_breaks_even": mine, "evaluate_arm_master_breaks_even": ev["master_breaks_even"],
                    "pass": ok})
    checks["ledger_supply_side_matches_coupled_inequality"] = {"cases": led, "pass": all(p["pass"] for p in led)}

    # ---------- fixed-overhead supremum c_sup(omega_f) = Y_sup / Pi_H
    fixed = {}
    for case in CASE_ORDER:
        for eb, ev in variants(case):
            ebv, evv = (eb if eb is not None else 0.7), (ev if ev is not None else 0.9)
            tab = {}
            for u0 in ETA_U0:
                r = G.ref(300.0, u0, ebv, evv, 0.9)
                rs = G.resp(case, r)
                h = b.hall_only_state(r)
                row = []
                for wf in OMEGA_F:
                    s = b.supremum_breakeven_delivered_cost(r, rs, wf * h["P_d_bus_W"], 64)
                    row.append([wf, g6(s["sup_W_per_A"] / h["Pi_H_bus_W_per_A"])])
                tab[f"eta_u0={u0}"] = row
            fixed[vkey(case, eb, ev)] = tab

    # ---------- Z: minimum eta_t = C_src / Y at reference slices
    Ztab = {}
    for case in CASE_ORDER:
        for V in V_D_SLICES:
            for eb in ETA_B:
                y_lo, y_hi = Ytab[case][f"V_d={V:g}"][f"eta_b={eb}"]
                Ztab.setdefault(case, {})[f"V_d={V:g}|eta_b={eb}"] = [[C, g6(C / y_hi), g6(C / y_lo)] for C in C_SRC_GRID]

    # ---------- payable region in (eta_t, C_src)
    region_lines = []
    for et in ETA_T:
        row = {"eta_t": et, "outer_envelope_C_src_max": g6(et * Y_max_box),
               "inner_envelope_C_src_max": g6(et * Y_min_box)}
        for case in CASE_ORDER:
            y = Ytab[case]["V_d=300"]["eta_b=0.7"]
            row[f"{case}@V_d=300,eta_b=0.7"] = [g6(et * y[0]), g6(et * y[1])]
        region_lines.append(row)

    # ---------- evidence placements
    units = build_units(M, gen, K)
    for u in units:
        if u["reported"].get("matrix_value_check"):
            mv = u["reported"]["matrix_value_check"]["matrix_value"]
            ok = abs(u["reported"]["value"] - mv) <= 0.5e-1 + 1e-9 * abs(mv)
            if not ok:
                raise OverlaySelfCheckError(f"{u['unit_id']}: recomputed {u['reported']['value']} vs matrix {mv}")
        if "recomputed_from_ranges" in u["reported"]:
            rc, rv = u["reported"]["recomputed_from_ranges"], u["reported"]["value"]
            if abs(rc[0] - rv[0]) > 0.05 or abs(rc[1] - rv[1]) > 0.05:
                raise OverlaySelfCheckError(f"{u['unit_id']}: corner bound {rc} vs matrix {rv}")
        C = u["C_src_bus_W_per_A"]
        per_case = {case: classify(C["lo"], C["hi"], C["lo_open"], box[case][0], box[case][1], et_lo, et_hi)
                    for case in CASE_ORDER}
        pl, stated = overall(per_case)
        slices = {}
        for V in V_D_SLICES:
            for eb in ETA_B:
                row = {}
                for case in CASE_ORDER:
                    y_lo, y_hi = Ytab[case][f"V_d={V:g}"][f"eta_b={eb}"]
                    row[case] = {"status": classify(C["lo"], C["hi"], C["lo_open"], y_lo, y_hi, et_lo, et_hi),
                                 "eta_t_min_range": [g6(C["lo"] / y_hi), g6(C["hi"] / y_lo) if C["hi"] is not None else None]}
                slices[f"V_d={V:g}|eta_b={eb}"] = row
        cm = u["C_src_if_missing_factors_equal_1"]
        cond_case = {case: classify(cm[0], cm[1], False, box[case][0], box[case][1], et_lo, et_hi) for case in CASE_ORDER}
        cond_slices = {}
        for V in V_D_SLICES:
            for eb in ETA_B:
                cond_slices[f"V_d={V:g}|eta_b={eb}"] = {
                    case: classify(cm[0], cm[1], False, *Ytab[case][f"V_d={V:g}"][f"eta_b={eb}"], et_lo, et_hi)
                    for case in CASE_ORDER}
        u["eta_t"] = {"range": [et_lo, et_hi], "range_class": PROPOSED, "air_value": "TBD (interstage_v1 refuses air)",
                      "basis": "lane 18 interstage_v1: upper bound 1 (source-free duct, strong-B no-radial-loss limit, "
                               "capture 1); lower end 0.1 = analysis span, not a physical bound (top-level "
                               "eta_transport)"}
        u["conversion_chain"].append({
            "step": "A of source-exit ions -> A of ions delivered into the Hall channel (divide by eta_t, ion-current "
                    "basis)", "status": "missing (no measured or model-derived air value; PROPOSED range)",
            "factor": [g6(1.0 / et_hi), g6(1.0 / et_lo)], "range_eta": [et_lo, et_hi],
            "missing_quantity": "eta_t of the interstage on air (lane 18 inputs: dissociative-recombination rates valid "
                                "at the interstage T_e, junction ion capture, magnetized wall flux, source exit state)"})
        u["C_del_bus_W_per_delivered_A"] = {
            "lo": g6(C["lo"] / et_hi), "hi": g6(C["hi"] / et_lo) if C["hi"] is not None else None,
            "lo_open": C["lo_open"],
            "basis": "C_del = C_src / eta_t over the eta_t range; compared with Y (payable bus W per delivered A)"}
        u["placement"] = {
            "status": pl, "stated_case": stated, "per_case_over_declared_box": per_case,
            "eta_t_min_over_box": {"most_favourable": g6(C["lo"] / Y_max_box) if C["lo"] > 0 else 0.0,
                                   "least_favourable_add_only": g6(C["hi"] / Y_min_box) if C["hi"] is not None else None},
            "per_slice": slices,
            "evidence_class": "model-derived (overlay_rf_v1 on breakeven_v1; conditional on A1-A8 and every chain "
                              "condition)"}
        u["conditional_placement_if_missing_factors_equal_1"] = {
            "C_src_bus_W_per_A": cm, "per_case_over_declared_box": cond_case, "per_slice": cond_slices,
            "note": "NOT the placement: shows where the entry would sit if every missing conversion were exactly 1 "
                    "(ion basis transfers 1:1; antenna coupling 1). It is not a bound."}
        u["in_payable_region"] = {
            "intersects_outer_region": bool(C["lo"] <= et_hi * Y_max_box),
            "inside_inner_region": bool(C["hi"] is not None and C["hi"] <= et_lo * Y_min_box),
            "conditional_inside_outer_at_eta_t_1": bool(cm[1] <= et_hi * Y_max_box),
            "conditional_inside_inner_at_eta_t_1": bool(cm[1] <= et_hi * Y_min_box)}
        thr_above = (C["lo"] / Y_max_box) if C["lo"] > 0 else None
        thr_below = (C["hi"] / Y_min_box) if C["hi"] is not None else None
        u["decisive_measurements"] = {
            "eta_t_below_which_CLEARLY_ABOVE": g6(thr_above) if thr_above is not None else None,
            "eta_t_at_or_above_which_CLEARLY_BELOW_add_only": g6(thr_below) if thr_below is not None else None,
            "eta_t_alone_can_reach_CLEARLY_BELOW": bool(thr_below is not None and thr_below <= 1.0),
            "single_measurements": decisive_text(u),
        }
    placed_ids = sorted({i for u in units for i in u["matrix_ids"]})
    npl = []
    for eid, why, missing in NOT_PLACEABLE:
        npl.append({"id": eid, "status": "NOT_PLACEABLE", "reason": why, "missing_quantity": missing,
                    "entry": matrix_entry_summary(M[eid]),
                    "single_measurement": ("bus W (RF-generator DC input) and ion current leaving the RF stage on "
                                           "air/N2 at the ICD inlet state, same set point; this would give C_src "
                                           "directly" if eid != "RF-SITA19-02" else "none within the RF lane")})
    cost_topics = ("ion_production_cost", "ionization_fraction", "performance_context")
    topic_ids = sorted(e["id"] for e in rfm["entries"] if e["topic"] in cost_topics)
    covered = set(placed_ids) | {x["id"] for x in npl}
    missing_cov = [i for i in topic_ids if i not in covered]
    checks["every_cost_topic_entry_placed_or_not_placeable"] = {"uncovered": missing_cov, "pass": not missing_cov}
    other = sorted({e["topic"] for e in rfm["entries"] if e["topic"] not in cost_topics})
    chain_role = {"rf_generator_efficiency": "conversion-chain evidence (bus -> coil feed), via electrical_closure",
                  "power_coupling": "conversion-chain evidence (coil feed -> absorbed); no air value applicable",
                  "magnetic_field": "fixed rf_source load evidence: no accessed magnet power on air "
                                    "(RF_SOURCE_EVIDENCE.md section 4 item 5)",
                  "operating_envelope": "set-point definitions / regime context",
                  "pressure_mode_limits": "sustainment regime context (not a cost)",
                  "plasma_state": "regime / species-mix context",
                  "thermal_load": "thermal context (milestone C)", "material_interaction": "life context (milestone C)",
                  "hardware_mass": "mass context (milestone C)", "architecture_heritage": "heritage context"}
    other_topics = [{"topic": t, "ids": sorted(e["id"] for e in rfm["entries"] if e["topic"] == t),
                     "role_in_overlay": chain_role.get(t, "context")} for t in other]

    # consistency of place_evidence statuses with the Y band (samples)
    samp = []
    for C_src, et, case, V, eb in ((300.0, 0.5, "add_only", 300.0, 0.7), (600.0, 0.9, "optimistic_bound", 450.0, 0.5),
                                   (200.0, 1.0, "add_only", 150.0, 0.9)):
        r = G.ref(V, 0.6, eb, 0.9, ppu_hi)
        rs = G.resp(case, r)
        res = b.place_evidence(r, rs, 0.0, b.Evidenced(C_src, "W/A", "assumed", "overlay self-check"),
                               b.Evidenced(et, "1", "assumed", "overlay self-check"), 64)
        y = b.marginal_breakeven_delivered_cost(r, rs)
        mine = C_src / et <= y
        theirs = res["status"] != "CANNOT_BREAK_EVEN_IN_MODEL_FAMILY"
        samp.append({"C_src": C_src, "eta_t": et, "case": case, "V_d": V, "eta_b": eb, "status": res["status"],
                     "pass": mine == theirs})
    checks["Y_band_consistent_with_place_evidence"] = {"samples": samp, "pass": all(s["pass"] for s in samp)}

    failed = [k for k, v in checks.items() if not v["pass"]]
    if failed:
        raise OverlaySelfCheckError(f"self-checks failed: {failed}")
    for v in checks.values():
        if "max_abs_diff" in v:
            v["max_abs_diff"] = float(f"{v['max_abs_diff']:.3g}")

    any_outer = [u["unit_id"] for u in units if u["in_payable_region"]["intersects_outer_region"]]
    any_inner = [u["unit_id"] for u in units if u["in_payable_region"]["inside_inner_region"]]
    placements_count = {p: sum(1 for u in units if u["placement"]["status"] == p) for p in PLACEMENTS}
    placements_count["NOT_PLACEABLE"] = len(npl)

    out = {
        "overlay_id": "fo_rf_breakeven_overlay", "overlay_version": OVERLAY_VERSION, "trigger": "T_RF_OVERLAY",
        "prepared": PREPARED, "architecture": ARCH, "reference_architecture": REFERENCE_ARCH,
        "boundary_version": BOUNDARY_VERSION,
        "power_basis": "P_bus = all DC-bus power of the arm (every bus_power_boundary_v1 component: rf_source plus the "
                       "common components); never plasma-absorbed RF power, never source-only or discharge-only power. "
                       "Y and C_src are bus W per ampere; the Hall side is bus-referred through eta_ppu,d.",
        "status": "CONDITIONAL INEQUALITIES for milestone A. Not a prediction, not a ranking; names no winner and sets "
                  "nothing aside (only hard gates do that). No Hall transport closure, no screening candidate and no "
                  "withdrawn 0-D Hall number is used: the credible set is empty (gate 3 FAIL), so every Hall-side "
                  "quantity is a PROPOSED analysis value. The other pre-ionized arm is outside this overlay.",
        "milestone_support": {
            "supports": ["A"],
            "A": "conditional statement 'rf_hall is baseline only if it demonstrates X, Y, Z at the Vyovrinda Hall "
                 "reference point' with X, Y, Z computable now over PROPOSED ranges, and the placement of every "
                 "accessed RF evidence entry against them",
            "to_reach_B": "admitted Hall transport closure(s) for the Vyovrinda geometry (eta_u0, eta_b, eta_v, V_d per "
                          "credible-set member) replacing the PROPOSED box; measured delivered-ion bus cost of an RF "
                          "stage on air/N2 at the ICD inlet state; measured eta_t; measured response (alpha, chi, "
                          "eta_v,S, delivered mix); matching/antenna coupling on air",
            "to_reach_C": "mass (s_P, s_T, RF hardware), life (source mechanisms), thermal (thermal_life.py), start-up, "
                          "cathode, mission closure on the same boundary",
        },
        "inputs": {k: {"path": v["path"], "sha256": v["sha256"], "lane": v["lane"], "branch": v["branch"],
                       "commit": v["commit"]} for k, v in INPUTS.items()},
        "constants_used": {"E_CHARGE_C": K["E_CHARGE"], "AMU_kg": K["AMU"],
                           "masses_u": {"N2": K["M_N2"] / K["AMU"], "N": K["M_N2"] / K["AMU"] / 2.0,
                                        "O": K["M_O"] / K["AMU"], "O2": K["M_O2"] / K["AMU"]},
                           "source": "abep_sim/constants.py M_SPECIES (nominal masses, as used by the RF evidence lane's "
                                     "derive_rf_evidence.py); N = N2/2; electron mass neglected"},
        "cases": CASES,
        "cases_evidence_class": "assumed response parameters (breakeven_v1 named cases; A3-A5 of "
                                "BREAKEVEN_DERIVATION.md section 3); none is measured",
        "analysis_ranges": {
            "class": PROPOSED,
            "V_d_V": {"range": [V_D[0], V_D[-1]], "grid": V_D, "basis": "breakeven_v1 analysis range"},
            "eta_b": {"range": [ETA_B[0], ETA_B[-1]], "grid": ETA_B, "basis": "breakeven_v1 analysis range"},
            "eta_u0": {"range": [ETA_U0[0], ETA_U0[-1]], "grid": ETA_U0,
                       "basis": "breakeven_v1 analysis range; enters only through the utilization cap"},
            "eta_v": {"range": [ETA_V[0], ETA_V[-1]], "grid": ETA_V,
                      "basis": "breakeven_v1 analysis range; enters only the optimistic_bound case"},
            "eta_ppu_discharge": {"range": [g6(ppu_lo), g6(ppu_hi)], "class": "evidence range (digitized, level 3), "
                                  "applicability-limited", "evidence": ppu},
            "eta_t": {"range": [et_lo, et_hi], "grid": ETA_T, "class": PROPOSED},
            "omega": {"grid": OMEGA, "definition": "total bus overhead O / Hall-only discharge bus power P_d,bus0"},
            "omega_f": {"grid": OMEGA_F, "definition": "fixed (non-ion-scaling) overhead / P_d,bus0: common-component "
                        "deltas, generator standby, RF magnet if any; all TBD under v1"},
            "c": {"grid": C_NORM, "definition": "C_del / Pi_H: delivered-ion bus cost in units of the Hall price"},
            "C_src_grid_W_per_A": C_SRC_GRID,
            "gamma_div": {"value": GAMMA_REF, "note": "enters no break-even quantity"},
            "species": "equal delivered and Hall-born mix (A8); per-ampere results are species-independent at equal "
                       "mix. A heavier delivered ion into a lighter Hall beam raises Y (BREAKEVEN_DERIVATION.md 6.4)",
        },
        "rf_source_chain_evidence": gen,
        "electrical_closure_rules": elec_rules,
        "eta_transport": eta_t,
        "breakeven_condition": {
            "statement": "At a Hall reference point h (V_d, eta_b, eta_u0, eta_v, eta_ppu,d, mdot; analysis values) "
                         "and response case k, rf_hall can become preferable to hall_only ONLY IF (power side; "
                         "necessary, not sufficient) it delivers a relative utilization gain x = delta_eta_u/eta_u0 of "
                         "at least X, at no more than Y bus W per delivered ampere, through an interstage whose "
                         "transport efficiency is at least Z.",
            "X": "X = x*(omega) from R(x)(1 - omega) = 1, omega = (P_bus[rf_source] + sum of common-component "
                 "deltas)/P_d,bus0; add_only: X = omega/(1 - omega). Coupled form: for a delivered cost c*Pi_H and "
                 "fixed overhead omega_f the payable x lie in [x_lo, x_hi] (table coupled_X_interval); with "
                 "omega_f = 0, x_lo = 0 and the only lower limit on the gain is that it be positive.",
            "Y": "Y = c_k(eta_b, eta_v) * Pi_H, Pi_H = V_d/(eta_b eta_ppu,d); c_add = 1, c_cost = 2 - eta_b, "
                 "c_opt = 2/sqrt(eta_v) - eta_b (no fixed overhead: supremum = marginal limit); fixed overhead lowers "
                 "it to c_sup(omega_f) * Pi_H (table Y_sup_fixed_overhead_normalized)",
            "Z": "Z = C_src / Y, C_src = bus W per A of ions leaving the RF stage; eta_t < Z cannot pay at h under k",
            "same_inequality": "X, Y and Z are three views of one inequality R(x)(1 - omega_f - c x) >= 1 with "
                               "c = C_src/(eta_t Pi_H) and x = delta_s/eta_u0 <= (1 - eta_u0)/eta_u0",
            "source": "abep_sim/breakeven.py breakeven_v1 (required_utilization_gain, marginal/supremum_breakeven_"
                      "delivered_cost, place_evidence); BREAKEVEN_DERIVATION.md sections 4-6",
            "assumptions": "A1-A8 of BREAKEVEN_DERIVATION.md section 3 (all assumed); Hall-side values PROPOSED",
        },
        "tables": {
            "c_norm_Y_over_Pi_H": c_norm,
            "Y_bus_W_per_delivered_A": {"index_order": "case -> V_d -> eta_b -> [min, max] over eta_ppu,d evidence "
                                                       "range (and eta_v 0.7-1.0 for optimistic_bound)",
                                        "values": Ytab},
            "Y_box": {case: [g6(box[case][0]), g6(box[case][1])] for case in CASE_ORDER},
            "Y_sup_fixed_overhead_normalized": {"index_order": "variant -> eta_u0 -> [omega_f, c_sup]; "
                                                "c_sup <= 0 means no source cost pays", "values": fixed},
            "X_required_relative_gain": {"index_order": "variant -> [omega, x* = delta_eta_u*/eta_u0, eta_u0 values "
                                                        "for which x* exceeds the cap (1 - eta_u0)/eta_u0]",
                                         "values": Xtab},
            "coupled_X_interval": {"index_order": "variant -> omega_f -> [c, x_lo, x_hi] (uncapped; apply "
                                                  "x <= (1 - eta_u0)/eta_u0; null = no payable gain)",
                                   "caps": {f"eta_u0={u0}": g6((1.0 - u0) / u0) for u0 in ETA_U0},
                                   "values": coupled},
            "Z_min_eta_t": {"index_order": "case -> 'V_d|eta_b' -> [C_src W/A, eta_t_min at the most favourable, at "
                                           "the least favourable eta_ppu,d/eta_v]; > 1 = unreachable",
                            "values": Ztab},
        },
        "placement_rules": {
            "class": "PROPOSED definitions (not in the RFP; owner to confirm)",
            "C_src": "bus W per A of ions leaving the RF stage, after every SOURCED conversion; each MISSING "
                     "conversion is replaced by its physical bound (efficiency in (0, 1]; ion-basis factor in (0, 1]) "
                     "so [lo, hi] is a bound, not an estimate",
            "boundary": "C_src <= eta_t * Y(h, k)",
            "declared_box": "V_d, eta_b, eta_v as analysis_ranges; eta_ppu,d over its evidence range; omega_f = 0 "
                            "(most favourable; fixed overheads only lower Y)",
            "CLEARLY_ABOVE_BREAKEVEN": "lo > eta_t,max * Y_max(optimistic_bound): cannot pay under any declared case, "
                                       "at any declared Hall point, at any eta_t in range",
            "CLEARLY_BELOW": "hi <= eta_t,min * Y_min(k) for the stated case k: pays (for small delivered shares) at "
                             "every declared Hall point and every eta_t in range",
            "STRADDLES": "neither; the per-slice table and eta_t thresholds show where it can and cannot pay",
            "NOT_PLACEABLE": "no ion-current basis can be formed; the missing quantity is named",
            "per_slice": "the same rule at fixed (V_d, eta_b) over the eta_ppu,d range (and eta_v for optimistic_bound)",
        },
        "evidence_placements": units,
        "not_placeable": npl,
        "other_rf_matrix_topics": other_topics,
        "placement_counts": placements_count,
        "payable_region": {
            "definition": "R_k(h) = {(eta_t, C_src): C_src <= eta_t * Y_k(h)}; outer envelope = union over the "
                          "declared box and cases = {C_src <= eta_t * Y_max(optimistic_bound)}; inner envelope = "
                          "intersection = {C_src <= eta_t * Y_min(add_only)}",
            "Y_max_optimistic_W_per_A": g6(Y_max_box), "Y_min_add_only_W_per_A": g6(Y_min_box),
            "lines": region_lines,
            "evidence_intersecting_outer_region": any_outer,
            "evidence_inside_inner_region": any_inner,
            "answer": ((f"{len(any_inner)} of {len(units)} placeable units lie inside the inner region "
                        f"({', '.join(any_inner)})" if any_inner else
                        "No accessed RF evidence entry lies inside the inner region (where rf_hall would pay at every "
                        "declared Hall point, under add_only, at every eta_t in range)") + ". "
                       + (f"{len(any_outer)} of {len(units)} placeable units intersect the outer region (they could "
                          "pay somewhere in the declared box for a high enough eta_t)" if any_outer else
                          "None intersects the outer region") + ". No RF source has a measured eta_t, so no entry is "
                       "a located point in the (eta_t, C_src) plane: each is a C_src interval swept over the eta_t "
                       "range."),
        },
        "decisive_measurement_common": {
            "quantity": "delivered-ion bus cost C_del = P_bus[rf_source] / I_delivered, with I_delivered the ion "
                        "current entering the Hall channel from an RF stage + interstage on air/N2 at the ICD inlet "
                        "state (one measurement that combines C_src and eta_t)",
            "C_del_above_which_CLEARLY_ABOVE_W_per_A": g6(Y_max_box),
            "C_del_at_or_below_which_CLEARLY_BELOW_add_only_W_per_A": g6(Y_min_box),
            "in_between": "placement depends on the Hall reference point and response case: needs milestone-B "
                          "quantities (admitted closure; measured alpha, chi, eta_v,S)",
        },
        "milestone_A_statement": milestone_statement(Y_min_box, Y_max_box, placements_count, units, et_lo),
        "open_questions_for_owner": [
            "Accept the PROPOSED analysis box (V_d 150-450 V, eta_b 0.5-0.9, eta_v 0.7-1.0, eta_t 0.1-1) and the use of "
            "the electrical_closure discharge-supply evidence range for eta_ppu,d?",
            "Accept the robust placement definitions (CLEARLY_BELOW over the whole declared box and eta_t range)? With "
            "eta_t unmeasured down to 0.1 it cannot be met by any RF source cost above 0.1 * Y_min.",
            "bus_power_boundary_v1 has no RF magnet component: a B-assisted RF stage would book its magnet inside "
            "rf_source (fixed load). Confirm, or add a component in a v2 boundary.",
            "Is the RF generator fed directly from the propulsion DC bus (as in the NewOrbit source)? Otherwise a bus "
            "-> RFG converter efficiency enters every chain.",
        ] + [f"(electrical_closure) {q}" for q in elec_questions[:2]],
        "self_checks": checks,
        "provenance": {"generated_by": SCRIPT_REL,
                       "regenerate": f"python {SCRIPT_REL}  (check: --check)",
                       "breakeven_version": b.BREAKEVEN_VERSION, "interstage_model": eta_t["model"]},
    }
    return out


def decisive_text(u):
    if u["unit_id"].startswith("U-RF-NO25"):
        return ["per-set-point (P_RFG, I_beam) pairs from the source's Fig. 14 or data (narrows 206.7-1600 W/A)",
                "ion extraction fraction I_beam/I_exit of that source (effective screen-grid ion transparency), which "
                "turns the extracted-beam cost into a source-exit cost",
                "eta_t of the Vyovrinda interstage (lane 18 inputs: DR rates valid at the interstage T_e, junction "
                "capture, magnetized wall flux)",
                "or, decisive by itself: C_del measured on a gridless RF stage + interstage (decisive_measurement_common)"]
    split = {"N2": "N2+/N+", "O": "O+ and any O2+ from wall recombination", "O2": "O2+/O+"}[u["gas"]]
    return ["antenna/plasma coupling eta_ant and matching/cable loss on air at the operating point (the only step "
            "that leaves C_src unbounded above)",
            f"beam species/charge split of the source exit ({split}, multiply charged fraction)",
            "a measurement replacing the model (level 6): bus W and exit ion current of an RF stage on the same gas",
            "eta_t of the Vyovrinda interstage"]


def slice_summary(units):
    """(unit, slice, case) combinations that sit above break-even even at eta_t = 1 (bounded lower C_src)."""
    rows = []
    for u in units:
        for sl, per in u["placement"]["per_slice"].items():
            for case in CASE_ORDER:
                if per[case]["status"] == "ABOVE":
                    rows.append({"unit_id": u["unit_id"], "slice": sl, "case": case})
    vds = sorted({float(r["slice"].split("|")[0].split("=")[1]) for r in rows})
    return rows, vds


def milestone_statement(Y_min_box, Y_max_box, counts, units, et_lo):
    rows, vds = slice_summary(units)
    n_low = sum(1 for u in units if u["C_src_bus_W_per_A"]["hi"] is not None
                and u["C_src_bus_W_per_A"]["hi"] <= et_lo * Y_min_box)
    s_units = sorted({r["unit_id"] for r in rows})
    slice_text = (f"In the per-slice tables {len(s_units)} placeable units sit above break-even even at eta_t = 1 in "
                  f"{len(rows)} (unit, V_d, eta_b, case) combinations, all at V_d = {', '.join(f'{v:g}' for v in vds)} V "
                  "(the lowest Hall price per beam ampere Pi_H = V_d/(eta_b eta_ppu,d) of the box). Those rest on the "
                  "lower bound of C_src, which is conditional on singly charged beams and on level-6 model points; "
                  "they are slice statements, not placements." if rows else
                  "No placeable unit sits above break-even at eta_t = 1 in any per-slice table.")
    return {
        "supports": "A",
        "can_be_concluded_now": [
            "The power-side break-even of rf_hall against hall_only on bus_power_boundary_v1 is the closed-form "
            "inequality set X, Y, Z of breakeven_condition; it is computable at any Hall reference point without an "
            "absolute Hall prediction.",
            f"Over the declared box the payable bus cost per delivered ampere lies between {Y_min_box:.4g} W/A "
            f"(add_only, least favourable point) and {Y_max_box:.4g} W/A (optimistic_bound, most favourable point).",
            f"No accessed RF evidence entry is CLEARLY_ABOVE_BREAKEVEN ({counts['CLEARLY_ABOVE_BREAKEVEN']}) or "
            f"CLEARLY_BELOW ({counts['CLEARLY_BELOW']}); {counts['STRADDLES']} placeable units straddle and "
            f"{counts['NOT_PLACEABLE']} entries are NOT_PLACEABLE. The power break-even therefore gives no basis to "
            "set rf_hall aside and no basis to expect it to pay.",
            f"With eta_t known only to lie in [{et_lo:g}, 1], CLEARLY_BELOW needs C_src <= {et_lo:g} * Y_min = "
            f"{et_lo * Y_min_box:.4g} bus W/A under add_only; {n_low} of {len(units)} placeable units have an upper "
            "bound of C_src at or below it. eta_t is the decisive unknown on the transport side, the antenna/matching coupling on "
            "air on the source side.",
            slice_text,
        ],
        "conditions_for_rf_hall_as_baseline": [
            "C1 (Y): demonstrated delivered-ion bus cost C_del = P_bus[rf_source]/I_delivered <= Y(h, k) at the "
            "Vyovrinda Hall reference point h under the demonstrated response case k, reduced for fixed overheads "
            "(Y_sup_fixed_overhead_normalized)",
            "C2 (Z): demonstrated eta_t >= C_src/Y(h, k) on the ion-current basis",
            "C3 (X): demonstrated relative utilization gain x >= X(omega) at the operated rf_source bus power, "
            "within the cap x <= (1 - eta_u0)/eta_u0 and inside the coupled interval [x_lo, x_hi]",
            "C4: the response (alpha, chi, eta_v,S, delivered mix) demonstrated in a coupled RF + Hall test. add_only "
            "is the least favourable of the three declared cases, but it is not a bound: delivered ions that displace "
            "Hall-born ions (alpha < 1) lower Y further (alpha = 0, chi = 0 gives Y = 0)",
            "C5: a complete bus_power_boundary_v1 ledger for both arms at the same operating mode (all common-"
            "component deltas explicit)",
            "C6: mass, life, thermal and start-up conditions (milestone C) are additional and not assessed here",
        ],
        "slices_above_at_eta_t_1": rows,
        "not_concluded": "no winner, no ranking, no statement that rf_hall is or is not worth its power, no "
                         "comparison with the other pre-ionized arm",
    }


# ---------------------------------------------------------------------------------------------------- markdown block
def vlabel(k):
    """Markdown-safe label of a variant key such as 'cost_offset|eta_b=0.7'."""
    parts = k.split("|")
    if len(parts) == 1:
        return parts[0]
    return parts[0] + " (" + ", ".join(p.replace("eta_b=", "η_b ").replace("eta_v=", "η_v ") for p in parts[1:]) + ")"


def md_cell(s):
    return str(s).replace("|", "\\|").replace("\n", " ")


def fmt_iv(lo, hi, lo_open=False):
    return f"{'(' if lo_open else '['}{fmt(lo)}, {fmt(hi)}{']' if hi is not None else ')'}"


def md_block(o):
    t = o["tables"]
    ms = o["milestone_A_statement"]
    L = [MD_BEGIN, ""]
    L.append("Everything between these markers is written by `build_overlay_rf.py` from `overlay_rf_v1.json`. Hall-side "
             "values are PROPOSED analysis values, not predictions.")
    L.append("")
    L.append("### G0. Milestone-A statement (conditional)")
    L.append("")
    L.append(f"Supports milestone **{ms['supports']}**. What can be concluded now:")
    L.append("")
    for x in ms["can_be_concluded_now"]:
        L.append(f"* {x}")
    L.append("")
    L.append("rf_hall can be the baseline only if **all** of the following are demonstrated:")
    L.append("")
    for x in ms["conditions_for_rf_hall_as_baseline"]:
        L.append(f"* {x}")
    L.append("")
    L.append(f"Not concluded: {ms['not_concluded']}.")
    L.append("")
    L.append(f"To reach B: {o['milestone_support']['to_reach_B']}.")
    L.append("")
    L.append(f"To reach C: {o['milestone_support']['to_reach_C']}.")
    L.append("")

    L.append("### G1. Y: largest payable bus W per delivered ampere (no fixed overhead)")
    L.append("")
    L.append("Min–max over η_ppu,d " + f"{o['analysis_ranges']['eta_ppu_discharge']['range']}"
             + " (and η_v 0.7–1.0 for optimistic_bound).")
    L.append("")
    L.append("| V_d [V] | η_b | add_only | cost_offset | optimistic_bound |")
    L.append("|---|---|---|---|---|")
    for V in V_D:
        for eb in ETA_B:
            cells = []
            for c in CASE_ORDER:
                y = t["Y_bus_W_per_delivered_A"]["values"][c][f"V_d={V:g}"][f"eta_b={eb}"]
                cells.append(f"{fmt(y[0])}–{fmt(y[1])}")
            L.append(f"| {V:g} | {eb} | " + " | ".join(cells) + " |")
    yb = t["Y_box"]
    L.append("")
    L.append("Declared-box extremes: " + "; ".join(f"{c} {fmt(yb[c][0])}–{fmt(yb[c][1])} W/A" for c in CASE_ORDER)
             + ".")
    L.append("")

    L.append("### G2. X: required relative utilization gain x* = Δη_u*/η_u0 against the total overhead fraction ω")
    L.append("")
    L.append("ω = (P_bus[rf_source] + Σ common-component deltas)/P_d,bus0. With α = 1 the delivered-ion share equals "
             "the gain: δ_s* = Δη_u* = x*·η_u0.")
    L.append("")
    keys = ["add_only", "cost_offset|eta_b=0.5", "cost_offset|eta_b=0.7", "cost_offset|eta_b=0.9",
            "optimistic_bound|eta_b=0.7|eta_v=0.7", "optimistic_bound|eta_b=0.7|eta_v=1.0"]
    L.append("| ω | " + " | ".join(vlabel(k) for k in keys) + " |")
    L.append("|---|" + "---|" * len(keys))
    for i, w in enumerate(OMEGA):
        if round(w * 100) % 10 != 0 and w not in (0.05, 0.25, 0.75, 0.85):
            continue
        cells = []
        for k in keys:
            row = t["X_required_relative_gain"]["values"][k][i]
            s = fmt(row[1])
            if row[2]:
                s += " (cap: η_u0 " + ", ".join(str(x) for x in row[2]) + ")"
            cells.append(s)
        L.append(f"| {w:g} | " + " | ".join(cells) + " |")
    L.append("")
    L.append("\"cap: η_u0 …\" = x* exceeds (1 − η_u0)/η_u0 for those η_u0: no break-even there. Full grid in the JSON "
             "(`tables.X_required_relative_gain`).")
    L.append("")

    L.append("### G3. Coupled X–Y: payable relative-gain interval [x_lo, x_hi] for a delivered cost c·Π_H")
    L.append("")
    L.append("Uncapped; apply x ≤ (1 − η_u0)/η_u0 = " + ", ".join(
        f"{fmt(v)} ({k})" for k, v in t["coupled_X_interval"]["caps"].items()) + ". '—' = no payable gain.")
    L.append("")
    ck = ["add_only", "cost_offset|eta_b=0.7", "optimistic_bound|eta_b=0.7|eta_v=0.9"]
    L.append("| c = C_del/Π_H | ω_f | " + " | ".join(vlabel(k) for k in ck) + " |")
    L.append("|---|---|" + "---|" * len(ck))
    for wf in (0.0, 0.05):
        for c in (0.2, 0.5, 0.8, 1.0, 1.2, 1.5):
            ci = C_NORM.index(c)
            cells = []
            for k in ck:
                row = t["coupled_X_interval"]["values"][k][f"omega_f={wf}"][ci]
                cells.append("—" if row[1] is None else f"{fmt(row[1])}–{fmt(row[2])}")
            L.append(f"| {c} | {wf} | " + " | ".join(cells) + " |")
    L.append("")

    L.append("### G4. Fixed overhead lowers Y: c_sup(ω_f) = Y_sup/Π_H (η_u0 = 0.6)")
    L.append("")
    fk = ["add_only", "cost_offset|eta_b=0.7", "optimistic_bound|eta_b=0.7|eta_v=0.9"]
    L.append("| ω_f | " + " | ".join(vlabel(k) for k in fk) + " |")
    L.append("|---|" + "---|" * len(fk))
    for i, wf in enumerate(OMEGA_F):
        cells = [fmt(t["Y_sup_fixed_overhead_normalized"]["values"][k]["eta_u0=0.6"][i][1]) for k in fk]
        L.append(f"| {wf:g} | " + " | ".join(cells) + " |")
    L.append("")
    L.append("A value ≤ 0 means no source cost pays. ω_f collects the non-ion-scaling loads (common-component deltas, "
             "generator standby, any RF magnet booked in rf_source); all are TBD.")
    L.append("")

    L.append("### G5. Z and the payable region: largest payable source cost C_src,max = η_t·Y [bus W per A of "
             "source-exit ions]")
    L.append("")
    L.append("| η_t | outer envelope (some declared point, optimistic_bound) | inner envelope (every declared point, "
             "add_only) | add_only @300 V, η_b 0.7 | cost_offset @300 V, η_b 0.7 | optimistic_bound @300 V, η_b 0.7 |")
    L.append("|---|---|---|---|---|---|")
    for row in o["payable_region"]["lines"]:
        cells = [fmt(row["outer_envelope_C_src_max"]), fmt(row["inner_envelope_C_src_max"])]
        for c in CASE_ORDER:
            v = row[f"{c}@V_d=300,eta_b=0.7"]
            cells.append(f"{fmt(v[0])}–{fmt(v[1])}")
        L.append(f"| {row['eta_t']} | " + " | ".join(cells) + " |")
    L.append("")
    L.append("Z = C_src/Y: a source of cost C_src needs η_t ≥ C_src/Y (JSON `tables.Z_min_eta_t`). "
             f"{o['payable_region']['answer']}")
    L.append("")

    L.append("### G6. Evidence placements")
    L.append("")
    L.append("| unit | entries | reported | power reference | C_src bound [bus W/A exit ions] | C_del bound [bus W/A "
             "delivered] | placement | η_t below which CLEARLY_ABOVE | η_t for CLEARLY_BELOW (add_only) |")
    L.append("|---|---|---|---|---|---|---|---|---|")
    for u in o["evidence_placements"]:
        rep = u["reported"]
        rv = rep["value"]
        rs = (f"{fmt(rv[0])}–{fmt(rv[1])}" if isinstance(rv, list) else fmt(rv)) + " " + rep["units"]
        C, D = u["C_src_bus_W_per_A"], u["C_del_bus_W_per_delivered_A"]
        dm = u["decisive_measurements"]
        below = dm["eta_t_at_or_above_which_CLEARLY_BELOW_add_only"]
        if below is None:
            bt = "none (C_src unbounded above)"
        else:
            bt = fmt(below) + (" (> 1: unreachable)" if below > 1 else "")
        above = dm["eta_t_below_which_CLEARLY_ABOVE"]
        at = "none (C_src lower bound → 0)" if above is None else fmt(above)
        L.append(f"| {u['unit_id']} | {', '.join(u['matrix_ids'])} | {rs} | {u['power_reference']} | "
                 f"{fmt_iv(C['lo'], C['hi'], C['lo_open'])} | {fmt_iv(D['lo'], D['hi'], D['lo_open'])} | "
                 f"**{u['placement']['status']}** | {at} | {bt} |")
    L.append("")
    L.append("Evidence class of every placement: model-derived (this overlay on breakeven_v1), conditional on A1–A8 of "
             "BREAKEVEN_DERIVATION.md §3 and on every chain condition below.")
    L.append("")

    L.append("### G7. Conversion chains to bus W per delivered ampere")
    L.append("")
    L.append("Units with an identical chain share one table; the unit-specific numbers are in G6 and in the JSON.")
    L.append("")
    groups = {}
    for u in o["evidence_placements"]:
        key = json.dumps([u["power_reference"], u["power_reference_note"], u["conversion_chain"],
                          u["C_src_bus_W_per_A"].get("conditional_on")], sort_keys=True, ensure_ascii=False)
        groups.setdefault(key, []).append(u)
    for us in groups.values():
        u = us[0]
        gases = sorted({x["gas"] for x in us})
        L.append(f"**{', '.join(x['unit_id'] for x in us)}** (gas {'; '.join(gases)}; power reference "
                 f"`{u['power_reference']}`: {md_cell(u['power_reference_note'])})")
        L.append("")
        L.append("| step | status | factor | direction, formula, missing quantity or note |")
        L.append("|---|---|---|---|")
        for st in u["conversion_chain"]:
            fac = st.get("factor")
            fs = "—" if fac is None else f"{fmt(fac[0])}–{fmt(fac[1])}"
            note = "; ".join(st[k] for k in ("direction", "formula", "factor_note", "missing_quantity", "note")
                             if st.get(k))
            L.append(f"| {md_cell(st['step'])} | {md_cell(st['status'])} | {fs} | {md_cell(note)} |")
        cond = u["C_src_bus_W_per_A"].get("conditional_on")
        if cond:
            L.append("")
            L.append("C_src bound conditional on: " + "; ".join(cond) + ".")
        L.append("")

    L.append("### G8. Per-slice placement (A = cannot pay even at η_t = 1, S = straddles, B = pays everywhere in the "
             "slice)")
    L.append("")
    sl = [f"V_d={V:g}|eta_b={eb}" for V in V_D_SLICES for eb in ETA_B]
    L.append("| unit | case | " + " | ".join(s.replace("V_d=", "").replace("|eta_b=", " V, η_b ") for s in sl) + " |")
    L.append("|---|---|" + "---|" * len(sl))
    code = {"ABOVE": "A", "STRADDLES": "S", "BELOW": "B"}
    for u in o["evidence_placements"]:
        for c in CASE_ORDER:
            L.append(f"| {u['unit_id']} | {c} | " + " | ".join(code[u['placement']['per_slice'][s][c]['status']]
                                                          for s in sl) + " |")
    L.append("")

    L.append("### G9. NOT_PLACEABLE entries")
    L.append("")
    L.append("| entry | evidence class / level | why | missing quantity |")
    L.append("|---|---|---|---|")
    for x in o["not_placeable"]:
        e = x["entry"]
        ecl = e["evidence_class"] if e["evidence_class"] is not None else "TBD (not measured)"
        L.append(f"| {x['id']} | {ecl} / {e['evidence_level']} | {md_cell(x['reason'])} | "
                 f"{md_cell(x['missing_quantity'])} |")
    L.append("")

    L.append("### G10. Single measurements that would give a definite placement")
    L.append("")
    dc = o["decisive_measurement_common"]
    L.append(f"* **Common, decisive by itself:** {dc['quantity']}. C_del > {fmt(dc['C_del_above_which_CLEARLY_ABOVE_W_per_A'])}"
             f" W/A → CLEARLY_ABOVE_BREAKEVEN; C_del ≤ {fmt(dc['C_del_at_or_below_which_CLEARLY_BELOW_add_only_W_per_A'])}"
             f" W/A → CLEARLY_BELOW (add_only); in between: {dc['in_between']}.")
    for u in o["evidence_placements"]:
        L.append(f"* **{u['unit_id']}** ({u['placement']['status']}): "
                 + "; ".join(u["decisive_measurements"]["single_measurements"]) + ".")
    ids = ", ".join(x["id"] for x in o["not_placeable"] if x["id"] != "RF-SITA19-02")
    L.append(f"* **NOT_PLACEABLE ({ids}):** bus W (RF-generator DC input) and the ion current leaving the RF stage on "
             "air/N₂ at the ICD inlet state, at the same set point. RF-SITA19-02 is outside the RF evidence scope.")
    L.append("")

    et = o["eta_transport"]
    L.append("### G11. Interstage transport efficiency η_t (lane 18)")
    L.append("")
    L.append(f"* Model: `{et['model']}`. Range used: {et['range'][0]}–{et['range'][1]} ({et['range_class']}).")
    L.append(f"* Air value: {et['air_value']}.")
    L.append(f"* Upper end: {et['upper_bound_basis']}.")
    L.append(f"* Lower end: {et['lower_bound_basis']}.")
    L.append(f"* Ion basis: {et['ion_basis']}.")
    L.append("")
    L.append("### G12. Open questions for the owner")
    L.append("")
    for i, q in enumerate(o["open_questions_for_owner"], 1):
        L.append(f"{i}. {q}")
    L.append("")
    L.append("Placement counts: " + ", ".join(f"{k} {v}" for k, v in o["placement_counts"].items()) + ". Self-checks: "
             + ", ".join(f"{k} {'pass' if v['pass'] else 'FAIL'}" for k, v in o["self_checks"].items()) + ".")
    L.append("")
    L.append(MD_END)
    return "\n".join(L)


def render(o):
    return json.dumps(o, indent=1, ensure_ascii=False) + "\n"


def merged_md(block):
    with open(OUT_MD, encoding="utf-8") as f:
        text = f.read()
    i, j = text.find(MD_BEGIN), text.find(MD_END)
    if i < 0 or j < 0 or j < i:
        raise OverlaySelfCheckError(f"{OUT_MD}: GENERATED markers not found")
    return text[:i] + block + text[j + len(MD_END):]


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="rebuild in memory and byte-compare with the committed files")
    ap.add_argument("--input-root", action="append", default=[], help="extra checkout root to search for inputs")
    a = ap.parse_args(argv)
    o = build(a.input_root)
    js = render(o)
    md = merged_md(md_block(o))
    if a.check:
        bad = []
        with open(OUT_JSON, encoding="utf-8") as f:
            if f.read() != js:
                bad.append(os.path.basename(OUT_JSON))
        with open(OUT_MD, encoding="utf-8") as f:
            if f.read() != md:
                bad.append(os.path.basename(OUT_MD) + " (generated block)")
        if bad:
            print("MISMATCH: " + ", ".join(bad) + " differ from a fresh build")
            return 1
        print("OK: overlay_rf_v1.json and the generated block of RF_BREAKEVEN_OVERLAY.md reproduce")
        return 0
    with open(OUT_JSON, "w", encoding="utf-8") as f:
        f.write(js)
    with open(OUT_MD, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"wrote {os.path.relpath(OUT_JSON, ROOT)} and the generated block of {os.path.relpath(OUT_MD, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
