"""Authoritative input manifests (A9.22 layer separation; A9.23 simulation architecture): loaders for ``config/`` and
the ``SimulationConfiguration`` record.

Owner directives 2026-10-03 (docs/decisions/OD_2026_10_03_A9_22_*, OD_2026_10_03_A9_23_*): requirements / provenance
-> frozen engineering constraints; architecture + constraints + design states + physics -> raw results; raw results +
constraints -> assessment. The physics never reads or interprets the RFP / RVM / clause ids; it consumes versioned,
sha256-pinned configuration files. This module is that interface:

  config/MANIFEST.json                                  every config file + sha256 (root of trust for this directory)
  config/SOURCES_OF_TRUTH.json                          one authoritative artefact per role (A9.23)
  config/architecture/hall_icp_neutralizer_v1.json      A9.19 / A9.20 / A9.15 flight architecture (design layer)
  config/constraints/engineering_constraints_v1.json    frozen engineering constraints (values; provenance labels only)
  config/requirements/rfp_constraints_v1.json           requirements snapshot (PROVENANCE layer; read only by the
                                                        assessment loaders below, never by physics / design seams)
  config/mission/mission_scenario_v1.json               operating-scenario choices + references to the constraints
  config/environment/design_state_set_ref_v1.json       REFERENCE to the frozen design-state set v2 (never a copy)
  config/hardware/hardware_bounds_v1.json               INDEX of hardware-limit sources (path + sha256 + locator)
  config/model_set/physics_model_set_v1.json            physics module / data hashes and version labels

Every loader fails closed: a file missing from the manifest, a file whose sha256 differs from the manifest, or a
referenced file whose sha256 differs from the pin raises ``ConfigurationError`` (no fallback, CLAUDE.md rule 3).
The files are generated by ``scripts/config/build_config.py`` from the existing sources. ``abep_sim.constants.RFP``
keeps its recorded values (immutable; its mission_hours = 26,000 h is HISTORICAL_CONSTANT_NOT_CONSUMED since the
A9.22 G1 governed migration). The seams ``abep_sim.operating_inputs`` (physics) and
``abep_sim.design.engineering_constraints`` (design) read their values through ``load_operating_inputs`` and
``load_engineering_constraints`` below; both read config/constraints (+ config/mission), never config/requirements.

``physics_configuration()`` is the raw-physics entry point: it never opens the requirements snapshot.
The config root is ``<repository>/config``; ``ABEP_CONFIG_ROOT`` overrides it (used when the package is installed
outside a checkout). There is no packaged fallback copy.
"""
from __future__ import annotations

import hashlib
import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

REPO_ROOT = Path(__file__).resolve().parents[1]
CONFIG_ENV = "ABEP_CONFIG_ROOT"

MANIFEST_REL = "MANIFEST.json"
ARCHITECTURE_REL = "architecture/hall_icp_neutralizer_v1.json"
REQUIREMENTS_REL = "requirements/rfp_constraints_v1.json"
CONSTRAINTS_REL = "constraints/engineering_constraints_v1.json"
MISSION_REL = "mission/mission_scenario_v1.json"
DESIGN_STATE_REF_REL = "environment/design_state_set_ref_v1.json"
HARDWARE_BOUNDS_REL = "hardware/hardware_bounds_v1.json"
MODEL_SET_REL = "model_set/physics_model_set_v1.json"
SOURCES_OF_TRUTH_REL = "SOURCES_OF_TRUTH.json"

# constraint ids of config/constraints/engineering_constraints_v1.json the loaders require
CONSTRAINT_IDS = ("altitude_band_km", "thrust_sustained_min_mN", "thrust_capability_mN", "p_bus_max_W",
                  "wet_mass_max_kg", "mission_life_h", "firing_life_h", "propellant_capability",
                  "intake_drag_generation_limit_mN", "ic_total_min", "ic_subsystem_min", "hall_preferred")

# RFPConstraints fields carried by the snapshot's compatibility block (abep_sim.constants.RFP; same names, same order)
RFP_COMPAT_FIELDS = ("thrust_min_mN", "thrust_max_mN", "power_max_W", "mass_max_kg", "alt_min_km", "alt_max_km",
                     "ignition_hours", "mission_hours", "ic_total_min", "ic_subsystem_min", "hall_preferred")
_RFP_FLOAT_FIELDS = RFP_COMPAT_FIELDS[:-2]


class ConfigurationError(RuntimeError):
    """A configuration file is missing, unlisted, altered, or references an altered source (fail closed)."""


def config_root() -> Path:
    env = os.environ.get(CONFIG_ENV)
    return Path(env) if env else REPO_ROOT / "config"


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def load_manifest(root: Optional[Path] = None) -> dict:
    root = Path(root) if root is not None else config_root()
    p = root / MANIFEST_REL
    if not p.is_file():
        raise ConfigurationError(f"{p} missing: the configuration manifest is required (no fallback); build it with "
                                 "python scripts/config/build_config.py")
    m = json.loads(p.read_text(encoding="utf-8"))
    if m.get("schema") != "abep_config_manifest_v1" or not isinstance(m.get("files"), dict):
        raise ConfigurationError(f"{p} is not an abep_config_manifest_v1")
    return m


def load_verified(rel: str, root: Optional[Path] = None) -> dict:
    """Load ``config/<rel>`` after checking it is listed in MANIFEST.json with a matching sha256."""
    root = Path(root) if root is not None else config_root()
    files = load_manifest(root)["files"]
    if rel not in files:
        raise ConfigurationError(f"config/{rel} is not listed in config/MANIFEST.json")
    p = root / rel
    if not p.is_file():
        raise ConfigurationError(f"config/{rel} missing (listed in config/MANIFEST.json; no fallback)")
    got = _sha256_file(p)
    if got != files[rel]["sha256"]:
        raise ConfigurationError(f"config/{rel} sha256 {got} != MANIFEST {files[rel]['sha256']} (an edited "
                                 "configuration file is refused; regenerate with scripts/config/build_config.py)")
    return json.loads(p.read_text(encoding="utf-8"))


def _check_ref(path_rel: str, want: str, what: str) -> Path:
    p = REPO_ROOT / path_rel
    if not p.is_file():
        raise ConfigurationError(f"{what}: referenced file {path_rel} missing")
    got = _sha256_file(p)
    if got != want:
        raise ConfigurationError(f"{what}: referenced file {path_rel} sha256 {got} != pinned {want}")
    return p


# -------------------------------------------------------------------------------------------------------- loaders
def load_architecture(root: Optional[Path] = None) -> dict:
    d = load_verified(ARCHITECTURE_REL, root)
    if d.get("schema") != "abep_config_architecture_v1":
        raise ConfigurationError("architecture config: unexpected schema")
    return d


def load_requirements_snapshot(root: Optional[Path] = None) -> dict:
    d = load_verified(REQUIREMENTS_REL, root)
    if d.get("schema") != "abep_config_requirements_snapshot_v1":
        raise ConfigurationError("requirements snapshot: unexpected schema")
    if d.get("snapshot_status") not in ("FROZEN", "PROVISIONAL"):
        raise ConfigurationError(f"requirements snapshot: status {d.get('snapshot_status')!r} not FROZEN/PROVISIONAL")
    return d


def load_rfp_constraints_compat(root: Optional[Path] = None) -> dict:
    """The values ``abep_sim.constants.RFPConstraints`` carries (field by field, today's values)."""
    comp = load_requirements_snapshot(root).get("rfp_constraints_compat") or {}
    if tuple(comp) != RFP_COMPAT_FIELDS:
        raise ConfigurationError(f"rfp_constraints_compat fields {tuple(comp)} != {RFP_COMPAT_FIELDS}")
    out = {}
    for k in _RFP_FLOAT_FIELDS:
        v = comp[k]["value"]
        if isinstance(v, bool) or not isinstance(v, (int, float)):
            raise ConfigurationError(f"rfp_constraints_compat.{k}: non-numeric value {v!r}")
        out[k] = float(v)
    sub = comp["ic_subsystem_min"]["value"]
    if not isinstance(sub, dict) or not all(isinstance(v, (int, float)) and not isinstance(v, bool)
                                            for v in sub.values()):
        raise ConfigurationError("rfp_constraints_compat.ic_subsystem_min must map subsystem -> number")
    out["ic_subsystem_min"] = {k: float(v) for k, v in sub.items()}
    hp = comp["hall_preferred"]["value"]
    if not isinstance(hp, bool):
        raise ConfigurationError("rfp_constraints_compat.hall_preferred must be a boolean")
    out["hall_preferred"] = hp
    return out


def load_engineering_constraints_file(root: Optional[Path] = None) -> dict:
    """The frozen engineering-constraints artefact config/constraints/engineering_constraints_v1.json (A9.23), checked
    against MANIFEST.json. Physics / design seams read constraint values from here only (never config/requirements)."""
    d = load_verified(CONSTRAINTS_REL, root)
    if d.get("schema") != "abep_config_engineering_constraints_v1":
        raise ConfigurationError("engineering constraints: unexpected schema")
    if d.get("set_status") not in ("FROZEN", "PROVISIONAL"):
        raise ConfigurationError(f"engineering constraints: set_status {d.get('set_status')!r} not FROZEN/PROVISIONAL")
    for k, e in (d.get("constraints") or {}).items():
        if e.get("status") not in ("FROZEN", "PROVISIONAL"):
            raise ConfigurationError(f"engineering constraint {k}: status {e.get('status')!r} not FROZEN/PROVISIONAL")
    return d


def load_mission_scenario(root: Optional[Path] = None, verify_constraints: bool = True) -> dict:
    """The operating scenario; with ``verify_constraints`` its pin of the engineering-constraints file is checked."""
    d = load_verified(MISSION_REL, root)
    if d.get("schema") != "abep_config_mission_scenario_v1":
        raise ConfigurationError("mission scenario: unexpected schema")
    if verify_constraints:
        root_ = Path(root) if root is not None else config_root()
        pin = d.get("engineering_constraints") or {}
        got = _sha256_file(root_ / CONSTRAINTS_REL) if (root_ / CONSTRAINTS_REL).is_file() else None
        if got is None or got != pin.get("sha256"):
            raise ConfigurationError(f"mission scenario pins engineering constraints sha256 {pin.get('sha256')}, "
                                     f"found {got}")
    return d


def _num_field(d: dict, key: str, what: str) -> float:
    if not isinstance(d, dict) or key not in d:
        raise ConfigurationError(f"{what}: field {key!r} missing")
    v = d[key]
    if isinstance(v, bool) or not isinstance(v, (int, float)):
        raise ConfigurationError(f"{what}.{key}: non-numeric value {v!r}")
    return float(v)


def _pair(v, what: str) -> tuple:
    if not (isinstance(v, list) and len(v) == 2 and all(isinstance(x, (int, float)) and not isinstance(x, bool)
                                                        for x in v)):
        raise ConfigurationError(f"{what}: expected [lo, hi]")
    return float(v[0]), float(v[1])


def load_engineering_constraints(root: Optional[Path] = None) -> dict:
    """Frozen engineering-constraint VALUES (A9.23) from config/constraints/engineering_constraints_v1.json, for the
    design seam (abep_sim.design.engineering_constraints), the operating-inputs seam and the assessment layer.
    Never opens config/requirements/: no requirement / clause id leaves this loader (provenance stays in the file)."""
    d = load_engineering_constraints_file(root)
    c = d["constraints"]
    w = "engineering_constraints.constraints"
    missing = [k for k in CONSTRAINT_IDS if k not in c]
    if missing:
        raise ConfigurationError(f"{w}: constraints {missing} missing")
    alt = _pair(c["altitude_band_km"].get("value"), f"{w}.altitude_band_km")
    fl = c["firing_life_h"]
    if fl.get("label") != "SUBSYSTEM_FIRING_LIFE_ASSUMPTION":
        raise ConfigurationError(f"{w}.firing_life_h: label {fl.get('label')!r} != SUBSYSTEM_FIRING_LIFE_ASSUMPTION")
    ml = c["mission_life_h"]
    if ml.get("g1_status") != "APPLIED":
        raise ConfigurationError(f"{w}.mission_life_h: A9.22 G1 not recorded as APPLIED")
    sub = c["ic_subsystem_min"].get("value")
    if not isinstance(sub, dict) or not all(isinstance(v, (int, float)) and not isinstance(v, bool)
                                            for v in sub.values()):
        raise ConfigurationError(f"{w}.ic_subsystem_min must map subsystem -> number")
    hp = c["hall_preferred"].get("value")
    if not isinstance(hp, bool):
        raise ConfigurationError(f"{w}.hall_preferred must be a boolean")
    pc = c["propellant_capability"].get("value")
    if not isinstance(pc, dict) or set(pc) != {"ambient_atmosphere", "xe"}:
        raise ConfigurationError(f"{w}.propellant_capability must name ambient_atmosphere and xe")
    return {
        "thrust_min_mN": _num_field(c["thrust_sustained_min_mN"], "value", f"{w}.thrust_sustained_min_mN"),
        "thrust_max_mN": _num_field(c["thrust_capability_mN"], "value", f"{w}.thrust_capability_mN"),
        "power_max_W": _num_field(c["p_bus_max_W"], "value", f"{w}.p_bus_max_W"),
        "mass_max_kg": _num_field(c["wet_mass_max_kg"], "value", f"{w}.wet_mass_max_kg"),
        "alt_min_km": alt[0],
        "alt_max_km": alt[1],
        "ignition_hours": _num_field(fl, "value", f"{w}.firing_life_h"),
        "firing_hours_label": fl["label"],
        "mission_life_h": _num_field(ml, "value", f"{w}.mission_life_h"),
        "historical_mission_hours": _num_field(ml.get("historical_value") or {}, "value_h",
                                               f"{w}.mission_life_h.historical_value"),
        "intake_drag_generation_limit_mN": _num_field(c["intake_drag_generation_limit_mN"], "value",
                                                      f"{w}.intake_drag_generation_limit_mN"),
        "ic_total_min": _num_field(c["ic_total_min"], "value", f"{w}.ic_total_min"),
        "ic_subsystem_min": {k: float(v) for k, v in sub.items()},
        "hall_preferred": hp,
        "propellant_capability": dict(pc),
        "status": {k: e["status"] for k, e in c.items()},
        "set_status": d["set_status"],
        "id": d["id"],
        "source": f"config/{CONSTRAINTS_REL}",
    }


def load_operating_inputs(root: Optional[Path] = None) -> dict:
    """Operating inputs of the physics seam (abep_sim.operating_inputs): the operating-scenario choices of
    config/mission/mission_scenario_v1.json plus the constraint values it references (by id) from
    config/constraints/engineering_constraints_v1.json (the scenario's sha256 pin of that file is verified).

    The physics layer never opens the requirements snapshot. Fails closed on any missing or non-numeric value, on an
    input that restates a referenced constraint, and on a mission basis not recorded as the applied A9.22 G1 basis."""
    ms = load_mission_scenario(root, verify_constraints=True)
    ec = load_engineering_constraints(root)
    inp = ms.get("inputs") or {}
    w = "mission_scenario.inputs"

    def ref(key, cid):
        e = inp.get(key) or {}
        if e.get("kind") != "CONSTRAINT_REFERENCE" or e.get("constraint_ref") != cid or "value" in e:
            raise ConfigurationError(f"{w}.{key}: expected a value-free CONSTRAINT_REFERENCE to {cid}")

    def choice(key, cid):
        e = inp.get(key) or {}
        if e.get("kind") != "OPERATING_SCENARIO_CHOICE" or e.get("set_equal_to_constraint") != cid:
            raise ConfigurationError(f"{w}.{key}: expected an OPERATING_SCENARIO_CHOICE set from {cid}")
        return _num_field(e, "value", f"{w}.{key}")

    mh = inp.get("mission_hours") or {}
    if mh.get("g1_status") != "APPLIED" or mh.get("label") != "MISSION_DURATION_BASIS":
        raise ConfigurationError(f"{w}.mission_hours: A9.22 G1 not recorded as APPLIED (label {mh.get('label')!r})")
    fh = inp.get("firing_hours") or {}
    if fh.get("label") != "SUBSYSTEM_FIRING_LIFE_ASSUMPTION":
        raise ConfigurationError(f"{w}.firing_hours: label {fh.get('label')!r} != SUBSYSTEM_FIRING_LIFE_ASSUMPTION")
    ref("altitude_domain_km", "altitude_band_km")
    ref("wet_mass_limit_kg", "wet_mass_max_kg")
    ref("firing_hours", "firing_life_h")
    return {
        "mission_hours": choice("mission_hours", "mission_life_h"),
        "historical_mission_hours": _num_field(mh.get("historical_note") or {}, "value_h",
                                               f"{w}.mission_hours.historical_note"),
        "firing_hours": ec["ignition_hours"],
        "firing_hours_label": ec["firing_hours_label"],
        "thrust_min_mN": choice("xe_sizing_thrust_target_mN", "thrust_sustained_min_mN"),
        "thrust_max_mN": choice("commanded_thrust_cap_mN", "thrust_capability_mN"),
        "P_bus_max_W": choice("p_bus_throttling_cap_W", "p_bus_max_W"),
        "mass_max_kg": ec["mass_max_kg"],
        "altitude_domain_km": (ec["alt_min_km"], ec["alt_max_km"]),
        "source": f"config/{MISSION_REL} + config/{CONSTRAINTS_REL}",
    }


def load_design_state_set_ref(root: Optional[Path] = None, verify_target: bool = True) -> dict:
    d = load_verified(DESIGN_STATE_REF_REL, root)
    if d.get("schema") != "abep_config_design_state_set_ref_v1":
        raise ConfigurationError("design-state set reference: unexpected schema")
    if verify_target:
        _check_ref(d["path"], d["sha256"], "design-state set reference")
        _check_ref(d["manifest"]["path"], d["manifest"]["sha256"], "design-state set dataset manifest")
    return d


def load_hardware_bounds(root: Optional[Path] = None, verify_targets: bool = True) -> dict:
    d = load_verified(HARDWARE_BOUNDS_REL, root)
    if d.get("schema") != "abep_config_hardware_bounds_index_v1":
        raise ConfigurationError("hardware bounds index: unexpected schema")
    if verify_targets:
        for e in d["entries"]:
            _check_ref(e["path"], e["sha256"], f"hardware bounds entry {e['id']}")
    return d


def load_model_set(root: Optional[Path] = None) -> dict:
    d = load_verified(MODEL_SET_REL, root)
    if d.get("schema") != "abep_config_physics_model_set_v1":
        raise ConfigurationError("physics model set: unexpected schema")
    return d


def model_set_drift(root: Optional[Path] = None) -> list[str]:
    """Physics modules / data files whose live sha256 differs from the model set (empty = consistent)."""
    d = load_model_set(root)
    bad = []
    for e in list(d["modules"]) + list(d["data"]):
        p = REPO_ROOT / e["path"]
        if not p.is_file():
            bad.append(f"{e['path']}: missing")
        elif _sha256_file(p) != e["sha256"]:
            bad.append(f"{e['path']}: sha256 differs from the model set")
    return bad


# ------------------------------------------------------------------------------------------- simulation configuration
@dataclass(frozen=True)
class SimulationConfiguration:
    """Identity of every input a simulation consumes (ids + sha256), recorded with each result.

    ``requirements_snapshot_id`` / ``_sha256`` are None for a raw physics run (``physics_configuration``): the physics
    layer never needs the requirements snapshot; the assessment layer adds it (``assessment_configuration``)."""
    architecture_id: str
    architecture_sha256: str
    design_state_set_id: str
    design_state_set_sha256: str
    materials_id: str
    hardware_bounds_id: str
    hardware_bounds_sha256: str
    model_set_id: str
    model_set_sha256: str
    model_versions: tuple = field(default_factory=tuple)               # ((label, value), ...) sorted
    numerical_method_versions: tuple = field(default_factory=tuple)    # ((label, value), ...) sorted
    engineering_constraints_id: Optional[str] = None
    engineering_constraints_sha256: Optional[str] = None
    requirements_snapshot_id: Optional[str] = None
    requirements_snapshot_sha256: Optional[str] = None
    requirements_snapshot_status: Optional[str] = None
    config_manifest_sha256: str = ""

    def as_dict(self) -> dict:
        d = {k: getattr(self, k) for k in self.__dataclass_fields__}
        d["model_versions"] = dict(self.model_versions)
        d["numerical_method_versions"] = dict(self.numerical_method_versions)
        return d


def physics_configuration(root: Optional[Path] = None) -> SimulationConfiguration:
    """Raw-physics configuration: architecture, frozen engineering constraints, design-state set, hardware bounds,
    model set (A9.23). Never opens the requirements snapshot (or anything under docs/requirements)."""
    root = Path(root) if root is not None else config_root()
    man = load_manifest(root)["files"]
    arch = load_architecture(root)
    ds = load_design_state_set_ref(root)
    hw = load_hardware_bounds(root)
    ms = load_model_set(root)
    ec = load_engineering_constraints_file(root)
    mat = next(e for e in hw["entries"] if e["kind"] == "materials_database")
    return SimulationConfiguration(
        architecture_id=arch["id"], architecture_sha256=man[ARCHITECTURE_REL]["sha256"],
        design_state_set_id=ds["id"], design_state_set_sha256=ds["sha256"],
        materials_id=f"{mat['id']}@{mat['sha256'][:16]}",
        hardware_bounds_id=hw["id"], hardware_bounds_sha256=man[HARDWARE_BOUNDS_REL]["sha256"],
        model_set_id=ms["id"], model_set_sha256=man[MODEL_SET_REL]["sha256"],
        engineering_constraints_id=ec["id"], engineering_constraints_sha256=man[CONSTRAINTS_REL]["sha256"],
        model_versions=tuple(sorted(ms["version_labels_flat"].items())),
        numerical_method_versions=tuple(sorted(ms["numerical_methods_flat"].items())),
        config_manifest_sha256=_sha256_file(root / MANIFEST_REL))


def assessment_configuration(root: Optional[Path] = None) -> SimulationConfiguration:
    """Physics configuration plus the requirements snapshot identity (assessment layer)."""
    root = Path(root) if root is not None else config_root()
    base = physics_configuration(root)
    snap = load_requirements_snapshot(root)
    d = base.as_dict()
    d.update(model_versions=base.model_versions, numerical_method_versions=base.numerical_method_versions,
             requirements_snapshot_id=snap["id"],
             requirements_snapshot_sha256=load_manifest(root)["files"][REQUIREMENTS_REL]["sha256"],
             requirements_snapshot_status=snap["snapshot_status"])
    return SimulationConfiguration(**d)
