"""Authoritative input manifests (A9.22 layer separation, Phase A): loaders for ``config/`` and the
``SimulationConfiguration`` record.

Owner directive 2026-10-03 (docs/decisions/OD_2026_10_03_A9_22_*): four layers REQUIREMENTS -> FROZEN ENGINEERING
CONFIGURATION -> PHYSICS -> ASSESSMENT. The physics never reads or interprets the RFP / RVM / clause ids; it consumes
versioned, sha256-pinned configuration files. This module is that interface:

  config/MANIFEST.json                                  every config file + sha256 (root of trust for this directory)
  config/architecture/hall_icp_neutralizer_v1.json      A9.19 / A9.20 / A9.15 flight architecture (design layer)
  config/requirements/rfp_constraints_v1.json           requirements snapshot generated from the RVM limit fields
  config/mission/mission_scenario_v1.json               operating-scenario inputs (provenance to the snapshot)
  config/environment/design_state_set_ref_v1.json       REFERENCE to the frozen design-state set v2 (never a copy)
  config/hardware/hardware_bounds_v1.json               INDEX of hardware-limit sources (path + sha256 + locator)
  config/model_set/physics_model_set_v1.json            physics module / data hashes and version labels

Every loader fails closed: a file missing from the manifest, a file whose sha256 differs from the manifest, or a
referenced file whose sha256 differs from the pin raises ``ConfigurationError`` (no fallback, CLAUDE.md rule 3).
The files are generated by ``scripts/config/build_config.py`` from the existing sources. ``abep_sim.constants.RFP``
keeps its recorded values (immutable; its mission_hours = 26,000 h is HISTORICAL_CONSTANT_NOT_CONSUMED since the
A9.22 G1 governed migration). The seams ``abep_sim.operating_inputs`` (physics) and
``abep_sim.design.engineering_constraints`` (design) read their values through ``load_operating_inputs`` and
``load_engineering_constraints`` below.

``physics_configuration()`` is the raw-physics entry point: it never opens the requirements snapshot.
The config root is ``<repository>/config``; ``ABEP_CONFIG_ROOT`` overrides it (used when the package is installed
outside a checkout). There is no packaged fallback copy.
"""
from __future__ import annotations

import hashlib
import json
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

REPO_ROOT = Path(__file__).resolve().parents[1]
CONFIG_ENV = "ABEP_CONFIG_ROOT"

MANIFEST_REL = "MANIFEST.json"
ARCHITECTURE_REL = "architecture/hall_icp_neutralizer_v1.json"
REQUIREMENTS_REL = "requirements/rfp_constraints_v1.json"
MISSION_REL = "mission/mission_scenario_v1.json"
DESIGN_STATE_REF_REL = "environment/design_state_set_ref_v1.json"
HARDWARE_BOUNDS_REL = "hardware/hardware_bounds_v1.json"
MODEL_SET_REL = "model_set/physics_model_set_v1.json"

# RFPConstraints fields carried by the snapshot's compatibility block (abep_sim.constants.RFP; same names, same order)
RFP_COMPAT_FIELDS = ("thrust_min_mN", "thrust_max_mN", "power_max_W", "mass_max_kg", "alt_min_km", "alt_max_km",
                     "ignition_hours", "mission_hours", "ic_total_min", "ic_subsystem_min", "hall_preferred")
_RFP_FLOAT_FIELDS = RFP_COMPAT_FIELDS[:-2]


class ConfigurationError(RuntimeError):
    """A configuration file is missing, unlisted, altered, or references an altered source (fail closed)."""


def config_root() -> Path:
    env = os.environ.get(CONFIG_ENV)
    return Path(env) if env else REPO_ROOT / "config"


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def load_manifest(root: Optional[Path] = None) -> dict:
    root = Path(root) if root is not None else config_root()
    p = root / MANIFEST_REL
    if not p.is_file():
        raise ConfigurationError(f"{p} missing: the configuration manifest is required (no fallback); build it with "
                                 "python scripts/config/build_config.py")
    m = json.loads(p.read_text(encoding="utf-8"))
    if m.get("schema") != "abep_config_manifest_v1" or not isinstance(m.get("files"), dict):
        raise ConfigurationError(f"{p} is not an abep_config_manifest_v1")
    return m


def load_verified(rel: str, root: Optional[Path] = None) -> dict:
    """Load ``config/<rel>`` after checking it is listed in MANIFEST.json with a matching sha256."""
    root = Path(root) if root is not None else config_root()
    files = load_manifest(root)["files"]
    if rel not in files:
        raise ConfigurationError(f"config/{rel} is not listed in config/MANIFEST.json")
    p = root / rel
    if not p.is_file():
        raise ConfigurationError(f"config/{rel} missing (listed in config/MANIFEST.json; no fallback)")
    got = _sha256_file(p)
    if got != files[rel]["sha256"]:
        raise ConfigurationError(f"config/{rel} sha256 {got} != MANIFEST {files[rel]['sha256']} (an edited "
                                 "configuration file is refused; regenerate with scripts/config/build_config.py)")
    return json.loads(p.read_text(encoding="utf-8"))


def _check_ref(path_rel: str, want: str, what: str) -> Path:
    p = REPO_ROOT / path_rel
    if not p.is_file():
        raise ConfigurationError(f"{what}: referenced file {path_rel} missing")
    got = _sha256_file(p)
    if got != want:
        raise ConfigurationError(f"{what}: referenced file {path_rel} sha256 {got} != pinned {want}")
    return p


# -------------------------------------------------------------------------------------------------------- loaders
def load_architecture(root: Optional[Path] = None) -> dict:
    d = load_verified(ARCHITECTURE_REL, root)
    if d.get("schema") != "abep_config_architecture_v1":
        raise ConfigurationError("architecture config: unexpected schema")
    return d


def load_requirements_snapshot(root: Optional[Path] = None) -> dict:
    d = load_verified(REQUIREMENTS_REL, root)
    if d.get("schema") != "abep_config_requirements_snapshot_v1":
        raise ConfigurationError("requirements snapshot: unexpected schema")
    if d.get("snapshot_status") not in ("FROZEN", "PROVISIONAL"):
        raise ConfigurationError(f"requirements snapshot: status {d.get('snapshot_status')!r} not FROZEN/PROVISIONAL")
    return d


def load_rfp_constraints_compat(root: Optional[Path] = None) -> dict:
    """The values ``abep_sim.constants.RFPConstraints`` carries (field by field, today's values)."""
    comp = load_requirements_snapshot(root).get("rfp_constraints_compat") or {}
    if tuple(comp) != RFP_COMPAT_FIELDS:
        raise ConfigurationError(f"rfp_constraints_compat fields {tuple(comp)} != {RFP_COMPAT_FIELDS}")
    out = {}
    for k in _RFP_FLOAT_FIELDS:
        v = comp[k]["value"]
        if isinstance(v, bool) or not isinstance(v, (int, float)):
            raise ConfigurationError(f"rfp_constraints_compat.{k}: non-numeric value {v!r}")
        out[k] = float(v)
    sub = comp["ic_subsystem_min"]["value"]
    if not isinstance(sub, dict) or not all(isinstance(v, (int, float)) and not isinstance(v, bool)
                                            for v in sub.values()):
        raise ConfigurationError("rfp_constraints_compat.ic_subsystem_min must map subsystem -> number")
    out["ic_subsystem_min"] = {k: float(v) for k, v in sub.items()}
    hp = comp["hall_preferred"]["value"]
    if not isinstance(hp, bool):
        raise ConfigurationError("rfp_constraints_compat.hall_preferred must be a boolean")
    out["hall_preferred"] = hp
    return out


def load_mission_scenario(root: Optional[Path] = None, verify_snapshot: bool = True) -> dict:
    d = load_verified(MISSION_REL, root)
    if d.get("schema") != "abep_config_mission_scenario_v1":
        raise ConfigurationError("mission scenario: unexpected schema")
    if verify_snapshot:
        root_ = Path(root) if root is not None else config_root()
        snap = d["requirements_snapshot"]
        got = _sha256_file(root_ / REQUIREMENTS_REL) if (root_ / REQUIREMENTS_REL).is_file() else None
        if got != snap["sha256"]:
            raise ConfigurationError(f"mission scenario pins requirements snapshot sha256 {snap['sha256']}, found {got}")
    return d


def _num_field(d: dict, key: str, what: str) -> float:
    if not isinstance(d, dict) or key not in d:
        raise ConfigurationError(f"{what}: field {key!r} missing")
    v = d[key]
    if isinstance(v, bool) or not isinstance(v, (int, float)):
        raise ConfigurationError(f"{what}.{key}: non-numeric value {v!r}")
    return float(v)


def load_operating_inputs(root: Optional[Path] = None) -> dict:
    """Operating inputs of the physics seam (abep_sim.operating_inputs), from config/mission/mission_scenario_v1.json.

    The physics layer never opens the requirements snapshot: the mission scenario is read with
    ``verify_snapshot=False`` (its own sha256 is still checked against MANIFEST.json; the scenario -> snapshot pin is
    checked by load_engineering_constraints, the configuration tests and ``build_config.py --check``). Fails closed on
    any missing or non-numeric value and on a mission basis not recorded as the applied A9.22 G1 basis."""
    inp = load_mission_scenario(root, verify_snapshot=False).get("inputs") or {}
    w = "mission_scenario.inputs"
    mh = inp.get("mission_hours") or {}
    if mh.get("g1_status") != "APPLIED" or mh.get("label") != "MISSION_DURATION_BASIS":
        raise ConfigurationError(f"{w}.mission_hours: A9.22 G1 not recorded as APPLIED (label {mh.get('label')!r})")
    fh = inp.get("firing_hours") or {}
    if fh.get("label") != "SUBSYSTEM_FIRING_LIFE_ASSUMPTION":
        raise ConfigurationError(f"{w}.firing_hours: label {fh.get('label')!r} != SUBSYSTEM_FIRING_LIFE_ASSUMPTION")
    alt = (inp.get("altitude_domain_km") or {}).get("value")
    if not (isinstance(alt, list) and len(alt) == 2 and all(isinstance(x, (int, float)) and not isinstance(x, bool)
                                                            for x in alt)):
        raise ConfigurationError(f"{w}.altitude_domain_km: expected [lo, hi]")
    return {
        "mission_hours": _num_field(mh, "value", f"{w}.mission_hours"),
        "historical_mission_hours": _num_field(mh.get("historical_note") or {}, "value_h",
                                               f"{w}.mission_hours.historical_note"),
        "firing_hours": _num_field(fh, "value", f"{w}.firing_hours"),
        "firing_hours_label": fh["label"],
        "thrust_min_mN": _num_field(inp.get("xe_sizing_thrust_target_mN"), "value", f"{w}.xe_sizing_thrust_target_mN"),
        "thrust_max_mN": _num_field(inp.get("commanded_thrust_cap_mN"), "value", f"{w}.commanded_thrust_cap_mN"),
        "P_bus_max_W": _num_field(inp.get("p_bus_throttling_cap_W"), "value", f"{w}.p_bus_throttling_cap_W"),
        "mass_max_kg": _num_field(inp.get("wet_mass_limit_kg"), "value", f"{w}.wet_mass_limit_kg"),
        "altitude_domain_km": (float(alt[0]), float(alt[1])),
        "source": f"config/{MISSION_REL}",
    }


def load_engineering_constraints(root: Optional[Path] = None) -> dict:
    """Frozen engineering-constraint values of the design seam (abep_sim.design.engineering_constraints), from the
    requirements snapshot's compatibility block (config/requirements/rfp_constraints_v1.json) and the mission domain
    of config/mission/mission_scenario_v1.json (snapshot pin verified). Values only: no clause id leaves this loader."""
    comp = load_rfp_constraints_compat(root)
    ms = load_mission_scenario(root, verify_snapshot=True)["inputs"]
    alt = ms["altitude_domain_km"]["value"]
    if [float(x) for x in alt] != [comp["alt_min_km"], comp["alt_max_km"]]:
        raise ConfigurationError("mission_scenario altitude domain differs from the requirements snapshot")
    out = {k: comp[k] for k in ("thrust_min_mN", "thrust_max_mN", "power_max_W", "mass_max_kg", "alt_min_km",
                                "alt_max_km", "ignition_hours")}
    out["source"] = f"config/{REQUIREMENTS_REL} (rfp_constraints_compat) + config/{MISSION_REL} (altitude domain)"
    return out


def load_design_state_set_ref(root: Optional[Path] = None, verify_target: bool = True) -> dict:
    d = load_verified(DESIGN_STATE_REF_REL, root)
    if d.get("schema") != "abep_config_design_state_set_ref_v1":
        raise ConfigurationError("design-state set reference: unexpected schema")
    if verify_target:
        _check_ref(d["path"], d["sha256"], "design-state set reference")
        _check_ref(d["manifest"]["path"], d["manifest"]["sha256"], "design-state set dataset manifest")
    return d


def load_hardware_bounds(root: Optional[Path] = None, verify_targets: bool = True) -> dict:
    d = load_verified(HARDWARE_BOUNDS_REL, root)
    if d.get("schema") != "abep_config_hardware_bounds_index_v1":
        raise ConfigurationError("hardware bounds index: unexpected schema")
    if verify_targets:
        for e in d["entries"]:
            _check_ref(e["path"], e["sha256"], f"hardware bounds entry {e['id']}")
    return d


def load_model_set(root: Optional[Path] = None) -> dict:
    d = load_verified(MODEL_SET_REL, root)
    if d.get("schema") != "abep_config_physics_model_set_v1":
        raise ConfigurationError("physics model set: unexpected schema")
    return d


def model_set_drift(root: Optional[Path] = None) -> list[str]:
    """Physics modules / data files whose live sha256 differs from the model set (empty = consistent)."""
    d = load_model_set(root)
    bad = []
    for e in list(d["modules"]) + list(d["data"]):
        p = REPO_ROOT / e["path"]
        if not p.is_file():
            bad.append(f"{e['path']}: missing")
        elif _sha256_file(p) != e["sha256"]:
            bad.append(f"{e['path']}: sha256 differs from the model set")
    return bad


# ------------------------------------------------------------------------------------------- simulation configuration
@dataclass(frozen=True)
class SimulationConfiguration:
    """Identity of every input a simulation consumes (ids + sha256), recorded with each result.

    ``requirements_snapshot_id`` / ``_sha256`` are None for a raw physics run (``physics_configuration``): the physics
    layer never needs the requirements snapshot; the assessment layer adds it (``assessment_configuration``)."""
    architecture_id: str
    architecture_sha256: str
    design_state_set_id: str
    design_state_set_sha256: str
    materials_id: str
    hardware_bounds_id: str
    hardware_bounds_sha256: str
    model_set_id: str
    model_set_sha256: str
    model_versions: tuple = field(default_factory=tuple)               # ((label, value), ...) sorted
    numerical_method_versions: tuple = field(default_factory=tuple)    # ((label, value), ...) sorted
    requirements_snapshot_id: Optional[str] = None
    requirements_snapshot_sha256: Optional[str] = None
    requirements_snapshot_status: Optional[str] = None
    config_manifest_sha256: str = ""

    def as_dict(self) -> dict:
        d = {k: getattr(self, k) for k in self.__dataclass_fields__}
        d["model_versions"] = dict(self.model_versions)
        d["numerical_method_versions"] = dict(self.numerical_method_versions)
        return d


def physics_configuration(root: Optional[Path] = None) -> SimulationConfiguration:
    """Raw-physics configuration: architecture, design-state set, hardware bounds, model set. Never opens the
    requirements snapshot (or anything under docs/requirements)."""
    root = Path(root) if root is not None else config_root()
    man = load_manifest(root)["files"]
    arch = load_architecture(root)
    ds = load_design_state_set_ref(root)
    hw = load_hardware_bounds(root)
    ms = load_model_set(root)
    mat = next(e for e in hw["entries"] if e["kind"] == "materials_database")
    return SimulationConfiguration(
        architecture_id=arch["id"], architecture_sha256=man[ARCHITECTURE_REL]["sha256"],
        design_state_set_id=ds["id"], design_state_set_sha256=ds["sha256"],
        materials_id=f"{mat['id']}@{mat['sha256'][:16]}",
        hardware_bounds_id=hw["id"], hardware_bounds_sha256=man[HARDWARE_BOUNDS_REL]["sha256"],
        model_set_id=ms["id"], model_set_sha256=man[MODEL_SET_REL]["sha256"],
        model_versions=tuple(sorted(ms["version_labels_flat"].items())),
        numerical_method_versions=tuple(sorted(ms["numerical_methods_flat"].items())),
        config_manifest_sha256=_sha256_file(root / MANIFEST_REL))


def assessment_configuration(root: Optional[Path] = None) -> SimulationConfiguration:
    """Physics configuration plus the requirements snapshot identity (assessment layer)."""
    root = Path(root) if root is not None else config_root()
    base = physics_configuration(root)
    snap = load_requirements_snapshot(root)
    d = base.as_dict()
    d.update(model_versions=base.model_versions, numerical_method_versions=base.numerical_method_versions,
             requirements_snapshot_id=snap["id"],
             requirements_snapshot_sha256=load_manifest(root)["files"][REQUIREMENTS_REL]["sha256"],
             requirements_snapshot_status=snap["snapshot_status"])
    return SimulationConfiguration(**d)
