"""Clause-by-clause data of the DBF-1.2 technical annexure (rev 2).

Single source for compliance_matrix_dbf1_2_v1.json and A1_COMPLIANCE_MATRIX.md (generated by build_annexure.py). Every
technical number is a `{{NAME}}` placeholder filled from the DBF-1.2 freeze commit (annexure_pin_v1.json); none is typed
here. Status vocabulary is the one of the historical bid package (A9.27), so every change against that package is
visible clause by clause (the generator lists them). `dbf_trace` names the DBF-1.2 requirement-trace rows (RVM ids) the
clause rests on; `evidence` paths are files at the DBF-1.2 freeze commit.
Nothing here is a test result, a PASS or a GO. DBF-1.2 is never labelled fully RFP-qualified, demonstrated compliant,
flight-qualified, performance validated or a final flight design.
"""

STATUSES = ["COMPLY", "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "PARTIAL", "NOT_YET_DEMONSTRATED", "OWNER_INPUT_REQUIRED"]

STATUS_DEFINITIONS = {
    "COMPLY": "the offered design (DBF-1.2) meets the clause as written; a property of the offer, no test result implied",
    "COMPLY_PLANNED_WITH_EVIDENCE_PATH": "the frozen DBF-1.2 preliminary design conforms by design / allocation, or a "
                                         "plan exists; compliance is verified on EM / QM hardware; nothing is yet "
                                         "demonstrated",
    "PARTIAL": "some sub-items are covered by the DBF-1.2 design or plan, others are not yet (listed in the response)",
    "NOT_YET_DEMONSTRATED": "the outcome depends on hardware / validation evidence that does not exist yet and that the "
                            "preliminary design cannot substitute for; the annexure does not claim the outcome",
    "OWNER_INPUT_REQUIRED": "organisational, commercial or facility information the repository does not hold; the "
                            "owner supplies it",
}

STATUS_RULE = ("A clause moves from the A9.27 package status only where the DBF-1.2 requirement trace (approved baseline, "
               "A9.41 / A9.42 / A9.43) gives a CONFORMING_BY_DESIGN / ALLOCATION state with an EM / QM verification "
               "path; owner rulings A9.27 (RFP-P19-03 COMPLY composition only; RFP-P18-08 split) are kept; no clause "
               "is raised to COMPLY by this regeneration; VERIFY_EM_QM-only trace states (life, AO, thermal) do not "
               "change a status.")

DBF = "docs/baseline/DBF-1.2/dbf1_2_v1.json"
TRACE = "docs/baseline/DBF-1.2/dbf1_2_requirement_trace_v1.json"
RISKS = "docs/baseline/DBF-1.2/dbf1_2_risk_register_v1.json"
RVM = "docs/requirements/rvm_a9/rvm_a9_v1.json"
POWER = "docs/closure/power/power_ledger_v1.json"
THERM = "docs/closure/thermal/thermal_closure_v2.json"
ICP = "docs/closure/icp/icp_closure_v1.json"
MAT = "docs/closure/materials/materials_gates_v1.json"
BZ = "docs/closure/P3_h1_magnetic_field_closure_v1.json"
CONC = "docs/closure/conclusion/ARCHITECTURE_CLOSURE_CONCLUSION_v2.md"
CONS = "config/constraints/engineering_constraints_v1.json"
A940 = "docs/decisions/OD_2026_10_10_A9_40_dbf_1_2_freeze_gates_air_operating_concept_host_drag.json"
A941 = "docs/decisions/OD_2026_10_10_A9_41_dcr_dbf1_001_approval_mass_risk.json"
A943 = "docs/decisions/OD_2026_10_10_A9_43_power_reconciliation_and_dbf_1_2_freeze.json"
A927 = "docs/decisions/OD_2026_10_05_A9_27_final_bid_owner_rulings.json"
A919 = "docs/decisions/OD_2026_10_01_A9_19_architecture_xe_contingency_owner_decision.json"
A920 = "docs/decisions/OD_2026_10_01_A9_20_c1_ground_only_owner_decision.json"
PIVOT = "docs/decisions/OD_HARDWARE_PIVOT_2026_09_27.json"
ENS = "hallthruster_bridge/ensemble/transport_ensemble_v0.json"
AO = "docs/experiments/lifetime_ao/ao_lifetime_register_v5.json"
INS = "docs/experiments/instrumentation/instrumentation_definition_v1.json"


def ev(path, locator):
    return {"path": path, "locator": locator}


NOT_DEMO = ("Not demonstrated: no Vyovrinda hardware has been built or tested; Hall-transport validation (gate 3) is "
            "FAIL and the credible transport set is empty, so every Hall performance figure is a design allocation or "
            "a PARAMETRIC / NOT_VALIDATED model value, never a measurement.")

CLAUSES = [
    {"id": "RFP-P16-01", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": ["RVM-21"],
     "response": "Vyovrinda proposes to develop, test and space-qualify an ABEP system for VLEO. The architecture and "
                 "preliminary design are frozen as DBF-1.2 ({{STATUS}}); compliance is verified on EM / QM hardware "
                 "through Milestones 1-5 (A3_VERIFICATION_PLAN.md). " + NOT_DEMO,
     "evidence": [ev(DBF, "#/status_semantics"), ev(TRACE, "#/trace")], "owner_input": []},
    {"id": "RFP-P16-02", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": ["RVM-08", "RVM-10 / RVM-29"],
     "response": "The DBF-1.2 architecture follows the RFP logical block diagram: Intake ({{INTAKE_A}} m2 aperture, "
                 "collimator L/D {{LD}}) -> filter -> Compressor (integrated contra-rotating molecular compressor) -> "
                 "Gas Chamber (plenum {{PLEN_V}} L at {{PLEN_SET}} Pa) -> Valve / H-1 distributor -> Thruster (H-1 "
                 "Hall accelerator, ionization and acceleration in one annular channel) -> Thrust; Xenon Gas -> Valve "
                 "-> Thruster (separate Xe branch AL-08). One element is added outside the diagram: a downstream "
                 "13.56 MHz RF-ICP electron source / neutralizer in place of a hollow cathode (cathodeless flight "
                 "architecture hall_icp_neutralizer, A9.19 / A9.20). Mapping in A2_TECHNICAL_DESCRIPTION.md section 2.",
     "evidence": [ev(DBF, "#/intake_compressor_feed"), ev(A919, "#/architecture")], "owner_input": []},
    {"id": "RFP-P17-01", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": ["RVM-21"],
     "response": "The EM -> EM integration -> EM integration test -> QM (intake / compressor, power electronics, "
                 "thruster) -> QM integration test flow is the model philosophy; DBF-1.2 is the design these models "
                 "build. Mapping onto the milestones and the DBF-1.2 verification items in A3_VERIFICATION_PLAN.md. No "
                 "EM or QM hardware exists yet.",
     "evidence": [ev(RISKS, "#/risks[id=VR-EMQM-01]")], "owner_input": []},
    {"id": "RFP-P17-02", "status": "NOT_YET_DEMONSTRATED", "dbf_trace": ["RVM-02", "RVM-16", "RVM-08"],
     "response": "Each critical technology has a frozen DBF-1.2 design answer and an EM / QM verification path; none "
                 "is demonstrated. (1) Thruster ionizing N2 and nascent O: H-1 (d_mean {{H1_D}} mm, h {{H1_H}} mm, "
                 "L {{H1_L}} mm, FE-derived B(z) FROZEN FOR EM) at the 12 mN AIR sizing point; the {{AIR_VEFF}} km/s "
                 "design basis is PARAMETRIC / NOT_VALIDATED (VR-HALL-01), gate 3 is FAIL and the ICP AIR closure is "
                 "{{ICP_STATE}}. (2) AO material compatibility: primary / backup materials frozen (INCONEL 600 / 601 "
                 "anode and collector; BN-SiO2 / BN wall); materials state {{MAT_STATE}}, closed only by coupon / EM "
                 "tests. (3) Intake and compressor: {{INTAKE_A}} m2 intake and 7-row contra-rotating molecular "
                 "compressor frozen; F6 / B7 transitional rows are EM verification risks (VR-CMP-02).",
     "evidence": [ev(DBF, "#/items"), ev(ICP, "#/closure"), ev(MAT, "#/closure_state"), ev(ENS, "#/members")],
     "owner_input": []},
    {"id": "RFP-P17-03", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": ["RVM-08"],
     "response": "Frozen intake (DBF12-IN-01): physical aperture {{INTAKE_A}} m2 (equivalent diameter {{INTAKE_D}} m), "
                 "collimator L/D {{LD}}, retention S_eff {{SEFF}} m3/s. Delivered flow is regulated by active "
                 "compressor / retention control with density-aware altitude scheduling (DBF12-IN-02); exposed frontal "
                 "drag is not controlled by compressor speed. Trace state RVM-08: {{T_RVM-08}}. Verified by EM intake / "
                 "compressor tests (Milestone 4).",
     "evidence": [ev(DBF, "#/intake_compressor_feed/DBF12-IN-01"), ev(TRACE, "#/trace[rvm=RVM-08]")],
     "owner_input": []},
    {"id": "RFP-P17-04", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": ["RVM-08"],
     "response": "Frozen compressor (DBF12-CMP-01): integrated contra-rotating molecular compressor, 7 blade rows + "
                 "shared Holweck rear section, two coaxial counter-rotating shafts, {{CMP_RPM}} rpm, tip speed "
                 "{{CMP_TIP}} m/s, governing mass {{CMP_MEV}} kg MEV, power estimate {{CMP_P}} W (allowance "
                 "{{CMP_PA}} W). Gas chamber: plenum setpoint {{PLEN_SET}} Pa (band {{PLEN_BAND}} Pa), volume "
                 "{{PLEN_V}} L. Rows F1-F5 are free-molecular; F6 / B7 (transitional) and the Holweck coefficients are "
                 "EM verification risks (VR-CMP-02, VR-CMP-03), rotor growth vs running clearance VR-CMP-04.",
     "evidence": [ev(DBF, "#/intake_compressor_feed/DBF12-CMP-01"), ev(DBF, "#/intake_compressor_feed/DBF12-FEED-01")],
     "owner_input": []},
    {"id": "RFP-P17-05", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": ["RVM-10 / RVM-29", "RVM-15 / RVM-28"],
     "response": "One H-1 Hall accelerator serves both supply modes with one downstream RF-ICP neutralizer (no hollow "
                 "cathode): AIR is the primary nominal mode (N2 / O-bearing ambient air, DBF12-OPS-01); Xe is the "
                 "required secondary mode for contingency / off-nominal / upper-envelope operation with the "
                 "atmospheric compressor OFF (DBF12-OPS-02) - the RFP's extra input system. Trace: RVM-10 / RVM-29 "
                 "{{T_RVM-10 / RVM-29}}; RVM-15 / RVM-28 {{T_RVM-15 / RVM-28}}. Ionization of atomic O is not "
                 "demonstrated: O2-bearing ground tests are NO_ATOMIC_O, atomic O only through the AO programme; ICP "
                 "AIR closure {{ICP_STATE}}.",
     "evidence": [ev(DBF, "#/operating_modes"), ev(ICP, "#/closure")], "owner_input": []},
    {"id": "RFP-P18-01", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": ["RVM-04"],
     "response": "A propulsion PPU (AL-07, {{PPU_MEV}} kg MEV, PRELIMINARY CBE / NOT MEASURED) takes power from the "
                 "satellite bus and generates all ABEP supplies: Hall discharge, magnet supplies, 13.56 MHz RF "
                 "generator + local match (AL-06), ICP collector bias, valve drivers, compressor drive, thermal "
                 "control, housekeeping. No flight cathode heater / keeper supply exists. Bus power at the AIR 12 mN "
                 "point: {{AIR_REF}} W reference / {{AIR_CONS}} W conservative (P6 ledger + DBF-1.2 compressor, A9.43).",
     "evidence": [ev(DBF, "#/power_rollup"), ev(POWER, "whole file")], "owner_input": []},
    {"id": "RFP-P18-02", "status": "PARTIAL", "dbf_trace": ["RVM-19"],
     "response": "Electronics level: the DBF-1.2 PPU estimate carries N+1 / redundant electronics (trace RVM-19: "
                 "{{T_RVM-19}}); verification by FMEA at PDR-1. Sensor level: no sensor-redundancy concept is defined "
                 "in DBF-1.2; it is an owner design decision to be booked within the mass risk MR-DCR001-01 (OIR-TEC-02).",
     "evidence": [ev(TRACE, "#/trace[rvm=RVM-19]")], "owner_input": ["OIR-TEC-02"]},
    {"id": "RFP-P18-03", "status": "OWNER_INPUT_REQUIRED", "dbf_trace": [],
     "response": "a) Indigenous content > 60 %: no supplier is selected, so no IC figure is stated (frozen programme "
                 "limit IC >= 75 % total, config/constraints). b) Vyovrinda will present the technical proposal to the "
                 "technical evaluation committee (presenters: owner). c) Consortium and its documentary proof: owner.",
     "evidence": [ev(CONS, "#/constraints/ic_total_min")], "owner_input": ["OIR-IC-01", "OIR-ORG-04", "OIR-ORG-05"]},
    {"id": "RFP-P18-04", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": ["RVM-01"],
     "response": "AIR mode operates by density-aware altitude scheduling within 180-230 km, at the 12 mN sizing point, "
                 "inside the admissible AIR density / thrust / drag window (DBF12-OPS-01, A9.40); Xe mode covers "
                 "contingency / off-nominal / upper-envelope cases. The 196-state set is a conservative verification "
                 "dataset, not 196 mandatory AIR points (DBF12-OPS-03). Trace RVM-01: {{T_RVM-01}}. Host drag at "
                 "PDR: IR-HOST-DRAG-01 (reference proposal sizing C_D*A {{CDA}} m2, REFERENCE_PENDING_ICD).",
     "evidence": [ev(DBF, "#/operating_modes"), ev(A940, "whole file")], "owner_input": []},
    {"id": "RFP-P18-05", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": ["RVM-08", "RVM-01"],
     "response": "The intake is sized from air density as a function of solar activity and altitude (frozen NRLMSIS "
                 "2.1 data; conservative 196-state set). A single fixed intake cannot span the whole state set "
                 "(conservation finding, architecture closure conclusion v2), so DBF-1.2 freezes a {{INTAKE_A}} m2 "
                 "aperture with active compressor / retention control and density-aware altitude scheduling inside "
                 "180-230 km (DBF12-IN-01 / -02, DBF12-OPS-01).",
     "evidence": [ev(CONC, "section 2-3"), ev(DBF, "#/intake_compressor_feed")], "owner_input": []},
    {"id": "RFP-P18-06", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": ["RVM-02", "RVM-03"],
     "response": "Design basis (owner reading DISC-07): >= 12 mN sustained on air and 25 mN capability. 12 mN AIR "
                 "sizing point (DBF12-AIR-01): v_eff {{AIR_VEFF}} km/s, Hall feed {{AIR_MDOT}} mg/s, discharge "
                 "allocation P_d {{AIR_PD}} W (FROZEN_ASSUMPTION; v_eff basis PARAMETRIC / NOT_VALIDATED, VR-HALL-01; "
                 "22 km/s sensitivity needs {{AIR22_MDOT}} mg/s, VR-HALL-02). 25 mN is a Xe-mode design capability "
                 "with a Hall discharge allocation <= {{XE1450N}} W (nominal ICP) / <= {{XE1450R}} W (+100 W RF) at "
                 "the 1,450 W design ceiling. Trace RVM-02 {{T_RVM-02}}; RVM-03 {{T_RVM-03}}. " + NOT_DEMO,
     "evidence": [ev(DBF, "#/air_design_point"), ev(DBF, "#/power_rollup/xe_25mN"), ev(A943, "whole file")],
     "owner_input": []},
    {"id": "RFP-P18-07", "status": "COMPLY", "dbf_trace": ["RVM-11"],
     "response": "The offered thruster is a Hall-effect thruster: one H-1 Hall accelerator (d_mean {{H1_D}} mm, h "
                 "{{H1_H}} mm, L {{H1_L}} mm; DBF1-H1-01..03). This states the thruster type only; no Hall performance "
                 "is demonstrated.",
     "evidence": [ev(DBF, "#/items[id=DBF1-H1-01]")], "owner_input": []},
    {"id": "RFP-P18-08", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": ["RVM-08", "RVM-10 / RVM-29"],
     "response": "Split (owner ruling A9.27, kept): (A) separate ambient-air path (intake -> compressor -> plenum) and "
                 "separate Xe storage / flow branch (AL-08, {{AL08}} kg MEV with the {{XE_REF}} kg Xe reference load) "
                 "- COMPLY BY DESIGN; (B) functional ambient-air + Xe propulsion capability - PLANNED / NOT YET "
                 "DEMONSTRATED (verified on EM / QM). Trace RVM-08 {{T_RVM-08}}; RVM-10 / RVM-29 {{T_RVM-10 / RVM-29}}.",
     "evidence": [ev(DBF, "#/mass_rollup"), ev(A927, "#/owner_decision_summary")], "owner_input": []},
    {"id": "RFP-P18-09", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": ["RVM-19"],
     "response": "Single-point-failure tolerance for electronics: the DBF-1.2 PPU estimate carries N+1 / redundant "
                 "electronics (RVM-19 {{T_RVM-19}}); the electronics FMEA / single-point-failure list at PDR-1 "
                 "verifies it.",
     "evidence": [ev(TRACE, "#/trace[rvm=RVM-19]")], "owner_input": []},
    {"id": "RFP-P18-10", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": ["RVM-04", "RVM-05"],
     "response": "P_bus (all power crossing the spacecraft-side DC boundary) at AIR 12 mN: {{AIR_REF}} W reference / "
                 "{{AIR_CONS}} W conservative, margins {{AIR_REF_M1500}} / {{AIR_CONS_M1500}} W to 1,500 W and "
                 "{{AIR_REF_M1350}} / {{AIR_CONS_M1350}} W to the internal 1,350 W allocation. Xe 25 mN is held "
                 "inside the 1,450 W design ceiling by its discharge allocation. Under the P6 conservative "
                 "non-discharge corner the AIR bus is {{AIR_CORNER}} W (< 1,500 W, > 1,350 W; VR-PWR-01). Trace "
                 "RVM-04 {{T_RVM-04}}. Measured on EM / QM.",
     "evidence": [ev(DBF, "#/power_rollup"), ev(POWER, "whole file")], "owner_input": []},
    {"id": "RFP-P18-11", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": ["RVM-06", "RVM-07"],
     "response": "{{MASS_WORDING}} Roll-up (A9.41): non-harness {{NONH}} kg + harness {{HAR}} kg = nominal dry "
                 "{{DRY}} kg; + 10 % system margin = {{DRY10}} kg; + {{XE_REF}} kg Xe reference = {{WET}} kg wet. "
                 "Trace RVM-06 {{T_RVM-06}}; the internal 34 kg nominal-dry target is not met (RVM-07 {{T_RVM-07}}). "
                 "Confirmed by CBE, quotation and EM mass measurement; any growth needs a DCR.",
     "evidence": [ev(DBF, "#/mass_rollup"), ev(RISKS, "#/risks[id=MR-DCR001-01]"), ev(A941, "whole file")],
     "owner_input": []},
    {"id": "RFP-P18-12", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": ["RVM-20"],
     "response": "MIL-STD-1553B remote terminal to the onboard computer for configuration and high-rate data logging, "
                 "discrete lines for thruster operation, drivers inside the propulsion system. Allocated to AL-09 "
                 "controls / FDIR ({{AL09}} kg, owner allocation; RVM-20 {{T_RVM-20}}). Interface ICD at PDR-2; "
                 "verified by inspection and a representative-bus test.",
     "evidence": [ev(TRACE, "#/trace[rvm=RVM-20]")], "owner_input": []},
    {"id": "RFP-P19-01", "status": "NOT_YET_DEMONSTRATED", "dbf_trace": ["RVM-12 / RVM-13"],
     "response": "Design basis: mission life >= {{LIFE_H}} h and > {{FIRING_H}} h cumulative firing (frozen engineering "
                 "constraints). DBF-1.2 trace RVM-12 / RVM-13: {{T_RVM-12 / RVM-13}}: life is verified by wear / "
                 "endurance tests (AO / lifetime register); no admissible life analysis exists.",
     "evidence": [ev(CONS, "#/constraints/mission_life_h"), ev(AO, "whole file")], "owner_input": []},
    {"id": "RFP-P19-02", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": ["RVM-16"],
     "response": "Space-qualified materials and processes for the QM. Frozen selections (DBF-1.1 inherited): anode / "
                 "gas distributor INCONEL 600 (backup 601), ICP collector INCONEL 600 / 601, channel wall BN-SiO2 "
                 "(backup BN), ICP vessel borosilicate. Materials state {{MAT_STATE}}: no gate fails on evidence; the "
                 "open gates close by coupon / EM tests.",
     "evidence": [ev(DBF, "#/items[id=DBF1-MAT-01]"), ev(MAT, "#/closure_state")], "owner_input": []},
    {"id": "RFP-P19-03", "status": "COMPLY", "dbf_trace": [],
     "response": "Subsystems (owner ruling A9.27, composition only): a. Air intake and compressor storage (AL-01 "
                 "intake, AL-02 compressor, AL-03 plenum / feed; plus the separate Xe branch AL-08); b. Power supply "
                 "electronics (AL-07 PPU, AL-06 RF generator / match, AL-09 controls / 1553B); c. Thruster (AL-04 "
                 "Hall head + magnets, AL-05 ICP neutralizer). No performance or qualification claim.",
     "evidence": [ev(DBF, "#/mass_rollup/lines_mev_kg"), ev(A927, "#/owner_decision_summary")], "owner_input": []},
    {"id": "RFP-P19-04", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": ["RVM-21", "RVM-17"],
     "response": "QM ENTEST qualification (launch vibration / shock, AO erosion, radiation, thermal, ThermoVac, 3-year "
                 "VLEO life) at Milestone 5 against the specification issued at PDR (no numeric levels assumed, "
                 "DISC-09). Thermal: cathodeless topology frozen (DBF1-TH-01, 50 K margin rule); thermal closure "
                 "state {{THERM_STATE}} (RVM-17 {{T_RVM-17}}); the co-located RF match exceeds its ceiling in the hot "
                 "cases and is under DCR-DBF1-003 ({{DCR3_STATUS}}).",
     "evidence": [ev(THERM, "#/closure"), ev(DBF, "#/items[id=DBF1-TH-01]")], "owner_input": []},
    {"id": "RFP-P19-05", "status": "OWNER_INPUT_REQUIRED", "dbf_trace": [],
     "response": "A detailed plan for >= 75 % project IC (thruster > 80 %, intake > 80 %, compressor and storage > 60 %, "
                 "PSE > 70 %) is required; no supplier is selected, so no IC percentage is stated.",
     "evidence": [ev(CONS, "#/constraints/ic_subsystem_min")], "owner_input": ["OIR-IC-01", "OIR-IC-02", "OIR-IC-03"]},
    {"id": "RFP-P19-06", "status": "PARTIAL", "dbf_trace": ["RVM-16"],
     "response": "a) AO-beam coating / erosion-yield tests: planned (AO / lifetime register, witness coupons; materials "
                 "gates EM_VERIFICATION_REQUIRED); facility / fluence: owner. b) Rarefied-gas source with prescribed "
                 "mg/s and velocity for intake tests: no facility record (owner). c) EM / QM force, variable intake "
                 "mg/s, Isp and total-system efficiency: planned (thrust stand INS-01, time-resolved bus-power "
                 "metering). d) Test plan reviewed by the expert committee: accepted.",
     "evidence": [ev(AO, "whole file"), ev(INS, "#/instruments")], "owner_input": ["OIR-FAC-02", "OIR-FAC-03", "OIR-FAC-04"]},
    {"id": "RFP-P20-01", "status": "OWNER_INPUT_REQUIRED", "dbf_trace": [],
     "response": "4.2: deliverables accepted against the Para 2 parameters (DBF-1.2 requirement trace). 4.3: ISO "
                 "certification is an owner fact. ATP prepared from the Para 2 parameters after DDR / CDR.",
     "evidence": [ev(TRACE, "#/trace")], "owner_input": ["OIR-ORG-01"]},
    {"id": "RFP-P20-02", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": [],
     "response": "Only ground demonstration in a simulated environment and space-qualification testing; no flight "
                 "trial. Evidence order: Ar (engineering only) -> N2 -> O2-bearing (NO_ATOMIC_O) -> atomic-O life "
                 "programme.",
     "evidence": [ev(PIVOT, "whole file")], "owner_input": []},
    {"id": "RFP-P20-03", "status": "NOT_YET_DEMONSTRATED", "dbf_trace": [],
     "response": "Acknowledged. The partial-success criterion (EM ABEP system and a qualified thruster on O and N2 at "
                 "Milestone 4) depends on evidence that does not yet exist: measured air-Hall performance "
                 "(VR-HALL-01), ICP AIR closure ({{ICP_STATE}}) and atomic-O evidence. Principal schedule risk.",
     "evidence": [ev(RISKS, "#/risks[id=VR-HALL-01]"), ev(ICP, "#/closure")], "owner_input": []},
    {"id": "RFP-P20-04", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": [],
     "response": "Milestone 1 (PDR-1, T0+09 months, 15 %): DBF-1.2 is the preliminary design entering PDR-1; PDR-1 "
                 "closes the early confirmations (PPU CBE VR-PPU-01, Xe tank quotation VR-XE-01, AL-09 / AL-10 CBEs, "
                 "routed harness, electronics FMEA), BoM and test-facility document.",
     "evidence": [ev(RISKS, "#/risks")], "owner_input": []},
    {"id": "RFP-P20-05", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": [],
     "response": "Milestone 2 (PDR-2, T0+12 months, 10 %): PSE software preliminary design incl. start-up sequencing "
                 "and FDIR, telemetry (MATLAB and C), 1553B / discrete ICD, test-facility readiness. The RFP names the "
                 "deliverable 'approved GNC design document and codes' (verbatim; owner to confirm the reading).",
     "evidence": [], "owner_input": []},
    {"id": "RFP-P20-06", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": [],
     "response": "Milestone 3 (CDR, T0+20 months, 20 %): EM thruster (H-1 + ICP) and EM PSE demonstrated with STORAGE "
                 "input (stored N2 / Xe), not intake: measured H-1 thrust / feed map, Xe 25 mN power (VR-XE-02), ICP "
                 "coupling, measured B(z).",
     "evidence": [ev(RISKS, "#/risks[id=VR-XE-02]")], "owner_input": []},
    {"id": "RFP-P21-01", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": [],
     "response": "Milestone 4 (T0+24 months, 35 %): EM intake with compressor and storage (VR-CMP-01..04, "
                 "VR-FEED-01); QM PSE and thruster testing. Carries the RFP-P20-03 exit-criterion risk.",
     "evidence": [ev(RISKS, "#/risks")], "owner_input": []},
    {"id": "RFP-P21-02", "status": "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "dbf_trace": ["RVM-21"],
     "response": "Milestone 5 (T0+36 months, 20 %): QM intake, total QM integration, ENTEST qualification "
                 "(VR-EMQM-01), documentation, delivery and closure.",
     "evidence": [ev(RISKS, "#/risks[id=VR-EMQM-01]")], "owner_input": []},
    {"id": "RFP-P21-03", "status": "OWNER_INPUT_REQUIRED", "dbf_trace": [],
     "response": "Acknowledged: no waiver is sought for Part IV(B). Its items (financial, heritage, infrastructure, "
                 "manpower, academia) are organisational facts the repository does not hold.",
     "evidence": [], "owner_input": ["OIR-ORG-02", "OIR-ORG-03", "OIR-ORG-06"]},
    {"id": "RFP-P27-01", "status": "OWNER_INPUT_REQUIRED", "dbf_trace": [],
     "response": "UHV propulsion test facility and low-thrust measurement setup (in-house / consortium / "
                 "sub-contract): owner facts. The repository defines the instrumentation requirements (INS-01).",
     "evidence": [ev(INS, "#/instruments")], "owner_input": ["OIR-FAC-01", "OIR-FAC-02"]},
    {"id": "RFP-P27-02", "status": "OWNER_INPUT_REQUIRED", "dbf_trace": [],
     "response": "Collaboration with academia / research institute on material compatibility with nascent O (LoI / "
                 "MoU): owner. The materials gates and AO programme define the work share.",
     "evidence": [ev(MAT, "#/gates")], "owner_input": ["OIR-ORG-03"]},
    {"id": "RFP-P30-01", "status": "OWNER_INPUT_REQUIRED", "dbf_trace": [],
     "response": "Micro-newton-level thrust measurement (scored in-house / consortium / sub-contract). The planned "
                 "stand INS-01 targets 12-25 mN; it is not evidence of micro-newton capability (DISC-10).",
     "evidence": [ev(INS, "#/instruments")], "owner_input": ["OIR-FAC-02"]},
]
