//! Selected-flight architecture mass accounting (SC-WP-07; programme_v3_1 `abep-subsystems::mass`).
//!
//! Existing physics ported under preregistered parity contracts (`docs/rust_migration/contracts/`):
//!
//! * [`rules`]: K-MASS-RULES, the fail-closed roll-up / margin / harness / closure rules (mass / power v3 builder) and
//!   the A9.26 bid-margin rules (10 % system margin).
//! * [`v5`]: the `mass_power_a9_v5` record (A9.26 bid mass policy), regenerated byte for byte from its pinned inputs;
//!   the AL-07 value-status view (A9.28: 6.0 kg PROVISIONAL_LEGACY_DERIVED_ANALOG_INPUT, AFI-02-RA1 open) and the
//!   fail-closed mass gates (mass compliance INCOMPLETE_EVIDENCE / NOT_YET_CLOSED, never PASS).
//! * [`wet_mass`]: the F7 / F8 wet-mass objective (NOT_EVALUATED without a CBE or measured line mass).
//! * [`xe`]: the Xe sensitivity kernels of the Xe accounting v3 builder (LOADED 2 / 5 / 10 kg planning cases, reserve /
//!   residual / ignition / ground-supply booking, ledger evaluation).
//!
//! The rules take JSON-shaped Python values ([`abep_types::pyjson::Value`]) and mirror CPython 3.11 semantics, so that
//! the parity observables (key order, int / float types, every float bit, refusal messages) are exact. C1 is
//! GROUND_REFERENCE_ONLY: its history is carried as data of the pinned records and never enters a flight roll-up.

pub mod eval;
pub mod py;
pub mod pyfmt;
pub mod rules;
pub mod v5;
pub mod wet_mass;
pub mod xe;
