# NP-HALL-PARAMETRIC-ENVELOPE addendum 01 AIR-family driver (A9.33 Q2). PARAMETRIC / NOT_VALIDATED.
# Runs the frozen AIR case file (cases/h1_parametric_envelope_air_cases_v1.json, generated by the Rust tool abep-air-cases)
# through hallthruster_bridge/air_bridge_lib.jl run_case_air in vacuum mode and records raw observables only: no status,
# threshold or verdict (the Rust ingestion applies the addendum's run-status rule).
#   julia --project=hallthruster_bridge docs/rust_migration/new_physics/NP-HALL-PARAMETRIC-ENVELOPE/driver/h1_envelope_air_driver.jl \
#         <out.jsonl> <shard> <nshards> [composition id | ALL]
# LAUNCH GATE: refuses to run without launch_manifest_air_v1.json, which the Rust tool writes only when the AIR reaction set
# (hallthruster_bridge/propellants_air/AIR_PINNED.toml) is COMPLETE_FOR_PARAMETRIC_ENVELOPE. Then it refuses any mismatch of
# the HallThruster.jl pin, the addendum lock, the case file, this driver, both Julia libraries, AIR_PINNED.toml, the AIR
# configuration, the validity file or any configured rate file. Resumable (skips keys already in out.jsonl).
include(joinpath(@__DIR__, "..", "..", "..", "..", "..", "hallthruster_bridge", "air_bridge_lib.jl"))
using SHA
using Dates
rev = check_pin()
sha(p) = bytes2hex(open(sha256, p))
const NPDIR = normpath(joinpath(@__DIR__, ".."))
const REPO = normpath(joinpath(NPDIR, "..", "..", "..", ".."))
const BRIDGE = joinpath(REPO, "hallthruster_bridge")
lm_path = joinpath(NPDIR, "launch_manifest_air_v1.json")
isfile(lm_path) || error("AIR launch gate closed: no launch_manifest_air_v1.json (the AIR reaction set is not COMPLETE_FOR_PARAMETRIC_ENVELOPE)")
man = JSON3.read(read(lm_path, String))
lock_sha = sha(joinpath(NPDIR, "addendum_01_lock.json"))
lock_sha == man.addendum_lock_sha256 || error("addendum lock does not match the AIR launch manifest")
lock = JSON3.read(read(joinpath(NPDIR, "addendum_01_lock.json"), String))
for (f, h) in pairs(lock.files)
    sha(joinpath(NPDIR, String(f))) == h || error("addendum lock mismatch: $(f)")
end
driver_sha = sha(@__FILE__)
driver_sha == man.driver_sha256 || error("driver does not match the AIR launch manifest")
sha(joinpath(BRIDGE, "air_bridge_lib.jl")) == man.air_bridge_lib_sha256 || error("air_bridge_lib.jl changed")
sha(joinpath(BRIDGE, "bridge_lib.jl")) == man.bridge_lib_sha256 || error("bridge_lib.jl changed")
air_pinned_sha = sha(joinpath(BRIDGE, "propellants_air", "AIR_PINNED.toml"))
air_pinned_sha == man.air_pinned_sha256 || error("AIR_PINNED.toml changed since the launch manifest")
config_sha = sha(joinpath(BRIDGE, String(man.air_config)))
config_sha == man.air_config_sha256 || error("AIR configuration changed since the launch manifest")
sha(joinpath(BRIDGE, "propellants_air", "rate_validity.toml")) == man.rate_validity_sha256 || error("rate_validity.toml changed")
for (f, h) in pairs(man.rate_files)
    sha(joinpath(BRIDGE, "propellants_air", String(f))) == h || error("rate file $(f) changed")
end
cases_path = joinpath(REPO, String(man.cases))
cases_sha = sha(cases_path)
cases_sha == man.cases_sha256 || error("AIR case file does not match the launch manifest")
doc = JSON3.read(read(cases_path, String))
doc.addendum_lock_sha256 == lock_sha || error("AIR case file was generated under another addendum lock")

out_path = ARGS[1]
shard = parse(Int, ARGS[2])
nshards = parse(Int, ARGS[3])
corner = length(ARGS) >= 4 ? ARGS[4] : "ALL"
0 <= shard < nshards || error("shard $(shard) outside 0..$(nshards - 1)")
corner == "ALL" || corner in [String(p.id) for p in doc.composition_points] || error("unknown composition $(corner)")
done = Set{String}()
isfile(out_path) && for l in eachline(out_path); isempty(strip(l)) || push!(done, String(JSON3.read(l).key)); end
threads = Dict(k => get(ENV, k, nothing) for k in ("JULIA_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS", "OMP_NUM_THREADS"))
const KEEP = ("retcode", "converged", "finite", "t_end_s", "sustained", "quasi_steady", "thrust_N", "discharge_current_A",
              "discharge_power_W", "ion_current_A", "anode_eff", "mass_eff", "current_eff", "voltage_eff", "divergence_eff",
              "Te_max_eV", "ne_max_m3", "Id_rms_rel", "Id_pp_rel", "Id_f_dominant_Hz", "Id_min_A", "Id_max_A", "B_max_T", "B_scale",
              "B_peak_minus_exit_m", "ion_species_fraction_atomic", "ion_exit_flux_fraction_by_gas", "wall_ion_basis",
              "chemistry_unresolved_rate_files", "chemistry_per_reaction", "chemistry_extrapolated_fraction_max",
              "chemistry_limiting_rate_file", "chemistry_trustworthy", "audit_domain_fraction_max", "audit_domain_limiting_rate_file",
              "air_in_domain", "feed_used", "transport", "error")
for (i, c) in enumerate(doc.cases)
    (i - 1) % nshards == shard || continue
    (corner == "ALL" || c.composition_id == corner) || continue
    key = String(c.key)
    key in done && continue
    rec = Dict{String,Any}("key" => key, "family" => String(c.family), "composition_id" => String(c.composition_id),
                           "case_sha256" => String(c.case_sha256), "cases_file_sha256" => cases_sha,
                           "addendum_lock_sha256" => lock_sha, "driver_sha256" => driver_sha,
                           "air_label" => String(man.air_label), "air_pinned_sha256" => air_pinned_sha,
                           "air_config_sha256" => config_sha, "hallthruster_commit" => rev,
                           "hallthruster_version" => string(pkgversion(het)), "julia_version" => string(VERSION),
                           "threads_blas" => threads, "host" => Libc.gethostname(), "utc_start" => string(Dates.now(Dates.UTC)),
                           "layer" => "PARAMETRIC / NOT_VALIDATED")
    t0 = time()
    try
        LAST_SOL[] = nothing
        r = run_case_air(c)
        for k in KEEP
            haskey(r, k) && (rec[k] = r[k])
        end
        haskey(rec, "finite") || (rec["finite"] = false)
    catch err
        rec["retcode"] = "error"; rec["error"] = sprint(showerror, err); rec["finite"] = false
    end
    rec["wall_s"] = time() - t0
    open(out_path, "a") do io
        JSON3.write(io, rec); println(io)
    end
    println(key, "  ", get(rec, "retcode", "?"))
    flush(stdout)
end
