# NP-HALL-PARAMETRIC-ENVELOPE v1 driver (A9.32; prereg_v1.json, locked by prereg_lock_v1.json). PARAMETRIC / NOT_VALIDATED.
# Runs the frozen H-1 case file (cases/h1_parametric_envelope_cases_v1.json, generated by the Rust tool
# abep-h1-envelope-cases) through hallthruster_bridge/bridge_lib.jl run_case in vacuum mode and records raw observables only:
# no status, no threshold, no verdict (the Rust ingestion applies the preregistered run-status rule).
#   julia --project=hallthruster_bridge docs/rust_migration/new_physics/NP-HALL-PARAMETRIC-ENVELOPE/driver/h1_envelope_driver.jl \
#         <out.jsonl> <shard> <nshards> [family: XE | N2_PROXY | ALL]
# Refuses to run unless the HallThruster.jl pin (check_pin), the preregistration lock, every file it locks, every input pinned
# by the preregistration, the case file and this driver match launch_manifest_v1.json. Resumable (skips keys already in
# out.jsonl). The log prints run keys and return codes only.
include(joinpath(@__DIR__, "..", "..", "..", "..", "..", "hallthruster_bridge", "bridge_lib.jl"))
using SHA
using Dates
rev = check_pin()
sha(p) = bytes2hex(open(sha256, p))
const NPDIR = normpath(joinpath(@__DIR__, ".."))
const REPO = normpath(joinpath(NPDIR, "..", "..", "..", ".."))
man = JSON3.read(read(joinpath(NPDIR, "launch_manifest_v1.json"), String))
lock_sha = sha(joinpath(NPDIR, "prereg_lock_v1.json"))
lock_sha == man.prereg_lock_sha256 || error("preregistration lock does not match the launch manifest")
lock = JSON3.read(read(joinpath(NPDIR, "prereg_lock_v1.json"), String))
for (f, h) in pairs(lock.files)
    sha(joinpath(NPDIR, String(f))) == h || error("preregistration lock mismatch: $(f)")
end
prereg = JSON3.read(read(joinpath(NPDIR, "prereg_v1.json"), String))
for (f, h) in pairs(prereg.pinned_inputs)
    sha(joinpath(REPO, String(f))) == h || error("pinned input changed: $(f)")
end
driver_sha = sha(@__FILE__)
driver_sha == man.driver_sha256 || error("driver does not match the launch manifest")
cases_path = joinpath(REPO, String(man.cases))
cases_sha = sha(cases_path)
cases_sha == man.cases_sha256 || error("case file does not match the launch manifest")
doc = JSON3.read(read(cases_path, String))
doc.prereg_lock_sha256 == lock_sha || error("case file was generated under another preregistration lock")

out_path = ARGS[1]
shard = parse(Int, ARGS[2])
nshards = parse(Int, ARGS[3])
family = length(ARGS) >= 4 ? ARGS[4] : "ALL"
family in ("XE", "N2_PROXY", "ALL") || error("family must be XE, N2_PROXY or ALL")
0 <= shard < nshards || error("shard $(shard) outside 0..$(nshards - 1)")
done = Set{String}()
isfile(out_path) && for l in eachline(out_path); isempty(strip(l)) || push!(done, String(JSON3.read(l).key)); end
threads = Dict(k => get(ENV, k, nothing) for k in ("JULIA_NUM_THREADS", "OPENBLAS_NUM_THREADS", "MKL_NUM_THREADS", "OMP_NUM_THREADS"))
const KEEP = ("retcode", "converged", "t_end_s", "sustained", "quasi_steady", "thrust_N", "discharge_current_A", "discharge_power_W",
              "ion_current_A", "anode_eff", "mass_eff", "current_eff", "voltage_eff", "divergence_eff", "Te_max_eV", "ne_max_m3",
              "Id_rms_rel", "Id_pp_rel", "Id_f_dominant_Hz", "Id_min_A", "Id_max_A", "B_max_T", "B_scale", "B_peak_minus_exit_m",
              "ion_species_fraction_atomic", "wall_ion_basis", "chemistry_basis", "chemistry_unresolved_rate_files",
              "chemistry_per_reaction", "chemistry_extrapolated_fraction_max", "chemistry_limiting_rate_file",
              "chemistry_trustworthy", "transport", "error")
for (i, c) in enumerate(doc.cases)
    (i - 1) % nshards == shard || continue
    (family == "ALL" || c.family == family) || continue
    key = String(c.key)
    key in done && continue
    rec = Dict{String,Any}("key" => key, "family" => String(c.family), "case_sha256" => String(c.case_sha256),
                           "cases_file_sha256" => cases_sha, "prereg_lock_sha256" => lock_sha, "driver_sha256" => driver_sha,
                           "hallthruster_commit" => rev, "hallthruster_version" => string(pkgversion(het)),
                           "julia_version" => string(VERSION), "threads_blas" => threads, "host" => Libc.gethostname(),
                           "utc_start" => string(Dates.now(Dates.UTC)), "layer" => "PARAMETRIC / NOT_VALIDATED")
    t0 = time()
    try
        LAST_SOL[] = nothing
        r = run_case(c, "vacuum")
        for k in KEEP
            haskey(r, k) && (rec[k] = r[k])
        end
        sol = LAST_SOL[]
        if r["retcode"] == "success" && !isnothing(sol)
            Id_t = het.discharge_current(sol)
            rec["finite"] = all(isfinite, Id_t) && isfinite(r["thrust_N"]) && isfinite(r["discharge_current_A"])
        else
            rec["finite"] = false
        end
    catch err
        rec["retcode"] = "error"; rec["error"] = sprint(showerror, err); rec["finite"] = false
    end
    rec["wall_s"] = time() - t0
    open(out_path, "a") do io
        JSON3.write(io, rec); println(io)
    end
    println(key, "  ", get(rec, "retcode", "?"))
    flush(stdout)
end
