"""Build the generated parts of the bid technical package (DRAFT_FOR_OWNER_REVIEW).

Generates, from compliance_data.py and the evidence AT THE BID FREEZE COMMIT bbc480c (read with `git show`, never from the
working tree):
  compliance_matrix_v1.json   machine-readable clause-by-clause matrix + gate statuses carried verbatim from bbc480c
  01_COMPLIANCE_MATRIX.md     the human-readable matrix
  docx/*.docx                 a Word rendering of every package Markdown file (only when python-docx is importable)

Usage: python docs/bid/package/build_package.py [--check] [--no-docx]
  --check    regenerate the JSON + Markdown in memory and fail if the committed files differ (docx not compared:
             python-docx zip timestamps are not deterministic)
Nothing here is submitted anywhere; the repository never submits a bid.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
sys.path.insert(0, HERE)
import compliance_data as cd  # noqa: E402

REG_PATH = "docs/requirements/rfp_official/rfp_registration_v1.json"
F9_PATH = "docs/architecture/freeze_candidate/architecture_freeze_candidate_v1.json"
MD_ORDER = ["README.md", "01_COMPLIANCE_MATRIX.md", "02_TECHNICAL_APPROACH.md", "03_DEVELOPMENT_AND_TEST_PLAN.md",
            "04_RISK_REGISTER.md", "05_PROGRAMMATIC_SECTIONS.md"]


def git_show(path: str) -> str:
    return subprocess.run(["git", "show", f"{cd.FREEZE_COMMIT}:{path}"], cwd=ROOT, check=True,
                          capture_output=True, text=True).stdout


def build_json() -> dict:
    reg = json.loads(git_show(REG_PATH))
    f9 = json.loads(git_show(F9_PATH))
    clauses = []
    for c in reg["clauses"]:
        d = cd.CLAUSES[c["id"]]
        assert d["status"] in cd.STATUSES, (c["id"], d["status"])
        clauses.append({
            "id": c["id"], "page": c["page"], "section": c["section"], "rfp_text_verbatim": c["text"],
            "status": d["status"], "response": d["response"], "rvm_rows": d.get("rvm", []),
            "evidence_at_freeze": d["evidence"], "owner_input": d.get("owner_input", []),
        })
    extra = sorted(set(cd.CLAUSES) - {c["id"] for c in reg["clauses"]})
    assert not extra, f"compliance data for unregistered clauses: {extra}"
    counts = {s: sum(1 for c in clauses if c["status"] == s) for s in cd.STATUSES}
    gates = [{"id": g["id"], "gate": g["gate"], "status_at_freeze": g["current_status"],
              "evidence_sufficient_for_freeze": g["evidence_sufficient_for_freeze"],
              "source": {"path": F9_PATH, "locator": f"#/architecture_gates[id={g['id']}]"}}
             for g in f9["architecture_gates"]]
    gates += [{"id": g["id"], "gate": g["gate"], "status_at_freeze": g["current_status"],
               "evidence_sufficient_for_freeze": g["evidence_sufficient_for_freeze"],
               "criteria": g.get("criteria"),
               "source": {"path": F9_PATH, "locator": f"#/pre_lock1_gates[id={g['id']}]"}}
              for g in f9["pre_lock1_gates"]]
    return {
        "schema": "bid_compliance_matrix_v1",
        "status": "DRAFT_FOR_OWNER_REVIEW",
        "tender": "2026_DRDO_788433_1",
        "rfp": "DTDF/06/13516/DSP/ABEP/X/L/M/01",
        "bidder": "Vyovrinda Aerospace",
        "technical_source_commit": cd.FREEZE_COMMIT,
        "freeze_record": "docs/bid/bid_technical_baseline.json",
        "generated_by": "docs/bid/package/build_package.py (data: docs/bid/package/compliance_data.py)",
        "rule": "every evidence path is a file at the freeze commit; no clause is stated compliant beyond what that "
                "evidence shows; nothing in this file is a test result, PASS or GO",
        "status_vocabulary": cd.STATUS_DEFINITIONS,
        "status_counts": counts,
        "clauses": clauses,
        "gates_at_freeze": gates,
        "owner_inputs": cd.OWNER_INPUTS,
        "rfp_pages_not_screened": reg["page_coverage"]["pages_not_screened"],
    }


def md_escape(s: str) -> str:
    return s.replace("|", "\\|").replace("\n", " ")


def build_md(j: dict) -> str:
    L = ["# 01 - Clause-by-clause compliance matrix", "",
         "**Status: DRAFT_FOR_OWNER_REVIEW.** Generated by `docs/bid/package/build_package.py` from "
         "`docs/bid/package/compliance_data.py` and the registered RFP clauses at the bid freeze commit "
         f"`{cd.FREEZE_SHORT}` (`{cd.FREEZE_COMMIT}`); do not edit by hand. Machine-readable: "
         "`docs/bid/package/compliance_matrix_v1.json`.", "",
         f"Tender {j['tender']}, RFP {j['rfp']}. Clause text is the repository's verbatim transcription "
         f"(`{REG_PATH}`, 37 clauses, pages 16-21, 27, 30). Every evidence path below is a file at `{cd.FREEZE_SHORT}`; "
         "read it with `git show bbc480c:<path>`. Locators are JSON pointers (with `[key=value]` list selection) or "
         "section names.", "",
         "Statuses never claim more than the evidence shows. At the freeze no RVM row of the flight configuration is "
         "PASS (27 NOT_EVALUATED, 3 INCOMPLETE_EVIDENCE), the Hall credible transport set is empty and every absolute "
         "0-D Hall result is withdrawn; this matrix quotes none of them.", "",
         "## Status vocabulary", "", "| status | meaning |", "|---|---|"]
    for s in cd.STATUSES:
        L.append(f"| {s} | {md_escape(cd.STATUS_DEFINITIONS[s])} |")
    L += ["", "## Status counts", "", "| status | clauses |", "|---|---|"]
    for s, n in j["status_counts"].items():
        L.append(f"| {s} | {n} |")
    L.append(f"| total | {sum(j['status_counts'].values())} |")
    L += ["", "## Summary table", "", "| clause | page | section | status | RVM rows |", "|---|---|---|---|---|"]
    for c in j["clauses"]:
        L.append(f"| {c['id']} | {c['page']} | {md_escape(c['section'])} | {c['status']} | "
                 f"{', '.join(c['rvm_rows']) or '-'} |")
    L += ["", "## Clause responses", ""]
    for c in j["clauses"]:
        L += [f"### {c['id']} (p. {c['page']}, {c['section']}) - {c['status']}", "",
              f"> RFP (verbatim transcription): {c['rfp_text_verbatim']}", "",
              f"**Response.** {c['response']}", "", "**Evidence at bbc480c:**", ""]
        for e in c["evidence_at_freeze"]:
            L.append(f"- `{e['path']}` {e['locator']}")
        if c["owner_input"]:
            L += ["", "**Owner input required:** " + ", ".join(c["owner_input"]) + " (checklist in README.md)."]
        L.append("")
    L += ["## Gate statuses at the freeze (carried verbatim)", "",
          f"Source: `{F9_PATH}` at `{cd.FREEZE_SHORT}` (`architecture_gates`, `pre_lock1_gates`). None of these gates is "
          "PASS or GO; none may be reported as such in the submission.", "",
          "| gate | what | status at bbc480c | sufficient for freeze |", "|---|---|---|---|"]
    for g in j["gates_at_freeze"]:
        st = g["status_at_freeze"]
        st = st if len(st) <= 160 else st[:157] + "..."
        L.append(f"| {g['id']} | {md_escape(g['gate'])} | {md_escape(st)} | {str(g['evidence_sufficient_for_freeze']).lower()} |")
    L += ["", "## RFP pages not screened", "", j["rfp_pages_not_screened"] +
          ". The owner must check those pages for mandatory formats, annexures and compliance statements (OIR-DOC-01).",
          ""]
    return "\n".join(L)


# ------------------------------------------------------------------ docx
_INLINE = re.compile(r"(\*\*[^*]+\*\*|`[^`]+`)")


def _add_inline(par, text):
    for part in _INLINE.split(text):
        if not part:
            continue
        if part.startswith("**") and part.endswith("**"):
            par.add_run(part[2:-2]).bold = True
        elif part.startswith("`") and part.endswith("`"):
            r = par.add_run(part[1:-1])
            r.font.name = "Consolas"
        else:
            par.add_run(part)


def md_to_docx(md_text: str, out_path: str) -> None:
    import docx  # python-docx
    doc = docx.Document()
    lines = md_text.split("\n")
    i = 0
    while i < len(lines):
        ln = lines[i]
        if ln.startswith("|") and i + 1 < len(lines) and re.match(r"^\|[-| :]+\|$", lines[i + 1]):
            rows = [ln]
            i += 2
            while i < len(lines) and lines[i].startswith("|"):
                rows.append(lines[i])
                i += 1
            cells = [[c.strip().replace("\\|", "|") for c in re.split(r"(?<!\\)\|", r.strip())[1:-1]] for r in rows]
            ncol = max(len(r) for r in cells)
            t = doc.add_table(rows=len(cells), cols=ncol)
            t.style = "Table Grid"
            for ri, r in enumerate(cells):
                for ci in range(ncol):
                    p = t.cell(ri, ci).paragraphs[0]
                    _add_inline(p, r[ci] if ci < len(r) else "")
                    if ri == 0:
                        for run in p.runs:
                            run.bold = True
            continue
        m = re.match(r"^(#{1,4})\s+(.*)$", ln)
        if m:
            doc.add_heading(m.group(2), level=len(m.group(1)))
        elif re.match(r"^\s*[-*]\s+", ln):
            _add_inline(doc.add_paragraph(style="List Bullet"), re.sub(r"^\s*[-*]\s+", "", ln))
        elif re.match(r"^\s*\d+\.\s+", ln):
            _add_inline(doc.add_paragraph(style="List Number"), re.sub(r"^\s*\d+\.\s+", "", ln))
        elif ln.startswith("> "):
            _add_inline(doc.add_paragraph(style="Intense Quote"), ln[2:])
        elif ln.strip() and not ln.startswith("<!--"):
            _add_inline(doc.add_paragraph(), ln)
        i += 1
    doc.save(out_path)


def main(argv):
    check = "--check" in argv
    j = build_json()
    js = json.dumps(j, indent=1, ensure_ascii=False) + "\n"
    md = build_md(j)
    targets = {os.path.join(HERE, "compliance_matrix_v1.json"): js, os.path.join(HERE, "01_COMPLIANCE_MATRIX.md"): md}
    if check:
        bad = [p for p, s in targets.items() if not os.path.exists(p) or open(p, encoding="utf-8").read() != s]
        if bad:
            print("STALE:", *bad)
            return 1
        print("OK")
        return 0
    for p, s in targets.items():
        with open(p, "w", encoding="utf-8") as f:
            f.write(s)
    if "--no-docx" not in argv:
        try:
            import docx  # noqa: F401
        except ImportError:
            print("python-docx not available: docx not generated")
            return 0
        os.makedirs(os.path.join(HERE, "docx"), exist_ok=True)
        for name in MD_ORDER:
            src = os.path.join(HERE, name)
            if os.path.exists(src):
                md_to_docx(open(src, encoding="utf-8").read(),
                           os.path.join(HERE, "docx", name[:-3] + ".docx"))
        print("docx generated")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
