"""Clause-by-clause compliance data for the bid technical package (DRAFT_FOR_OWNER_REVIEW).

Single source for compliance_matrix_v1.json and 01_COMPLIANCE_MATRIX.md (generated by build_package.py).
Every evidence path is a file AT THE BID FREEZE COMMIT bbc480c (docs/bid/bid_technical_baseline.json); the locator says where
inside it. Status vocabulary (STATUSES) is defined in STATUS_DEFINITIONS. Nothing here is a test result, a PASS or a GO.
"""

FREEZE_COMMIT = "bbc480cd6aacaa40c39eb459a056b942fe996b32"
FREEZE_SHORT = "bbc480c"

STATUSES = ["COMPLY", "COMPLY_PLANNED_WITH_EVIDENCE_PATH", "PARTIAL", "NOT_YET_DEMONSTRATED", "OWNER_INPUT_REQUIRED"]

STATUS_DEFINITIONS = {
    "COMPLY": "the offered design, as recorded at bbc480c, already meets the clause as written (a property of the offer; "
              "no test result is implied)",
    "COMPLY_PLANNED_WITH_EVIDENCE_PATH": "Vyovrinda proposes to comply; the repository at bbc480c holds the plan / "
                                         "verification path (file + locator); nothing is yet demonstrated",
    "PARTIAL": "some sub-items have a plan or evidence path at bbc480c, others have none yet (listed in the response)",
    "NOT_YET_DEMONSTRATED": "a technical performance requirement whose outcome depends on hardware / validation evidence "
                            "that does not exist at bbc480c; the programme has a path, but the package must not claim "
                            "the outcome",
    "OWNER_INPUT_REQUIRED": "the response depends on organisational, commercial or design-authority information that the "
                            "repository does not hold; the owner must supply it",
}

# Evidence paths (all exist at bbc480c; checked by tests/test_bid_package.py)
REG = "docs/requirements/rfp_official/rfp_registration_v1.json"
RVM = "docs/requirements/rvm_a9/rvm_a9_v1.json"
F9 = "docs/architecture/freeze_candidate/architecture_freeze_candidate_v1.json"
MP3 = "docs/budgets/mass_power_a9_v3/mass_power_a9_v3.json"
BPB = "docs/architecture_comparison/power_boundary_a9/bus_power_boundary_a9_v1.json"
H24 = "docs/hardware/h2/h2_4_ppu_bus/h2_4_ppu_bus_v1.json"
HWP = "docs/experiments/hall_icp/programme/hw_programme_a9_21_v1.json"
A9 = "docs/decisions/OD_HARDWARE_PIVOT_2026_09_29_A9_hall_downstream_rf_icp_neutralizer.json"
A919 = "docs/decisions/OD_2026_10_01_A9_19_architecture_xe_contingency_owner_decision.json"
A920 = "docs/decisions/OD_2026_10_01_A9_20_c1_ground_only_owner_decision.json"
A921 = "docs/decisions/OD_2026_10_02_A9_21_open_items_and_hardware_programme_owner_decisions.json"
A915 = "docs/decisions/OD_2026_10_01_A9_15_rfp_propellant_policy_owner_decision.json"
PIVOT = "docs/decisions/OD_HARDWARE_PIVOT_2026_09_27.json"
ENS = "hallthruster_bridge/ensemble/transport_ensemble_v0.json"
VAL = "hallthruster_bridge/validation/VALIDATION_RELEASE_v1.json"
RATE = "hallthruster_bridge/propellants/rate_validity.toml"
F1 = "docs/design_synthesis/f1_intake/f1_intake_synthesis_v1.json"
F2 = "docs/design_synthesis/f2_filter/f2_filter_stage_v1.json"
F3 = "docs/design_synthesis/f3_compressor/f3_compressor_synthesis_v1.json"
F4 = "docs/design_synthesis/f4_plenum/f4_plenum_feed_v1.json"
F6 = "docs/design_synthesis/f6_icp_geometry/f6_icp_geometry_v1.json"
F78 = "docs/design_synthesis/f7_f8_optimizer/f7_f8_optimizer_v1.json"
DRAG = "docs/design_synthesis/spacecraft_reference_drag/spacecraft_reference_drag_v1.json"
ATM = "abep_sim/data/atmosphere_msis21_v1.json"
ATM_DS = "abep_sim/data/atmosphere_msis21_orbit_v1_design_states.json"
AO = "docs/experiments/lifetime_ao/ao_lifetime_register_v5.json"
P1 = "docs/experiments/hall_icp/p1_icp_bench/p1_icp_bench_v1.json"
P2 = "docs/experiments/hall_icp/p2_impedance_map/p2_impedance_prep_v1.json"
P3 = "docs/experiments/hall_icp/p3_coupled_thermal/p3_coupled_thermal_v2.json"
P4 = "docs/experiments/hall_icp/p4_anode_materials/p4_anode_materials_v1.json"
INS = "docs/experiments/instrumentation/instrumentation_definition_v1.json"
HWDEF = "docs/experiments/hardware/hardware_requirements_v1.json"
OO2 = "docs/chemistry/o_o2/v0/channel_status_v0.json"
XE3 = "docs/budgets/xe_accounting_a9_v3/xe_accounting_a9_v3.json"
RFQ3 = "docs/procurement/rfq_a9_v3/rfq_a9_v3.json"
H1 = "docs/hardware/h1_freeze_candidate/h1_freeze_candidate_v1.json"
ICPICD = "docs/interfaces/icp_neutralizer/ICP_NEUTRALIZER_ICD.md"
FTREE = "docs/architecture_comparison/failure_tree/failure_trees_v1.json"
CLAUDE = "CLAUDE.md"
EVID = "docs/EVIDENCE.md"


def ev(path, locator):
    return {"path": path, "locator": locator}


CLAUSES = {
    "RFP-P16-01": dict(
        status="COMPLY_PLANNED_WITH_EVIDENCE_PATH",
        response="Vyovrinda proposes to develop, test and space-qualify an ABEP system for VLEO. The programme is "
                 "hardware-first (owner pivot 2026-09-27, A9.21 hardware order); the development and test plan "
                 "(03_DEVELOPMENT_AND_TEST_PLAN.md) maps it onto Milestones 1-5. No part of the system is yet "
                 "demonstrated: at bbc480c all 30 RVM rows of the flight configuration are NOT_EVALUATED (27) or "
                 "INCOMPLETE_EVIDENCE (3); none is PASS.",
        evidence=[ev(RVM, "#/status_counts/hall_icp_neutralizer"), ev(RVM, "#/rows[id=RVM-21]"),
                  ev(HWP, "whole file (A9.21 items 6-11)"), ev(PIVOT, "whole file (hardware-experiment pivot)")],
        rvm=["RVM-21", "RVM-08", "RVM-25"]),
    "RFP-P16-02": dict(
        status="COMPLY_PLANNED_WITH_EVIDENCE_PATH",
        response="The proposed architecture follows the RFP logical block diagram: Intake (F1) -> Filter (F2) -> "
                 "Compressor (F3) -> Gas Chamber / plenum (F4) -> Valve (atmospheric metering / isolation valve) -> "
                 "Thruster (H-1 Hall accelerator: ionization zone and acceleration zone in one channel) -> Thrust; "
                 "Xenon Gas -> Valve -> Thruster (separate Xe storage / flow path, AL-08). One element is ADDED "
                 "outside the diagram: a downstream 13.56 MHz RF-ICP electron source / neutralizer (owner decisions "
                 "A9, A9.19), which replaces a conventional hollow cathode. The upstream chain exists only as "
                 "design-synthesis screening at bbc480c (INVESTIGATION_HYPOTHESIS), not as a frozen design.",
        evidence=[ev(A919, "#/architecture"), ev(F9, "#/configuration"), ev(F1, "#/status"), ev(F2, "#/status"),
                  ev(F3, "#/status"), ev(F4, "#/status"), ev(MP3, "#/lines (AL-01..AL-10)"),
                  ev(RVM, "#/rows[id=RVM-29]")],
        rvm=["RVM-08", "RVM-10", "RVM-29"]),
    "RFP-P17-01": dict(
        status="COMPLY_PLANNED_WITH_EVIDENCE_PATH",
        response="The EM -> EM integration -> EM integration test -> QM (intake/compressor, power electronics, "
                 "thruster) -> QM integration test flow is adopted as the project's model philosophy and mapped onto "
                 "the milestones in 03_DEVELOPMENT_AND_TEST_PLAN.md section 3. No EM or QM hardware exists at bbc480c "
                 "(RVM-25: no verification artifact exists; T0 not set).",
        evidence=[ev(RVM, "#/rows[id=RVM-25]"), ev(REG, "#/clauses[id=RFP-P17-01]")],
        rvm=["RVM-25"]),
    "RFP-P17-02": dict(
        status="NOT_YET_DEMONSTRATED",
        response="Each listed critical technology is addressed, none is yet demonstrated: (1) thruster ionizing N2 "
                 "and nascent O: Hall transport validation gate 3 is FAIL at bbc480c (credible transport set empty; "
                 "P5-N2 v1 INCONCLUSIVE, permanent), the N2/N reaction set is complete only for its pre-registered "
                 "domain, and the O/O2 chemistry v0 tables are DRAFT and unused; (2) AO material compatibility: AO / "
                 "lifetime register v5 and the P4 anode-materials framework exist, every P4 gate is "
                 "INCOMPLETE_EVIDENCE, anode material OPEN; (3) intake and compressor: F1-F4 parametric screening "
                 "only; (4) test facility simulating the VLEO air mixture: no facility record exists in the "
                 "repository (OWNER_INPUT_REQUIRED, see 05_PROGRAMMATIC_SECTIONS.md).",
        evidence=[ev(CLAUDE, "section 'Gate status' (gate 3)"), ev(ENS, "#/members"), ev(VAL, "whole file"),
                  ev(OO2, "#/status"), ev(AO, "#/status"), ev(P4, "#/fixed_statuses"),
                  ev(F78, "#/findings[id=F78-02]"), ev(RVM, "#/rows[id=RVM-16]")],
        rvm=["RVM-09", "RVM-16", "RVM-08", "RVM-22"],
        owner_input=["OIR-FAC-03"]),
    "RFP-P17-03": dict(
        status="NOT_YET_DEMONSTRATED",
        response="Intake design is the subject of design-synthesis lane F1 (TPMC reduced-order intake model, "
                 "Maxwell + CLL wall models, frozen NRLMSIS 2.1 atmosphere). At bbc480c the coupled upstream screen "
                 "F7 is model-derived under PARAMETRIC_SENSITIVITY inputs: its nominal all-state delivered-flow "
                 "frontier is 0.0983 mg/s and no Pareto member reaches the lower end (0.38 mg/s) of the "
                 "characterization coverage at every state (F78-02; coverage, not a requirement). The post-freeze "
                 "caveat in bid_technical_baseline.json applies: robust upstream closure must not be claimed from "
                 "the bbc480c F7/F8 numbers (owner decision point R-03).",
        evidence=[ev(F1, "#/status"), ev(F78, "#/findings[id=F78-02]"), ev(F78, "#/findings[id=F8-01]"),
                  ev(ATM, "whole file (frozen NRLMSIS dataset metadata)"), ev(RVM, "#/rows[id=RVM-08]")],
        rvm=["RVM-08", "RVM-01"],
        owner_input=["OIR-TEC-01"]),
    "RFP-P17-04": dict(
        status="NOT_YET_DEMONSTRATED",
        response="Compressor and gas reservoir are covered by lanes F3 (compressor synthesis; Gaede / turbo "
                 "characteristic) and F4 (plenum / feed). Results are parametric screening (INVESTIGATION_HYPOTHESIS); "
                 "the compressor model mass on the nominal Pareto members is 4.19-10.91 kg against the 5.5 kg owner "
                 "allocation AL-02 (F78-07, model-derived, code-default coefficients; neither is a CBE). No "
                 "compressor hardware or test exists.",
        evidence=[ev(F3, "#/status"), ev(F4, "#/status"), ev(F78, "#/findings[id=F78-07]"),
                  ev(MP3, "#/lines/hall_icp_neutralizer[line=AL-02]")],
        rvm=["RVM-08"]),
    "RFP-P17-05": dict(
        status="NOT_YET_DEMONSTRATED",
        response="One H-1 Hall accelerator is proposed for atmospheric N2 / O-bearing propellant and Xe, with one "
                 "downstream RF-ICP neutralizer serving both supply modes (A9.19). Xe capability is retained as the "
                 "RFP's 'extra input system' (contingency / emergency supply mode; DISC-06 recorded). Not "
                 "demonstrated: no Hall transport closure is admitted (gate 3 FAIL), O2-bearing ground tests are "
                 "labelled NO_ATOMIC_O (atomic O only through the separate AO programme), and the Xe operation of "
                 "the ICP is not yet measured (ICP-XE-MODE campaign planned).",
        evidence=[ev(A919, "#/architecture"), ev(A919, "#/xenon_role"), ev(RVM, "#/rows[id=RVM-09]"),
                  ev(RVM, "#/rows[id=RVM-10]"), ev(RVM, "#/rows[id=RVM-28]"), ev(ENS, "#/members"),
                  ev(HWP, "#/steps[id=ICP-XE-MODE]"), ev(REG, "#/owner_rfp_fact_check")],
        rvm=["RVM-09", "RVM-10", "RVM-29", "RVM-15", "RVM-28"]),
    "RFP-P18-01": dict(
        status="COMPLY_PLANNED_WITH_EVIDENCE_PATH",
        response="A propulsion PPU taking power from the satellite bus and generating all ABEP supplies (Hall "
                 "discharge, per-coil magnet supplies, 13.56 MHz RF generator + matching, ICP collector / bias, "
                 "valve drivers, compressor drive, thermal control, housekeeping) is proposed. The bus-power "
                 "boundary (A9-02) and preliminary PPU options (H2-4: LCC resonant or ZVS full-bridge discharge "
                 "supply analogs) exist as PRELIMINARY_DRAFT_FOR_OWNER; the spacecraft-side input voltage is TBD "
                 "(A902-12) and every load value is TBD. No PPU hardware exists.",
        evidence=[ev(BPB, "#/slots"), ev(BPB, "#/bus_architecture"), ev(H24, "PPU architecture options (section 5)"),
                  ev(RVM, "#/rows[id=RVM-04]"), ev(RVM, "#/rows[id=RVM-20]")],
        rvm=["RVM-04", "RVM-20"],
        owner_input=["OIR-TEC-04"]),
    "RFP-P18-02": dict(
        status="OWNER_INPUT_REQUIRED",
        response="Accepted as a design requirement. The repository holds no redundancy design: RVM-19 is "
                 "NOT_EVALUATED (verification by FMEA / failure-tree analysis of the selected electronics; none "
                 "selected). The redundancy concept (which electronics and sensors are redundant, cold / hot, cross-"
                 "strapping) and its mass / power cost must be decided by the owner; mass closure is already "
                 "DOES_NOT_CLOSE at the MEV planning level (RFP-P18-11).",
        evidence=[ev(RVM, "#/rows[id=RVM-19]"), ev(MP3, "#/flight_rollup_vs_40kg")],
        rvm=["RVM-19"],
        owner_input=["OIR-TEC-02"]),
    "RFP-P18-03": dict(
        status="OWNER_INPUT_REQUIRED",
        response="a) Indigenous content > 60 %: no part is selected (RVM-18 NOT_EVALUATED; RFQ v3 is quotation-only), "
                 "so no IC figure can be stated from the repository; the IC plan skeleton is in "
                 "05_PROGRAMMATIC_SECTIONS.md. b) Vyovrinda will present the technical proposal to the technical "
                 "evaluation committee (owner to confirm presenters). c) Consortium: whether a consortium is proposed "
                 "and its documentary proof are owner items (DISC-03 recorded).",
        evidence=[ev(RVM, "#/rows[id=RVM-18]"), ev(RFQ3, "#/status"), ev(REG, "#/rvm_mapping")],
        rvm=["RVM-18"],
        owner_input=["OIR-IC-01", "OIR-IC-02", "OIR-ORG-04", "OIR-ORG-05"]),
    "RFP-P18-04": dict(
        status="NOT_YET_DEMONSTRATED",
        response="The design basis is the 180-230 km band on the frozen NRLMSIS 2.1 atmosphere dataset and its "
                 "orbit-resolved design states (model input, not compliance evidence). Operation across the band "
                 "(statewise thrust minus drag, AG-13) is NOT_EVALUATED: no admitted thrust and no host-spacecraft "
                 "drag ICD; inclination / LTAN are not specified by the RFP (A9.21 external inputs).",
        evidence=[ev(RVM, "#/rows[id=RVM-01]"), ev(ATM, "whole file"), ev(ATM_DS, "whole file"),
                  ev(F9, "#/architecture_gates[id=AG-13]"), ev(A921, "#/decisions/EXTERNAL_INPUTS")],
        rvm=["RVM-01"],
        owner_input=["OIR-TEC-03"]),
    "RFP-P18-05": dict(
        status="COMPLY_PLANNED_WITH_EVIDENCE_PATH",
        response="The intake is sized from air density as a function of solar activity and altitude: the frozen "
                 "NRLMSIS 2.1 dataset (hash-pinned) and the orbit-resolved design-state set feed the F1 intake "
                 "synthesis statewise. At bbc480c the F1-F8 results rest on five orbit-averaged design states; owner "
                 "decision OD3 requires the versioned design-state set (post-freeze caveat, owner decision R-03). "
                 "The intake specification is not frozen.",
        evidence=[ev(ATM, "whole file"), ev(ATM_DS, "whole file"), ev(F1, "#/status"),
                  ev(RVM, "#/rows[id=RVM-01]")],
        rvm=["RVM-01"],
        owner_input=["OIR-TEC-01"]),
    "RFP-P18-06": dict(
        status="NOT_YET_DEMONSTRATED",
        response="No thrust value is offered from analysis: no Hall transport closure is admitted (credible set "
                 "empty) and every absolute 0-D Hall result is withdrawn. Thrust is to be established by measurement: "
                 "the mandatory measured H-1 thrust / feed map (A9.21 item 11) drives the performance-derived feed "
                 "requirement AG-12 and the statewise drag check AG-13 (both NOT_EVALUATED). The RFP gives no split "
                 "between sustained and capability thrust; the owner reading (>= 12 mN sustained, 25 mN capability "
                 "inside P_bus < 1.5 kW) is recorded as DISC-07.",
        evidence=[ev(RVM, "#/rows[id=RVM-02]"), ev(RVM, "#/rows[id=RVM-03]"), ev(ENS, "#/members"),
                  ev(F9, "#/architecture_gates[id=AG-12]"), ev(F9, "#/architecture_gates[id=AG-13]"),
                  ev(HWP, "#/steps[id=H1-THRUST-FEED-MAP]")],
        rvm=["RVM-02", "RVM-03", "RVM-15"]),
    "RFP-P18-07": dict(
        status="COMPLY",
        response="The offered thruster is a Hall-effect thruster (one H-1 Hall accelerator; owner decision A9.19). "
                 "This states the thruster TYPE only: the architecture status is INVESTIGATION_HYPOTHESIS, H-1 is an "
                 "engineering freeze candidate (NOT_FROZEN), and no Hall performance is demonstrated (RVM-11 stays "
                 "NOT_EVALUATED until a frozen design baseline exists).",
        evidence=[ev(A919, "#/architecture/hall_accelerators"), ev(F9, "#/architecture_status"),
                  ev(H1, "#/status"), ev(RVM, "#/rows[id=RVM-11]")],
        rvm=["RVM-11", "RVM-28"]),
    "RFP-P18-08": dict(
        status="COMPLY_PLANNED_WITH_EVIDENCE_PATH",
        response="Two separate supply modes with separate storage are proposed: ambient air (primary; intake -> "
                 "compressor -> gas chamber / plenum) and Xe (contingency / emergency; dedicated Xe storage and flow "
                 "hardware, AL-08). The AL-08 Xe-hardware mass is a provisional planning floor pending quotations "
                 "(A9.21 AL08). No frozen feed-system design or demonstration exists (RVM-29).",
        evidence=[ev(A919, "#/architecture/propellant_supply_modes"), ev(MP3, "#/lines/hall_icp_neutralizer[line=AL-08]"),
                  ev(A921, "#/decisions/AL08"), ev(RVM, "#/rows[id=RVM-29]"), ev(XE3, "#/status")],
        rvm=["RVM-08", "RVM-10", "RVM-29"]),
    "RFP-P18-09": dict(
        status="OWNER_INPUT_REQUIRED",
        response="Accepted as a design requirement (single-point-failure tolerance for electronics). No electronics "
                 "design or FMEA exists at bbc480c (RVM-19 NOT_EVALUATED). The owner must decide the redundancy "
                 "concept before PDR-1; see RFP-P18-02.",
        evidence=[ev(RVM, "#/rows[id=RVM-19]")],
        rvm=["RVM-19"],
        owner_input=["OIR-TEC-02"]),
    "RFP-P18-10": dict(
        status="NOT_YET_DEMONSTRATED",
        response="Gate definition is frozen (P_bus,1ms,max < 1500 W at the spacecraft-DC propulsion boundary, steady "
                 "and every start-up step). Owner allocations: 1350 W internal design allocation, 300 W common "
                 "allocation incl. 50 W controls / thermal. The bus ledger is PARTIAL_BOUNDARY (compressor load TBD; "
                 "22 loads TBD; lower bound 0 W) and the gate is NOT_EVALUABLE in all 7 registered steps (AG-10).",
        evidence=[ev(BPB, "#/gates_and_allocations"), ev(RVM, "#/rows[id=RVM-04]"), ev(RVM, "#/rows[id=RVM-05]"),
                  ev(F9, "#/architecture_gates[id=AG-10]")],
        rvm=["RVM-03", "RVM-04", "RVM-05"]),
    "RFP-P18-11": dict(
        status="NOT_YET_DEMONSTRATED",
        response="Read as < 40 kg WET (conservative owner reading; DISC-02 recorded for DRDO clarification). At "
                 "bbc480c no CBE or measured mass exists. The single governing MEV-level planning roll-up (owner "
                 "allocations and owner-stated MEV planning floors, 20 % system margin, AL-09 controls without a "
                 "value) gives dry known 40.75 kg and wet known 42.75 / 45.75 / 50.75 kg for 2 / 5 / 10 kg loaded Xe: "
                 "DOES_NOT_CLOSE against < 40 kg in all three cases. The margin reading is not relaxed (MQ-10): "
                 "closure requires redesign / lighter qualified parts. This is a disclosed open item (risk R-07).",
        evidence=[ev(MP3, "#/flight_rollup_vs_40kg"), ev(MP3, "#/margin_convention"),
                  ev(RVM, "#/rows[id=RVM-06]"), ev(F9, "#/architecture_gates[id=AG-11]")],
        rvm=["RVM-06", "RVM-07"],
        owner_input=["OIR-TEC-05"]),
    "RFP-P18-12": dict(
        status="COMPLY_PLANNED_WITH_EVIDENCE_PATH",
        response="Vyovrinda proposes a MIL-STD-1553B remote-terminal interface to the satellite onboard computer for "
                 "configuration and high-rate data logging, discrete lines for thruster operation, and the hardware "
                 "drivers inside the propulsion system. No interface design, ICD or test exists in the repository "
                 "(RVM-20: NO VERIFICATION ARTIFACT EXISTS); the verification path is an ICD (inspection) plus a "
                 "1553B configuration / data-logging test with a representative bus and a discrete-line operation "
                 "demonstration. Interface design is a PDR-2 deliverable.",
        evidence=[ev(RVM, "#/rows[id=RVM-20]"), ev(BPB, "#/slots[slot=housekeeping_controls]")],
        rvm=["RVM-20", "RVM-14"],
        owner_input=["OIR-TEC-06"]),
    "RFP-P19-01": dict(
        status="NOT_YET_DEMONSTRATED",
        response="Design basis: mission life >= 26,280 h (conservative within the RFP's 'Approx 26000 hrs', "
                 "DISC-04) and > 15,000 h cumulative energized operation for the literal 'Ignition Time' (DISC-05). "
                 "No life analysis exists that is admissible: wall-erosion life needs an admitted Hall closure "
                 "(none); the AO / lifetime register defines pre-registered wear / endurance segments. Life is "
                 "NOT_EVALUATED (RVM-12, RVM-13).",
        evidence=[ev(RVM, "#/rows[id=RVM-12]"), ev(RVM, "#/rows[id=RVM-13]"), ev(AO, "#/requirements")],
        rvm=["RVM-12", "RVM-13"]),
    "RFP-P19-02": dict(
        status="COMPLY_PLANNED_WITH_EVIDENCE_PATH",
        response="Space-qualified materials and processes will be used for the QM. Material selection is open: "
                 "the final anode material is OPEN, 316L is REJECTED_AS_CURRENT_BASELINE, and every P4 screen is "
                 "INCOMPLETE_EVIDENCE (no AO / oxidation / sputter evidence on any candidate). The path is the P4 "
                 "anode-materials programme with LOCK-2 thresholds frozen before acceptance-bearing exposure.",
        evidence=[ev(P4, "#/status"), ev(F9, "#/a9_2_statuses"), ev(RVM, "#/rows[id=RVM-16]"),
                  ev(HWP, "#/steps[id=P4-ACCEPTANCE-EXPOSURE]")],
        rvm=["RVM-16", "RVM-21"]),
    "RFP-P19-03": dict(
        status="COMPLY_PLANNED_WITH_EVIDENCE_PATH",
        response="Subsystem breakdown adopted: a. Air intake and compressor storage (F1 intake, F2 filter, F3 "
                 "compressor, F4 gas chamber / plenum, valves; plus the separate Xe storage and valve path); b. Power "
                 "supply electronics (propulsion PPU incl. RF generator / matching, valve drivers, 1553B / discrete "
                 "interface); c. Thruster (H-1 Hall accelerator with magnetic circuit and anode / gas distributor, "
                 "and the downstream RF-ICP neutralizer). Mapping in 02_TECHNICAL_APPROACH.md section 3.",
        evidence=[ev(MP3, "#/lines"), ev(BPB, "#/slots"), ev(A919, "#/architecture"), ev(RVM, "#/rows[id=RVM-08]")],
        rvm=["RVM-08"]),
    "RFP-P19-04": dict(
        status="COMPLY_PLANNED_WITH_EVIDENCE_PATH",
        response="QM ENTEST qualification (launch vibration / shock for PSLV / SSLV or the DRDO-decided LV, AO "
                 "erosion, radiation, thermal, ThermoVac, 3-year VLEO life) is planned at Milestone 5 against the "
                 "ENTEST specification issued at PDR. No numeric levels are assumed (DISC-09). Thermal closure is "
                 "UNRESOLVED at bbc480c (coupled H-1 / ICP and anode); AO erosion via the AO programme.",
        evidence=[ev(RVM, "#/rows[id=RVM-21]"), ev(RVM, "#/rows[id=RVM-17]"), ev(P3, "#/status"),
                  ev(AO, "#/status")],
        rvm=["RVM-16", "RVM-21", "RVM-17", "RVM-27"]),
    "RFP-P19-05": dict(
        status="OWNER_INPUT_REQUIRED",
        response="A detailed IC plan for >= 75 % project IC (thruster > 80 %, intake > 80 %, compressor and storage "
                 "> 60 %, PSE > 70 %) is required. No part is selected and no supplier origin is recorded at bbc480c "
                 "(RVM-18 NOT_EVALUATED); the plan skeleton with the owner inputs is in 05_PROGRAMMATIC_SECTIONS.md "
                 "section 1. No IC percentage is stated by this package.",
        evidence=[ev(RVM, "#/rows[id=RVM-18]"), ev(RFQ3, "#/status")],
        rvm=["RVM-18"],
        owner_input=["OIR-IC-01", "OIR-IC-02", "OIR-IC-03"]),
    "RFP-P19-06": dict(
        status="PARTIAL",
        response="a) AO-beam coating / erosion-yield tests: planned through the AO / lifetime register (AOL-EX-01 / "
                 "-02, witness coupons) and P4; ground AO facility and fluence are owner items (AOL-OQ-05). b) "
                 "Rarefied-gas source with prescribed mg/s and velocity for intake erosion: NO facility or test "
                 "record exists in the repository (OWNER_INPUT_REQUIRED). c) EM / QM integrated force tests with "
                 "variable intake mg/s, Isp and total-system efficiency: planned (thrust stand INS-01, absolute "
                 "demonstration HI-ABS; Isp and efficiency need the same measured thrust). d) Test plan reviewed by "
                 "the expert committee and approved by PMMG / SPMMG: accepted as process.",
        evidence=[ev(RVM, "#/rows[id=RVM-22]"), ev(AO, "#/open_owner_questions"), ev(INS, "#/instruments"),
                  ev(HWDEF, "whole file")],
        rvm=["RVM-16", "RVM-22"],
        owner_input=["OIR-FAC-03", "OIR-FAC-04"]),
    "RFP-P20-01": dict(
        status="OWNER_INPUT_REQUIRED",
        response="4.2: deliverables will be accepted against the Para 2 parameters. 4.3: ISO certification of the "
                 "company is an organisational fact the repository does not hold (RVM-23: no artifact). An ATP will "
                 "be prepared from the Para 2 parameters and finalized after DDR / CDR; testing to applicable MIL / "
                 "ASTM / BIS / ESS standards (standards list to be fixed in the ATP).",
        evidence=[ev(RVM, "#/rows[id=RVM-23]")],
        rvm=["RVM-23", "RVM-21"],
        owner_input=["OIR-ORG-01"]),
    "RFP-P20-02": dict(
        status="COMPLY_PLANNED_WITH_EVIDENCE_PATH",
        response="Only ground demonstration in a simulated environment and space-qualification testing are "
                 "planned; no flight trial is proposed. Ground demonstration evidence order: Ar (engineering only) -> "
                 "N2 -> O2-bearing (labelled NO_ATOMIC_O) -> separate atomic-O life programme.",
        evidence=[ev(RVM, "#/rows[id=RVM-22]"), ev(A9, "whole file (evidence order)")],
        rvm=["RVM-22"]),
    "RFP-P20-03": dict(
        status="NOT_YET_DEMONSTRATED",
        response="Acknowledged. The partial-success criterion (EM of the ABEP system and a qualified electric "
                 "thruster with O and N2 at Milestone 4) depends on evidence that does not yet exist: Hall-transport "
                 "validation (gate 3 FAIL), O-bearing operation (O/O2 chemistry DRAFT; ground O2 tests are "
                 "NO_ATOMIC_O) and a qualification record on N2 and O (RVM-24). This is the programme's principal "
                 "schedule risk (R-01, R-02).",
        evidence=[ev(RVM, "#/rows[id=RVM-24]"), ev(CLAUDE, "section 'Gate status' (gate 3)"), ev(OO2, "#/status")],
        rvm=["RVM-24", "RVM-09"]),
    "RFP-P20-04": dict(
        status="COMPLY_PLANNED_WITH_EVIDENCE_PATH",
        response="Milestone 1 (PDR-1, T0+09 months, 15 %): preliminary mechanical and electrical design, BoM, "
                 "preliminary test plan and test-facility document. Inputs available at bbc480c: H-1 freeze-candidate "
                 "definition, H2 hardware lanes, RFQ v3 quotation packages, instrumentation definition, P1-P4 "
                 "frameworks. Mapping in 03_DEVELOPMENT_AND_TEST_PLAN.md.",
        evidence=[ev(RVM, "#/rows[id=RVM-25]"), ev(H1, "#/status"), ev(RFQ3, "#/status"), ev(INS, "#/status")],
        rvm=["RVM-25"]),
    "RFP-P20-05": dict(
        status="COMPLY_PLANNED_WITH_EVIDENCE_PATH",
        response="Milestone 2 (PDR-2, T0+12 months, 10 %): PSE software preliminary design, FDIR, telemetry (MATLAB "
                 "and C), test-facility readiness review. No flight software, FDIR or telemetry artifact exists at "
                 "bbc480c; the bus-boundary start-up sequencing (SEQ-1) is the only sequencing input. The RFP lists "
                 "the deliverable as 'approved GNC design document and codes' (verbatim; owner to confirm the reading "
                 "for a propulsion PSE).",
        evidence=[ev(RVM, "#/rows[id=RVM-25]"), ev(BPB, "#/sequencing")],
        rvm=["RVM-25"],
        owner_input=["OIR-TEC-07"]),
    "RFP-P20-06": dict(
        status="COMPLY_PLANNED_WITH_EVIDENCE_PATH",
        response="Milestone 3 (CDR, T0+20 months, 20 %): EM thruster and EM power-supply electronics realized and "
                 "demonstrated with STORAGE input (not intake), consistent with the hardware-first order (H-1 + ICP "
                 "coupled operation on stored N2 / Xe before any intake). Evidence path: A9.21 programme steps "
                 "through COUPLED-H1-ICP and the measured H-1 thrust / feed map.",
        evidence=[ev(RVM, "#/rows[id=RVM-25]"), ev(HWP, "#/steps")],
        rvm=["RVM-25"]),
    "RFP-P21-01": dict(
        status="COMPLY_PLANNED_WITH_EVIDENCE_PATH",
        response="Milestone 4 (T0+24 months, 35 %): EM intake with compressor and storage; QM PSE and thruster "
                 "testing. Planned; carries the Milestone-4 exit-criterion risk (RFP-P20-03) and the upstream "
                 "flow-gap risk (R-03).",
        evidence=[ev(RVM, "#/rows[id=RVM-25]"), ev(RVM, "#/rows[id=RVM-24]")],
        rvm=["RVM-25", "RVM-24"]),
    "RFP-P21-02": dict(
        status="COMPLY_PLANNED_WITH_EVIDENCE_PATH",
        response="Milestone 5 (T0+36 months, 20 %): QM intake realization, total QM integration, ENTEST "
                 "qualification, documentation, delivery and closure. Planned (RVM-25, RVM-21).",
        evidence=[ev(RVM, "#/rows[id=RVM-25]"), ev(RVM, "#/rows[id=RVM-21]")],
        rvm=["RVM-25", "RVM-21"]),
    "RFP-P21-03": dict(
        status="OWNER_INPUT_REQUIRED",
        response="Acknowledged: no waiver is sought for Part IV(B). Part IV(B) items 1 (financial), 2 (in-house "
                 "expertise / heritage), 3 (infrastructure, RFP-P27-01), 4 (manpower) and 5 (academia, RFP-P27-02) "
                 "are organisational qualifications the repository does not hold.",
        evidence=[ev(REG, "#/page_coverage/screened_out"), ev(RVM, "#/rows[id=RVM-26]")],
        rvm=["RVM-26"],
        owner_input=["OIR-ORG-02", "OIR-ORG-03", "OIR-ORG-06", "OIR-FAC-01", "OIR-FAC-02", "OIR-COL-01"]),
    "RFP-P27-01": dict(
        status="OWNER_INPUT_REQUIRED",
        response="UHV propulsion test facility and low-thrust measurement setup: in-house / consortium / sub-contract "
                 "status is an owner fact. The repository defines the instrumentation requirements (INS-01 thrust "
                 "stand principle, vacuum / gauge requirements) but holds no facility availability record (RVM-26).",
        evidence=[ev(RVM, "#/rows[id=RVM-26]"), ev(INS, "#/instruments")],
        rvm=["RVM-26"],
        owner_input=["OIR-FAC-01", "OIR-FAC-02"]),
    "RFP-P27-02": dict(
        status="OWNER_INPUT_REQUIRED",
        response="Collaboration with academia / research institute on material compatibility of intake and "
                 "thruster with nascent O, with an LoI or MoU, is required. No partner is recorded in the "
                 "repository; the AO programme (register v5, P4) defines the work share that a partner could take.",
        evidence=[ev(AO, "#/status"), ev(P4, "#/status"), ev(REG, "#/rvm_mapping")],
        rvm=["RVM-16"],
        owner_input=["OIR-COL-01"]),
    "RFP-P30-01": dict(
        status="OWNER_INPUT_REQUIRED",
        response="Micro-newton-level thrust measurement capability (scored in-house / consortium / sub-contract). "
                 "The repository plans an mN-level torsional / inverted-pendulum stand (INS-01) for the 12-25 mN "
                 "range; that plan is not evidence of micro-newton capability (RVM-26, DISC-10). Facility, ownership "
                 "and calibration record are owner items.",
        evidence=[ev(RVM, "#/rows[id=RVM-26]"), ev(INS, "#/instruments")],
        rvm=["RVM-26"],
        owner_input=["OIR-FAC-02"]),
}

# Gate statuses carried verbatim from bbc480c (F9 architecture_gates, pre_lock1_gates; RVM owner_approved_gates; HW programme)
GATE_SOURCES = {
    "AG": (F9, "#/architecture_gates"),
    "GNG-ICP-01": (F9, "#/pre_lock1_gates[id=GNG-ICP-01]"),
}

# Owner-input checklist (ids referenced from the clauses and the section skeletons)
OWNER_INPUTS = {
    "OIR-IC-01": "Indigenous-content plan figures: per-subsystem IC % (thruster, intake, compressor + storage, PSE) and "
                 "project IC % with the computation basis (RFP-P19-05 / RFP-P18-03 a; Part IV(C) 2 scoring).",
    "OIR-IC-02": "Supplier / make-or-buy list with country of origin for every BoM line (RFQ v3 packages are "
                 "quotation-only; nothing selected).",
    "OIR-IC-03": "Indigenization roadmap for any imported item (e.g. Xe tank / regulator, RF components, 1553B "
                 "core) with ITAR / export-control exposure statement.",
    "OIR-ORG-01": "ISO certification: standard, scope, certificate number, validity (RFP-P20-01 4.3).",
    "OIR-ORG-02": "Financial capability: CA-certified net-worth document (Part IV(B) 1).",
    "OIR-ORG-03": "In-house expertise / heritage evidence: indigenous EP system realization, space-grade "
                  "electronics, vacuum test systems (Part IV(B) 2; Part IV(C) 1, 3).",
    "OIR-ORG-04": "Technical-evaluation presentation: presenters and date availability (RFP-P18-03 b).",
    "OIR-ORG-05": "Consortium: whether proposed, members, roles, signed consortium agreement (RFP-P18-03 c).",
    "OIR-ORG-06": "Manpower: named staff with > 3 years in high-energy physics and electric propulsion; MTech / PhD "
                  "profiles (Part IV(B) 4; Part IV(C) 6).",
    "OIR-FAC-01": "UHV propulsion test facility: owner / location / pumping speed / base pressure / in-house, "
                  "consortium or sub-contract status, with documentary proof (RFP-P27-01 i; Part IV(C) 5).",
    "OIR-FAC-02": "Thrust measurement system: type, range, resolution (micro-newton capability), calibration record, "
                  "in-house / consortium / sub-contract (RFP-P27-01 ii, RFP-P30-01).",
    "OIR-FAC-03": "Facility to simulate the VLEO air mixture and a rarefied-gas source with prescribed mg/s and "
                  "velocity for intake-erosion tests (RFP-P17-02 4, RFP-P19-06 b).",
    "OIR-FAC-04": "Ground atomic-oxygen exposure facility and target fluence (AOL-OQ-05; RFP-P19-06 a).",
    "OIR-COL-01": "Academic / research partner for AO material compatibility, its work share and the LoI / MoU "
                  "(RFP-P27-02).",
    "OIR-TEC-01": "Upstream-closure citation decision (post-freeze caveat): cite the bbc480c F7/F8 numbers as five-state "
                  "screening results only, or re-freeze at 32c9e63 (bid_technical_baseline.json "
                  "post_freeze_commits_known_at_freeze.owner_attention).",
    "OIR-TEC-02": "Electronics / sensor redundancy concept for single-point-failure tolerance and its mass / power "
                  "allocation (RFP-P18-02, RFP-P18-09).",
    "OIR-TEC-03": "Mission inputs not in the RFP: inclination / LTAN, AOCS pointing envelope, host-spacecraft drag ICD "
                  "(A9.21 EXTERNAL_INPUTS) - or a statement in the bid that these are requested from DRDO at PDR.",
    "OIR-TEC-04": "Spacecraft bus input voltage / power-quality assumptions for the PPU front end (A902-12 TBD).",
    "OIR-TEC-05": "Mass-closure position for the bid: how the < 40 kg (wet) exceedance of the MEV planning roll-up is "
                  "presented and which redesign levers are offered (MQ-10); confirm the wet reading (DISC-02).",
    "OIR-TEC-06": "MIL-1553B implementation choice (RT core / transceiver source, bus A/B redundancy) for the offer.",
    "OIR-TEC-07": "Reading of the Milestone-2 deliverable 'approved GNC design document and codes' for a propulsion "
                  "PSE (seek DRDO clarification or state the reading).",
    "OIR-TEC-08": "GNG-ICP-01 GO / NO-GO criteria (owner approved existence and placement only; criteria "
                  "PENDING_OWNER_ACCEPTANCE).",
    "OIR-SCH-01": "T0 assumption and confirmation that the A9.21 hardware order can be resourced inside the RFP "
                  "milestone offsets (no dates beyond T0 offsets are stated by this package).",
    "OIR-RSK-01": "Likelihood / impact rating and risk owner for each technical risk R-01..R-13 (04_RISK_REGISTER.md); "
                  "the repository holds no risk scoring.",
    "OIR-COM-01": "Cost / price breakdown, payment-milestone acceptance and all commercial formats (commercial bid; "
                  "not in this technical package).",
    "OIR-DOC-01": "Mandatory formats / annexures on RFP pages 1-15 and 34-40 (NOT screened by the repository) and "
                  "the DPR template pp. 22-25 / industry profile pp. 32-33 (screened from the text layer only).",
}
