//! NP-ICP-CHEM-AIR addendum_01 A1-OWN: every own ICP table listed in `data/chemistry/icp/own_tables.json` is
//! regenerated byte for byte (`.dat`, `.dat.source`, `xs/<name>.json`) from `abep_chem::icp_own`, and the listed
//! sha256 are the files'. Also the preregistered A1-XE-SRC unit cross-check of XE-ION-01.

use abep_chem::icp_own::{xe_tables, MB2016_XE1, MB2016_XE2, OWN_DIR};
use abep_provenance::sha256_hex as sha_hex;
use std::path::PathBuf;

fn root() -> PathBuf {
    abep_provenance::workspace_repo_root().expect("repository root")
}

#[test]
fn every_own_table_regenerates_byte_for_byte() {
    let root = root();
    let list: serde_json::Value =
        serde_json::from_slice(&std::fs::read(root.join(OWN_DIR).join("own_tables.json")).unwrap()).unwrap();
    assert_eq!(list["addendum"], "NP-ICP-CHEM-AIR addendum_01");
    let tables = xe_tables();
    let entries = list["tables"].as_array().unwrap();
    assert!(!entries.is_empty());
    for e in entries {
        let name = e["name"].as_str().unwrap();
        let t = tables.iter().find(|t| t.name == name).unwrap_or_else(|| panic!("{name}: no builder"));
        assert_eq!(e["path"].as_str().unwrap(), t.table_rel());
        let (dat, src) = t.render().unwrap();
        let xs = t.xs_text().unwrap();
        let on_disk = |rel: &str| std::fs::read(root.join(rel)).unwrap();
        let dat_rel = t.table_rel();
        let src_rel = format!("{dat_rel}.source");
        let xs_rel = format!("{OWN_DIR}/{}", t.xs_rel());
        assert_eq!(on_disk(&dat_rel), dat.as_bytes(), "{dat_rel}");
        assert_eq!(on_disk(&src_rel), src.as_bytes(), "{src_rel}");
        assert_eq!(on_disk(&xs_rel), xs.as_bytes(), "{xs_rel}");
        assert_eq!(e["sha256"].as_str().unwrap(), sha_hex(dat.as_bytes()));
        assert_eq!(e["source_file_sha256"].as_str().unwrap(), sha_hex(src.as_bytes()));
        assert_eq!(e["xs_sha256"].as_str().unwrap(), sha_hex(xs.as_bytes()));
    }
}

/// A1-XE-SRC XE-ION-01: the inferred unit 1e-22 m^2 holds only if sigma(Xe+) agrees with Stephan & Maerk sigma(Xe+)
/// and sigma(Xe+) + 2 sigma(Xe2+) with the Rapp & Englander-Golden gross cross section (both GK2008 Table D-1) within
/// 10 % at 35-100 eV; otherwise the inference is refused.
#[test]
fn xe_ion_01_unit_inference_passes_its_preregistered_check() {
    let sm = [
        (35.0, 4.17e-20),
        (40.0, 4.30e-20),
        (45.0, 4.31e-20),
        (50.0, 4.29e-20),
        (55.0, 4.27e-20),
        (60.0, 4.37e-20),
        (65.0, 4.47e-20),
        (70.0, 4.54e-20),
        (75.0, 4.57e-20),
        (80.0, 4.59e-20),
        (85.0, 4.55e-20),
        (90.0, 4.48e-20),
        (95.0, 4.42e-20),
        (100.0, 4.31e-20),
    ];
    for (e, s) in sm {
        let r = MB2016_XE1.sigma_m2(e) / s;
        assert!((r - 1.0).abs() <= 0.10, "Stephan & Maerk {e} eV: ratio {r}");
    }
    let re = [(40.0, 4.475e-20), (50.0, 4.835e-20), (60.0, 5.029e-20), (80.0, 5.178e-20), (100.0, 5.380e-20)];
    for (e, s) in re {
        let r = (MB2016_XE1.sigma_m2(e) + 2.0 * MB2016_XE2.sigma_m2(e)) / s;
        assert!((r - 1.0).abs() <= 0.10, "Rapp & Englander-Golden {e} eV: ratio {r}");
    }
}
