"""P5-N2 v1 vacuum campaign: E x B / species-acceleration physics forensics (NON-GATING, descriptive only).

This script never scores, re-scores or re-labels a run. Official per-run statuses and the official O5 E x B diagnostic are
READ from hallthruster_bridge/validation/p5_n2_campaign_v1_vacuum_scores.json. The v1 outcome (all nine screening
candidates INCONCLUSIVE / NOT ELIGIBLE, credible set empty) is final and is not touched. Nothing here is tuned, and no
criterion, tolerance or rate-table limit is proposed or changed. The E x B diagnostic never eliminates or admits anything.

What it does (all from frozen repository files; deterministic; no Julia, a few seconds of CPU):
  1. Recomputes, for every N1-N3 run of the frozen raw dataset, V_a,s = m_s u_s^2 / (2 Z_s e) at the model outlet from
     `outlet_ions` with the same constants and operation order as the frozen scorer (scripts/score_p5_n2_campaign.py,
     exb()), and checks it against the official `exb_diagnostic` block (value and ordering flag).
  2. Adds descriptive quantities the official block does not carry: N^2+ energy per charge, N2^2+ presence, all-species
     outlet flux fractions, D = V_a(N+) - V_a(N2+), R = V_a(N+)/V_a(N2+), velocity ratios, the alternative
     time-average definition u_eff = <n u>/<n> (both <n> and <n u> are recorded), the energy each model species would show
     under the E x B "m/Z = 14" label, discharge-voltage slopes, and rank associations with Te_max_eV, flux fractions,
     I_d oscillation and the candidate transport parameters.
  3. Groups everything by point, candidate, registration, chemistry, coil shape, official domain class and Te_max bin.

Measured side (frozen measurement audit, identification/brabston_p5_n2_measurement_audit_v1.json): Brabston et al.,
JPP 2025, doi:10.2514/1.B39623, Fig. 10 (digitized eta_V,n; V_a,n = eta_V,n V_d), E x B probe 1 m downstream of the exit
plane on centreline, bi-Gaussian peaks, Eq. (11) plasma-potential correction, Table 5 sigma 11.6 V. The propagated
sigma of a difference of two such values assumes independence (an ASSUMPTION, labelled as such in the output).

Outputs: docs/forensics/p5_n2_v1/exb_physics/exb_physics.json and exb_physics_tables.md (both regenerated byte-identically).
Usage: python scripts/forensics/p5_n2_v1_exb_physics.py [--check]   (--check: verify the committed outputs are current)
"""
import collections, gzip, hashlib, json, math, os, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
BR = os.path.join(ROOT, "hallthruster_bridge")
RAW = os.path.join(BR, "validation", "p5_n2_campaign_v1_vacuum_raw.jsonl.gz")
SCORES = os.path.join(BR, "validation", "p5_n2_campaign_v1_vacuum_scores.json")
AUDIT = os.path.join(BR, "identification", "brabston_p5_n2_measurement_audit_v1.json")
FINDINGS = os.path.join(BR, "identification", "p5_n2_measurement_audit_findings_v1.json")
CASES = os.path.join(BR, "cases", "p5_n2.json")
ENSEMBLE = os.path.join(BR, "ensemble", "transport_ensemble_v0.json")
OUT_DIR = os.path.join(ROOT, "docs", "forensics", "p5_n2_v1", "exb_physics")
OUT_JSON = os.path.join(OUT_DIR, "exb_physics.json")
OUT_MD = os.path.join(OUT_DIR, "exb_physics_tables.md")

# Same constants as the frozen scorer (scripts/score_p5_n2_campaign.py): CODATA 2018 amu and e; NIST atomic weights.
AMU, E = 1.66053906660e-27, 1.602176634e-19
MASS = {"N2": 28.0134 * AMU, "N": 14.0067 * AMU}
EXB_SIGMA_V = 11.6                      # Brabston 2025 Table 5, max V_a,n (E x B) uncertainty, nitrogen
POINTS = ("N1", "N2", "N3")             # E x B data exist for N1-N3 only (audit finding F3)
ROUND_V, ROUND_F = 4, 6

# Published ion kinetic-energy peaks quoted in a review (literature context only; not a model input, not a DI N+ value):
# Song et al., J. Phys. Chem. Ref. Data 52, 023104 (2023), doi:10.1063/5.0150618, Sec. 2.8, p. 023104-17: "For N2+ ions [as
# typeset] at 70 eV, Crowe and McConkey [ref. 115] observed a single broad peak in the ion kinetic energy around 2 eV, at 90 eV
# (a second, superimposed peak at 5 eV), and at 300 eV collision energy (an additional peak around 8 eV)". Ref. 115 is
# A. Crowe & J. W. McConkey, "Dissociative ionization by electron impact. IV. Energy and angular distributions of N^2+ from
# N2", J. Phys. B 8, 1765 (1975), doi:10.1088/0022-3700/8/10/025 (title checked in the JPCRD reference list and in Crossref;
# the paper itself was not accessed). The measured ion is therefore most likely the atomic dication N^2+ (inferred from the
# cited title; the review body typesets N2+), NOT DI-born N+. These peaks are used below only as an order-of-magnitude PROXY
# (level 5, "verify"). The DI N+ fragment KE (e.g. Crowe & McConkey II, J. Phys. B 6, 2108 (1973),
# doi:10.1088/0022-3700/6/10/023, or Deleanu & Stockdale, J. Chem. Phys. 63, 3898 (1975), doi:10.1063/1.431831) is
# TBD: requires reading those papers' full text (only their Crossref abstracts were accessed; no KE values are in them).
FRAGMENT_KE_PEAKS_EV = (2.0, 5.0, 8.0)
# Gurciullo, Lucca Fabris & Cappelli, J. Phys. D 52, 464003 (2019), Sec. 4.3.3 (XeAir-3, Wien filter 30 cm downstream):
# "The mean velocities of the ion species are ... 32 km s-1 (N2+) ... and 47 km s-1 (N+)" (rounded to 1 km/s). The preceding
# sentence refers to the "most probable ion velocity" shown in its figures 23-24, so whether these are mean or most-probable
# velocities is ambiguous in the source (verify). Level 3 (different thruster, Z-70).
GURCIULLO_XEAIR3_KMS = {"N2+": 32.0, "N+": 47.0}


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def va(sym, u, Z):
    """Energy per charge [V] exactly as the frozen scorer computes it (same operation order)."""
    return MASS[sym] * u ** 2 / (2 * Z * E)


def rnd(x, nd):
    if x is None:
        return None
    if isinstance(x, float) and not math.isfinite(x):
        return None
    return round(x, nd)


def quantile(xs, q):
    s = sorted(xs)
    if not s:
        return None
    pos = q * (len(s) - 1)
    lo = int(math.floor(pos)); hi = min(lo + 1, len(s) - 1)
    return s[lo] + (s[hi] - s[lo]) * (pos - lo)


def stats(xs, nd=ROUND_V):
    xs = [x for x in xs if x is not None]
    if not xs:
        return None
    return {"n": len(xs), "min": rnd(min(xs), nd), "p10": rnd(quantile(xs, 0.1), nd), "median": rnd(quantile(xs, 0.5), nd),
            "p90": rnd(quantile(xs, 0.9), nd), "max": rnd(max(xs), nd)}


def ranks(xs):
    order = sorted(range(len(xs)), key=lambda i: xs[i])
    r = [0.0] * len(xs)
    i = 0
    while i < len(order):
        j = i
        while j + 1 < len(order) and xs[order[j + 1]] == xs[order[i]]:
            j += 1
        avg = (i + j) / 2.0 + 1.0
        for k in range(i, j + 1):
            r[order[k]] = avg
        i = j + 1
    return r


def spearman(x, y):
    rx, ry = ranks(x), ranks(y)
    n = len(x)
    mx, my = sum(rx) / n, sum(ry) / n
    sxy = sum((a - mx) * (b - my) for a, b in zip(rx, ry))
    sxx = sum((a - mx) ** 2 for a in rx); syy = sum((b - my) ** 2 for b in ry)
    return None if sxx == 0 or syy == 0 else sxy / math.sqrt(sxx * syy)


def ls_slope(x, y):
    mx, my = sum(x) / len(x), sum(y) / len(y)
    return sum((a - mx) * (b - my) for a, b in zip(x, y)) / sum((a - mx) ** 2 for a in x)


def load_inputs():
    recs = [json.loads(l) for l in gzip.open(RAW, "rt")]
    scores = json.load(open(SCORES))
    audit = json.load(open(AUDIT))["points"]
    cases = {c["id"]: c for c in json.load(open(CASES))["cases"]}
    ens = {c["ensemble_member_id"]: c["transport_parameters"] for c in json.load(open(ENSEMBLE))["screening_candidates"]}
    return recs, scores, audit, cases, ens


def official_status(scores):
    st = collections.defaultdict(dict)
    for r in scores["runs"]:
        st[r["key"]][r["reading"]] = r["status"]
    return st


def run_row(r, audit, cases, ens, status):
    """Descriptive per-run quantities (N1-N3). Pure function of the frozen record."""
    ions = r["outlet_ions"]
    total = sum(v["flux_m2s"] for v in ions.values())
    n2p, np_, nz2 = ions["N2_Z1"], ions["N_Z1"], ions.get("N_Z2")
    obs = audit[r["point"]]["fig10"]
    Va = {"N2+": va("N2", n2p["u_ms"], n2p["Z"]), "N+": va("N", np_["u_ms"], np_["Z"])}
    Va_nu = {"N2+": va("N2", n2p["flux_m2s"] / n2p["n_m3"], 1), "N+": va("N", np_["flux_m2s"] / np_["n_m3"], 1)}
    row = {
        "key": r["key"], "candidate": r["candidate"], "chemistry": r["chemistry"], "point": r["point"],
        "registration": r["registration"], "coil_shape": r["coil_shape"],
        "status_A": status[r["key"]]["A"], "status_B": status[r["key"]]["B"],
        "domain_class": "OUT_OF_DOMAIN" if status[r["key"]]["A"] == "OUT_OF_DOMAIN" else "SCOREABLE",
        "Te_max_eV": r["Te_max_eV"], "Id_rms_rel": r["Id_rms_rel"], "V_d": audit[r["point"]]["table2"]["V_d"],
        "transport": ens[r["candidate"]],
        "outlet_z_minus_exit_m": cases[r["case"]]["domain_m"] - cases[r["case"]]["L_m"],
        "Va_N2p": Va["N2+"], "Va_Np": Va["N+"],
        "Va_N2p_nu_over_n": Va_nu["N2+"], "Va_Np_nu_over_n": Va_nu["N+"],
        "Va_NZ2_per_charge": va("N", nz2["u_ms"], nz2["Z"]) if nz2 else None,
        "Va_NZ2_per_charge_nu_over_n": va("N", nz2["flux_m2s"] / nz2["n_m3"], nz2["Z"]) if nz2 else None,
        "u_N2p": n2p["u_ms"], "u_Np": np_["u_ms"], "u_NZ2": nz2["u_ms"] if nz2 else None,
        "ff_N2p": n2p["flux_m2s"] / total, "ff_Np": np_["flux_m2s"] / total,
        "ff_NZ2": nz2["flux_m2s"] / total if nz2 else 0.0,
        "N2_Z2_present": "N2_Z2" in ions,
        "species_keys": sorted(ions),
        "obs_Va_N2p": obs["Va_N2plus_V"], "obs_Va_Np": obs["Va_Nplus_V"],
    }
    row["D"] = row["Va_Np"] - row["Va_N2p"]
    row["D_nu_over_n"] = row["Va_Np_nu_over_n"] - row["Va_N2p_nu_over_n"]
    row["R"] = row["Va_Np"] / row["Va_N2p"]
    row["u_ratio_Np_N2p"] = row["u_Np"] / row["u_N2p"]
    row["dVa_Np"] = row["Va_Np"] - row["obs_Va_Np"]
    row["dVa_N2p"] = row["Va_N2p"] - row["obs_Va_N2p"]
    row["ordering"] = row["Va_Np"] > row["Va_N2p"]
    row["ordering_nu_over_n"] = row["Va_Np_nu_over_n"] > row["Va_N2p_nu_over_n"]
    # Energy each species would be assigned under the E x B "m/Z = 14 amu/e" label (a Wien filter selects velocity only):
    # E_14 = m_N u^2 / (2 e). N+: = V_a(N+); N2+ (m/Z 28): = V_a(N2+) * (m_N / m_N2); N^2+ (m/Z 7): = 2 x per-charge energy.
    row["E14_N2p"] = MASS["N"] * row["u_N2p"] ** 2 / (2 * E)
    row["E14_Np"] = MASS["N"] * row["u_Np"] ** 2 / (2 * E)
    row["E14_NZ2"] = MASS["N"] * row["u_NZ2"] ** 2 / (2 * E) if nz2 else None
    return row


def reproduce(rows, scores):
    exb = scores["exb_diagnostic"]
    dev = {"N2+": 0.0, "N+": 0.0}
    flag_mismatch, missing = 0, []
    for row in rows:
        o = exb.get(row["key"])
        if o is None:
            missing.append(row["key"]); continue
        dev["N2+"] = max(dev["N2+"], abs(row["Va_N2p"] - o["N2+"]["Va_model_V"]))
        dev["N+"] = max(dev["N+"], abs(row["Va_Np"] - o["N+"]["Va_model_V"]))
        flag_mismatch += int(row["ordering"] != o["ordering_Nplus_above_N2plus"])
    official_true = sum(1 for v in exb.values() if v.get("ordering_Nplus_above_N2plus"))
    return {"n_runs_recomputed": len(rows), "n_official_exb_entries": len(exb),
            "keys_identical": sorted(r["key"] for r in rows) == sorted(exb),
            "missing_in_official": missing,
            "max_abs_dev_Va_V": {k: v for k, v in dev.items()}, "ordering_flag_mismatches": flag_mismatch,
            "ordering_true_recomputed": sum(r["ordering"] for r in rows), "ordering_true_official": official_true}


def reading_consistency(rows):
    """Official statuses under readings A and B (read, never recomputed). domain_class uses reading A; this checks that
    OUT_OF_DOMAIN is identical under both readings and lists the keys whose A/B statuses differ (PASS vs FAIL_VALIDATION)."""
    ood_diff = [r["key"] for r in rows if (r["status_A"] == "OUT_OF_DOMAIN") != (r["status_B"] == "OUT_OF_DOMAIN")]
    mixed = sorted((r["key"], r["status_A"], r["status_B"]) for r in rows if r["status_A"] != r["status_B"])
    scoreable = [r for r in rows if r["domain_class"] != "OUT_OF_DOMAIN"]
    return {"n_keys_ood_differs_between_readings": len(ood_diff),
            "n_not_ood_keys": len(scoreable),
            "n_mixed_reading_keys": len(mixed),
            "mixed_reading_keys": [{"key": k, "status_A": a, "status_B": b} for k, a, b in mixed],
            "ordering_count_in_mixed_reading_keys": sum(r["ordering"] for r in rows if r["status_A"] != r["status_B"]),
            "note": "OUT_OF_DOMAIN is decided per key (chemistry validity) and is the same under readings A and B; the "
                    "mixed-reading keys differ only between PASS and FAIL_VALIDATION."}


def group_summary(rows):
    return {
        "n": len(rows), "n_out_of_domain": sum(r["domain_class"] == "OUT_OF_DOMAIN" for r in rows),
        "Va_N2p": stats([r["Va_N2p"] for r in rows]), "Va_Np": stats([r["Va_Np"] for r in rows]),
        "Va_NZ2_per_charge": stats([r["Va_NZ2_per_charge"] for r in rows]),
        "D": stats([r["D"] for r in rows]), "R": stats([r["R"] for r in rows], ROUND_F),
        "u_ratio_Np_N2p": stats([r["u_ratio_Np_N2p"] for r in rows], ROUND_F),
        "ff_N2p": stats([r["ff_N2p"] for r in rows], ROUND_F), "ff_Np": stats([r["ff_Np"] for r in rows], ROUND_F),
        "ff_NZ2": stats([r["ff_NZ2"] for r in rows], ROUND_F),
        "dVa_Np": stats([r["dVa_Np"] for r in rows]), "dVa_N2p": stats([r["dVa_N2p"] for r in rows]),
        "Te_max_eV": stats([r["Te_max_eV"] for r in rows]),
        "Va_N2p_over_Vd": stats([r["Va_N2p"] / r["V_d"] for r in rows], ROUND_F),
        "Va_Np_over_Vd": stats([r["Va_Np"] / r["V_d"] for r in rows], ROUND_F),
        "ordering_count": sum(r["ordering"] for r in rows),
        "ordering_count_nu_over_n": sum(r["ordering_nu_over_n"] for r in rows),
    }


def grouped(rows, keyf):
    g = collections.defaultdict(list)
    for r in rows:
        g[keyf(r)].append(r)
    return {k: group_summary(g[k]) for k in sorted(g)}


def te_bin(te):
    for lo, hi in ((0, 15), (15, 18), (18, 21), (21, 1e9)):
        if lo <= te < hi:
            return f"{lo}-{hi}" if hi < 1e9 else f">={lo}"


def rms_band(x):
    return "<1" if x < 1 else ("1-3" if x < 3 else ">=3")


def measured_block(audit):
    out = {}
    for p in POINTS:
        f = audit[p]["fig10"]
        a, b = f["Va_N2plus_V"], f["Va_Nplus_V"]
        out[p] = {"V_d": audit[p]["table2"]["V_d"], "Va_N2p": rnd(a, ROUND_V), "Va_Np": rnd(b, ROUND_V),
                  "D": rnd(b - a, ROUND_V), "R": rnd(b / a, ROUND_F),
                  "Va_N2p_over_Vd": rnd(a / audit[p]["table2"]["V_d"], ROUND_F),
                  "Va_Np_over_Vd": rnd(b / audit[p]["table2"]["V_d"], ROUND_F),
                  "u_ratio_Np_N2p_if_labels_hold": rnd(math.sqrt((b / MASS["N"]) / (a / MASS["N2"])), ROUND_F),
                  "sigma_each_V": EXB_SIGMA_V,
                  "sigma_D_V_assuming_independent_errors": rnd(math.sqrt(2) * EXB_SIGMA_V, ROUND_V),
                  "p_chamber_Torr": audit[p]["table2"]["p_chamber_Torr_N2"]}
    return out


def vd_slopes(rows, audit):
    series = collections.defaultdict(dict)
    for r in rows:
        series[(r["candidate"], r["chemistry"], r["registration"], r["coil_shape"])][r["point"]] = r
    s2, s1, sD = [], [], []
    for k in sorted(series):
        pts = series[k]
        if set(pts) != set(POINTS):
            continue
        vd = [pts[p]["V_d"] for p in POINTS]
        s2.append(ls_slope(vd, [pts[p]["Va_N2p"] for p in POINTS]))
        s1.append(ls_slope(vd, [pts[p]["Va_Np"] for p in POINTS]))
        sD.append(ls_slope(vd, [pts[p]["D"] for p in POINTS]))
    vd = [audit[p]["table2"]["V_d"] for p in POINTS]
    m2 = ls_slope(vd, [audit[p]["fig10"]["Va_N2plus_V"] for p in POINTS])
    m1 = ls_slope(vd, [audit[p]["fig10"]["Va_Nplus_V"] for p in POINTS])
    return {"n_series": len(s2), "model_dVa_dVd_N2p": stats(s2, ROUND_F), "model_dVa_dVd_Np": stats(s1, ROUND_F),
            "model_dD_dVd": stats(sD, ROUND_F), "measured_dVa_dVd_N2p": rnd(m2, ROUND_F),
            "measured_dVa_dVd_Np": rnd(m1, ROUND_F), "measured_dD_dVd": rnd(m1 - m2, ROUND_F)}


def associations(rows):
    pairs = [("D", "Te_max_eV"), ("D", "ff_Np"), ("D", "ff_NZ2"), ("D", "Id_rms_rel"), ("Va_Np", "ff_Np"),
             ("Va_N2p", "ff_Np"), ("Va_Np", "Te_max_eV"), ("Va_N2p", "Te_max_eV"), ("R", "ff_NZ2"),
             ("D", "barrier_scale"), ("D", "center_L"), ("D", "width_L")]

    def val(r, k):
        return r["transport"][k] if k in r["transport"] else r[k]
    out = {}
    for scope in ("all",) + POINTS:
        sub = rows if scope == "all" else [r for r in rows if r["point"] == scope]
        out[scope] = {f"{a}~{b}": rnd(spearman([val(r, a) for r in sub], [val(r, b) for r in sub]), 3) for a, b in pairs}
    return out


def histogram(xs, width=10.0):
    lo = math.floor(min(xs) / width) * width
    hi = math.ceil(max(xs) / width) * width
    edges, counts = [], []
    e = lo
    while e < hi:
        edges.append([e, e + width]); counts.append(sum(1 for x in xs if e <= x < e + width)); e += width
    return {"bin_width_V": width, "bins": [{"lo": a, "hi": b, "count": c} for (a, b), c in zip(edges, counts)]}


RUN_COLUMNS = ("key", "candidate", "chemistry", "point", "registration", "coil_shape", "status_A", "status_B", "Te_max_eV",
               "Id_rms_rel", "Va_N2p", "Va_Np", "Va_NZ2_per_charge", "Va_N2p_nu_over_n", "Va_Np_nu_over_n", "D", "R",
               "u_N2p", "u_Np", "u_NZ2", "ff_N2p", "ff_Np", "ff_NZ2", "dVa_N2p", "dVa_Np", "ordering", "ordering_nu_over_n",
               "E14_NZ2", "N2_Z2_present")


def runs_table(rows):
    """Column-oriented per-run table (compact). Voltages and velocities rounded to 1e-4; ratios and fractions to 1e-6."""
    def cell(k, v):
        if isinstance(v, float):
            return rnd(v, ROUND_F if k.startswith(("ff_", "R", "Id_rms")) else ROUND_V)
        return v
    return {"columns": list(RUN_COLUMNS), "rows": [[cell(k, r[k]) for k in RUN_COLUMNS] for r in rows]}


def build():
    recs, scores, audit, cases, ens = load_inputs()
    status = official_status(scores)
    rows = [run_row(r, audit, cases, ens, status) for r in sorted(recs, key=lambda r: r["key"])
            if r["point"] in POINTS and r.get("outlet_ions")]
    meas = measured_block(audit)
    rep = reproduce(rows, scores)
    by_point = grouped(rows, lambda r: r["point"])
    worst_gap = {p: rnd(meas[p]["D"] - by_point[p]["D"]["max"], ROUND_V) for p in POINTS}
    Ds = [r["D"] for r in rows]
    geom = sorted({(r["registration"], rnd(r["outlet_z_minus_exit_m"], 6)) for r in rows})
    ker_max = max(FRAGMENT_KE_PEAKS_EV)
    chem = grouped(rows, lambda r: f"{r['chemistry']}|{r['point']}")
    # initial (birth) kinetic energy per charge of neutral-velocity products: N2 at 150 m/s, N at 150*sqrt(M_N2/M_N) m/s
    # (HallThruster.jl defaults, physics/constants.jl:33 and simulation/configuration.jl:331-343; inferred from code)
    u_n2 = 150.0
    u_n = u_n2 * math.sqrt(28.0134 / 14.0067)
    birth_ke = {"N2_150ms_eV": MASS["N2"] * u_n2 ** 2 / (2 * E), "N_212ms_eV": MASS["N"] * u_n ** 2 / (2 * E)}
    out = {
        "id": "p5_n2_v1_exb_physics", "role": "NON-GATING physics forensics of the O5 E x B diagnostic; descriptive only. "
        "Never eliminates, admits, re-scores or re-labels. Official v1 outcome unchanged: all 9 screening candidates "
        "INCONCLUSIVE / NOT ELIGIBLE, credible set empty.",
        "script": "scripts/forensics/p5_n2_v1_exb_physics.py",
        "inputs_sha256": {os.path.relpath(p, ROOT): sha256(p) for p in (RAW, SCORES, AUDIT, FINDINGS, CASES, ENSEMBLE)},
        "official_status_counts": scores["status_counts"],
        "official_reading_consistency": reading_consistency(rows),
        "reproduction_of_official_O5": rep,
        "measured": {"source": "Brabston et al., JPP 2025, doi:10.2514/1.B39623, Fig. 10 via the frozen measurement audit",
                     "evidence": "level 3; measured by E x B probe 1 m downstream of the exit plane on centreline, "
                                 "bi-Gaussian peak fit, Eq. (11) plasma-potential correction; digitized from a raster figure",
                     "points": meas},
        "observation_geometry": {
            "model_outlet": "right domain edge z = domain_m = 0.1 m from the anode (cases/p5_n2.json); value = ion.u[end] of "
                            "the time-averaged frame (campaign/p5_n2_campaign.jl:70-76)",
            "outlet_minus_exit_m_by_registration": [{"registration": g, "outlet_z_minus_exit_m": d} for g, d in geom],
            "exb_probe_minus_exit_m": 1.0,
            "unmodelled_path_m_by_registration": [{"registration": g, "path_m": rnd(1.0 - d, 6)} for g, d in geom],
            "model_reference_potential": "phi = cathode_coupling_voltage = 0 V at the outlet (HallThruster.jl default, not set "
                                         "by bridge_lib.jl); anode side phi = V_d + anode sheath",
            "measured_reference_potential": "Eq. (11): kinetic energy per charge at the probe minus the local plasma potential "
                                            "V_p at 1 m (Langmuir probe; values not published numerically, max uncertainty 0.25 V)"},
        "by_point": by_point,
        "by_candidate_point": grouped(rows, lambda r: f"{r['candidate']}|{r['point']}"),
        "by_registration_point": grouped(rows, lambda r: f"{r['registration']}|{r['point']}"),
        "by_chemistry_point": chem,
        "chemistry_spread_of_median_D_by_point_V": {
            p: rnd(max(v["D"]["median"] for k, v in chem.items() if k.endswith("|" + p))
                   - min(v["D"]["median"] for k, v in chem.items() if k.endswith("|" + p)), ROUND_V) for p in POINTS},
        "by_coil_point": grouped(rows, lambda r: f"{r['coil_shape']}|{r['point']}"),
        "by_domain_class_point": grouped(rows, lambda r: f"{r['domain_class']}|{r['point']}"),
        "by_Te_max_bin": grouped(rows, lambda r: te_bin(r["Te_max_eV"])),
        "by_Id_rms_band": grouped(rows, lambda r: rms_band(r["Id_rms_rel"])),
        "D_distribution": {"definition": "D = V_a(N+) - V_a(N2+) at the model outlet, time-averaged <u> (official definition)",
                           "all": stats(Ds), "count_D_ge_0": sum(d >= 0 for d in Ds),
                           "count_D_ge_0_nu_over_n": sum(r["D_nu_over_n"] >= 0 for r in rows),
                           "histogram": histogram(Ds),
                           "measured_D_minus_max_model_D_by_point_V": worst_gap},
        "time_average_definition_sensitivity": {
            "note": "HallThruster.jl time_average() averages n, nu and u separately (postprocess.jl:77-79); the official O5 "
                    "value uses <u>. <nu>/<n> is the density-weighted mean velocity. Neither is the most-probable velocity "
                    "of the time-integrated distribution an E x B probe records. Sensitivity only; the official value stands.",
            "ratio_Va_Np_nu_over_n_to_u": stats([r["Va_Np_nu_over_n"] / r["Va_Np"] for r in rows], ROUND_F),
            "ratio_Va_N2p_nu_over_n_to_u": stats([r["Va_N2p_nu_over_n"] / r["Va_N2p"] for r in rows], ROUND_F),
            "ratio_Va_NZ2_nu_over_n_to_u": stats([r["Va_NZ2_per_charge_nu_over_n"] / r["Va_NZ2_per_charge"] for r in rows],
                                                 ROUND_F),
            "ordering_count_nu_over_n": sum(r["ordering_nu_over_n"] for r in rows),
            "dVa_Np_nu_over_n": stats([r["Va_Np_nu_over_n"] - r["obs_Va_Np"] for r in rows]),
            "Id_rms_rel": stats([r["Id_rms_rel"] for r in rows], ROUND_F)},
        "multiply_charged": {
            "N2_Z2_present_in_runs": sum(r["N2_Z2_present"] for r in rows),
            "N_Z2_present_in_runs": sum(r["Va_NZ2_per_charge"] is not None for r in rows),
            "species_key_sets": sorted({"+".join(r["species_keys"]) for r in rows}),
            "NZ2_per_charge_vs_singles": {
                "between_N+_and_N2+": sum(min(r["Va_Np"], r["Va_N2p"]) <= r["Va_NZ2_per_charge"] <= max(r["Va_Np"], r["Va_N2p"])
                                         for r in rows),
                "above_both": sum(r["Va_NZ2_per_charge"] > max(r["Va_Np"], r["Va_N2p"]) for r in rows),
                "below_both": sum(r["Va_NZ2_per_charge"] < min(r["Va_Np"], r["Va_N2p"]) for r in rows),
                "above_N2p_nu_over_n": sum(r["Va_NZ2_per_charge_nu_over_n"] > r["Va_N2p_nu_over_n"] for r in rows)}},
        "velocity_space_m_over_Z_14_label": {
            "note": "A Wien filter passes one velocity; species are assigned by assuming m/Z. N+ and N2^2+ (m/Z 14) are "
                    "indistinguishable, and a species' V_a under a label is m_label u^2/(2 Z_label e). E14 = energy a model "
                    "species would be assigned if its outlet velocity were read under the N+ label. Descriptive only; no "
                    "re-attribution of the published peaks is proposed.",
            "by_point": {p: {"E14_N2p": stats([r["E14_N2p"] for r in rows if r["point"] == p]),
                             "E14_Np": stats([r["E14_Np"] for r in rows if r["point"] == p]),
                             "E14_NZ2": stats([r["E14_NZ2"] for r in rows if r["point"] == p]),
                             "ff_NZ2": stats([r["ff_NZ2"] for r in rows if r["point"] == p], ROUND_F)} for p in POINTS},
            "equal_birth_reference": {"R": 1.0, "u_ratio_Np_N2p": rnd(math.sqrt(MASS["N2"] / MASS["N"]), ROUND_F)}},
        "vd_slopes": vd_slopes(rows, audit),
        "associations_spearman": associations(rows),
        "neutral_birth_kinetic_energy_eV": {k: rnd(v, 6) for k, v in birth_ke.items()},
        "common_mode_invariance": "Any species-independent potential offset c per unit charge (cathode-to-ground, plume "
                                  "potential beyond the 0.1 m outlet, the Eq. (11) V_p term) shifts V_a(N+) and V_a(N2+) by the "
                                  "same c, so D is invariant: it cannot change the ordering or D. Algebraic, collisionless.",
        "fragment_kinetic_energy_context": {
            "published_peaks_eV": list(FRAGMENT_KE_PEAKS_EV),
            "ion_measured": "most likely N^2+ (atomic dication), inferred from the title of the cited ref. 115; the review body "
                            "typesets N2+; NOT DI-born N+ (verify against Crowe & McConkey 1975 itself)",
            "source": "Song et al., JPCRD 52, 023104 (2023), doi:10.1063/5.0150618, Sec. 2.8 (p. 023104-17), quoting ref. 115: "
                      "Crowe & McConkey, 'Dissociative ionization by electron impact. IV. Energy and angular distributions of "
                      "N^2+ from N2', J. Phys. B 8, 1765 (1975), doi:10.1088/0022-3700/8/10/025 (not accessed; title via the "
                      "JPCRD reference list and Crossref); level 5, verify",
            "DI_Nplus_fragment_KE_eV": "TBD - requires the full text of Crowe & McConkey II, J. Phys. B 6, 2108 (1973), "
                                       "doi:10.1088/0022-3700/6/10/023, or Deleanu & Stockdale, J. Chem. Phys. 63, 3898 "
                                       "(1975), doi:10.1063/1.431831 (Crossref abstracts accessed only: fast N+ >~1.5 eV "
                                       "detected, structured KE spectra, near-isotropic angular distributions; no values)",
            "proxy_max_peak_over_min_measured_D": rnd(ker_max / min(meas[p]["D"] for p in POINTS), 4),
            "proxy_max_peak_over_min_model_Np_deficit": rnd(ker_max / min(-r["dVa_Np"] for r in rows), 4),
            "note": "Order-of-magnitude PROXY only (the peaks belong to a different ion, most likely N^2+): the whole KE "
                    "(not its axial component) expressed in volts for Z = 1. Not a bound on DI N+ fragment energy; no "
                    "conclusion on mechanism 4 is drawn from it."},
        "literature_context_gurciullo2019": {
            "source": "Gurciullo, Lucca Fabris & Cappelli, J. Phys. D 52, 464003 (2019), doi:10.1088/1361-6463/ab36c5, "
                      "Sec. 4.3.3 (XeAir-3); author-hosted PDF sppl.stanford.edu; level 3, different thruster (Z-70), Wien "
                      "filter 30 cm downstream",
            "velocity_kms": GURCIULLO_XEAIR3_KMS,
            "velocity_definition": "introduced in the source as 'The mean velocities of the ion species are ...'; the "
                                   "preceding sentence refers to the 'most probable ion velocity' of figures 23-24; "
                                   "ambiguous in the source (verify)",
            "u_ratio_Np_N2p": rnd(GURCIULLO_XEAIR3_KMS["N+"] / GURCIULLO_XEAIR3_KMS["N2+"], 4),
            "R_from_rounded_velocities": rnd((MASS["N"] * GURCIULLO_XEAIR3_KMS["N+"] ** 2) /
                                             (MASS["N2"] * GURCIULLO_XEAIR3_KMS["N2+"] ** 2), 4)},
        "runs": runs_table(rows),
    }
    return out, rows


def fmt(s, key="median"):
    return "—" if s is None else f"{s[key]:.1f}"


def rng(s, nd=1):
    return "—" if s is None else f"{s['median']:.{nd}f} [{s['min']:.{nd}f}, {s['max']:.{nd}f}]"


def tables_md(out):
    L = ["# P5-N2 v1 E x B physics forensics: generated tables (non-gating)", "",
         "Generated by `scripts/forensics/p5_n2_v1_exb_physics.py`; do not edit by hand. Values: median [min, max] over runs, "
         "model outlet, official <u> definition unless stated. Measured: Brabston 2025 Fig. 10 via the frozen audit.", ""]
    rep = out["reproduction_of_official_O5"]
    L += ["## Reproduction of the official O5 block", "",
          f"- runs recomputed: {rep['n_runs_recomputed']} (official entries {rep['n_official_exb_entries']}, keys identical: "
          f"{rep['keys_identical']})",
          f"- max |V_a recomputed - official|: N2+ {rep['max_abs_dev_Va_V']['N2+']:.3g} V, N+ {rep['max_abs_dev_Va_V']['N+']:.3g} V",
          f"- ordering V_a(N+) > V_a(N2+): recomputed {rep['ordering_true_recomputed']}, official {rep['ordering_true_official']}, "
          f"flag mismatches {rep['ordering_flag_mismatches']}", ""]
    rc = out["official_reading_consistency"]
    L += ["## Official statuses under readings A and B (read from the scores file)", "",
          f"- keys whose OUT_OF_DOMAIN status differs between readings: {rc['n_keys_ood_differs_between_readings']}",
          f"- not-OUT_OF_DOMAIN keys: {rc['n_not_ood_keys']}, of which mixed-reading (A != B): {rc['n_mixed_reading_keys']}; "
          f"ordering count among mixed-reading keys: {rc['ordering_count_in_mixed_reading_keys']}", ""]
    L += [f"  - {m['key']}: A {m['status_A']}, B {m['status_B']}" for m in rc["mixed_reading_keys"]]
    if rc["mixed_reading_keys"]:
        L.append("")
    L += ["## Per point", "",
          "| point | n (OOD) | V_a N2+ | V_a N+ | N^2+ per charge | D = V_a(N+) - V_a(N2+) | R | u(N+)/u(N2+) | ff N2+ / N+ / N^2+ | ordering |",
          "|---|---|---|---|---|---|---|---|---|---|"]
    for p in POINTS:
        g = out["by_point"][p]; m = out["measured"]["points"][p]
        L.append(f"| {p} model | {g['n']} ({g['n_out_of_domain']}) | {rng(g['Va_N2p'])} | {rng(g['Va_Np'])} | "
                 f"{rng(g['Va_NZ2_per_charge'])} | {rng(g['D'])} | {rng(g['R'], 2)} | {rng(g['u_ratio_Np_N2p'], 2)} | "
                 f"{g['ff_N2p']['median']:.3f} / {g['ff_Np']['median']:.3f} / {g['ff_NZ2']['median']:.3f} | "
                 f"{g['ordering_count']}/{g['n']} |")
        L.append(f"| {p} measured | — | {m['Va_N2p']:.1f} ± 11.6 | {m['Va_Np']:.1f} ± 11.6 | not reported | "
                 f"{m['D']:.1f} (± {m['sigma_D_V_assuming_independent_errors']:.1f}, independence assumed) | {m['R']:.2f} | "
                 f"{m['u_ratio_Np_N2p_if_labels_hold']:.2f} (if labels hold) | not published | holds |")
    L += ["", f"Equal-birth reference (collisionless, cold birth, one potential): R = 1, u(N+)/u(N2+) = "
          f"{out['velocity_space_m_over_Z_14_label']['equal_birth_reference']['u_ratio_Np_N2p']:.4f}.", "",
          "| point | model V_a(N2+)/V_d | model V_a(N+)/V_d | measured V_a(N2+)/V_d | measured V_a(N+)/V_d |", "|---|---|---|---|---|"]
    for p in POINTS:
        g = out["by_point"][p]; m = out["measured"]["points"][p]
        L.append(f"| {p} | {rng(g['Va_N2p_over_Vd'], 2)} | {rng(g['Va_Np_over_Vd'], 2)} | {m['Va_N2p_over_Vd']:.2f} | "
                 f"{m['Va_Np_over_Vd']:.2f} |")
    L.append("")

    def gtable(title, block, label):
        L.extend([f"## {title}", "", f"| {label} | n (OOD) | V_a N2+ | V_a N+ | D | R | ff N+ | ff N^2+ | Te_max_eV | ordering <u> / <nu>/<n> |",
                  "|---|---|---|---|---|---|---|---|---|---|"])
        for k, g in block.items():
            L.append(f"| {k} | {g['n']} ({g['n_out_of_domain']}) | {rng(g['Va_N2p'])} | {rng(g['Va_Np'])} | {rng(g['D'])} | "
                     f"{rng(g['R'], 2)} | {g['ff_Np']['median']:.3f} | {g['ff_NZ2']['median']:.3f} | {rng(g['Te_max_eV'])} | "
                     f"{g['ordering_count']} / {g['ordering_count_nu_over_n']} |")
        L.append("")
    gtable("By candidate x point", out["by_candidate_point"], "candidate|point")
    gtable("By registration x point", out["by_registration_point"], "registration|point")
    gtable("By chemistry x point", out["by_chemistry_point"], "chemistry|point")
    L.extend(["Spread of the per-point median D across the four mandatory chemistries: " + ", ".join(
        f"{p} {v:.1f} V" for p, v in out["chemistry_spread_of_median_D_by_point_V"].items()), ""])
    gtable("By coil shape x point", out["by_coil_point"], "coil|point")
    gtable("By official domain class x point (status read from the scores file)", out["by_domain_class_point"], "class|point")
    gtable("By Te_max_eV bin (max of the time-averaged T_e profile; all points)", out["by_Te_max_bin"], "Te_max bin [eV]")
    gtable("By I_d RMS/mean band (all points)", out["by_Id_rms_band"], "Id_rms_rel")
    d = out["D_distribution"]
    L += ["## Distribution of D (all 648 runs)", "", f"- D: {rng(d['all'])} V; runs with D >= 0: {d['count_D_ge_0']} (<u>), "
          f"{d['count_D_ge_0_nu_over_n']} (<nu>/<n>)",
          "- measured D minus the largest model D, per point: " + ", ".join(f"{p} {v:.1f} V" for p, v in
                                                                      d["measured_D_minus_max_model_D_by_point_V"].items()),
          "", "| D bin [V] | runs |", "|---|---|"]
    L += [f"| [{b['lo']:.0f}, {b['hi']:.0f}) | {b['count']} |" for b in d["histogram"]["bins"]]
    t = out["time_average_definition_sensitivity"]
    L += ["", "## Time-average definition sensitivity (not a re-scoring)", "",
          f"- V_a(N+) <nu>/<n> over <u>: {rng(t['ratio_Va_Np_nu_over_n_to_u'], 2)}; V_a(N2+): {rng(t['ratio_Va_N2p_nu_over_n_to_u'], 2)}; "
          f"N^2+: {rng(t['ratio_Va_NZ2_nu_over_n_to_u'], 2)}",
          f"- ordering under <nu>/<n>: {t['ordering_count_nu_over_n']} of {out['reproduction_of_official_O5']['n_runs_recomputed']}; "
          f"V_a(N+) - measured under <nu>/<n>: {rng(t['dVa_Np_nu_over_n'])} V", f"- I_d RMS/mean: {rng(t['Id_rms_rel'], 2)}", ""]
    mc = out["multiply_charged"]
    L += ["## Multiply charged ions", "", f"- N2^2+ present in {mc['N2_Z2_present_in_runs']} runs; N^2+ present in "
          f"{mc['N_Z2_present_in_runs']}; species sets: {', '.join(mc['species_key_sets'])}",
          f"- N^2+ energy per charge: between the singles in {mc['NZ2_per_charge_vs_singles']['between_N+_and_N2+']}, above both in "
          f"{mc['NZ2_per_charge_vs_singles']['above_both']}, below both in {mc['NZ2_per_charge_vs_singles']['below_both']}; above "
          f"N2+ under <nu>/<n> in {mc['NZ2_per_charge_vs_singles']['above_N2p_nu_over_n']}", "",
          "## Energy under the E x B m/Z = 14 label (E14 = m_N u^2 / 2e)", "", "| point | E14 N2+ | E14 N+ | E14 N^2+ | ff N^2+ | measured V_a('N+') |",
          "|---|---|---|---|---|---|"]
    for p in POINTS:
        v = out["velocity_space_m_over_Z_14_label"]["by_point"][p]
        L.append(f"| {p} | {rng(v['E14_N2p'])} | {rng(v['E14_Np'])} | {rng(v['E14_NZ2'])} | {rng(v['ff_NZ2'], 3)} | "
                 f"{out['measured']['points'][p]['Va_Np']:.1f} |")
    s = out["vd_slopes"]
    L += ["", "## Discharge-voltage slopes (least squares over N1-N3 per fixed candidate/chemistry/registration/coil series)", "",
          f"- series: {s['n_series']}", f"- model dV_a/dV_d N2+: {rng(s['model_dVa_dVd_N2p'], 2)}; measured {s['measured_dVa_dVd_N2p']:.2f}",
          f"- model dV_a/dV_d N+: {rng(s['model_dVa_dVd_Np'], 2)}; measured {s['measured_dVa_dVd_Np']:.2f}",
          f"- model dD/dV_d: {rng(s['model_dD_dVd'], 2)}; measured {s['measured_dD_dVd']:.2f}", "",
          "## Rank associations (Spearman; descriptive, not causal)", "", "| pair | all | N1 | N2 | N3 |", "|---|---|---|---|---|"]
    a = out["associations_spearman"]
    for k in a["all"]:
        L.append(f"| {k} | " + " | ".join("—" if a[s_][k] is None else f"{a[s_][k]:+.3f}" for s_ in ("all",) + POINTS) + " |")
    f = out["fragment_kinetic_energy_context"]; g = out["literature_context_gurciullo2019"]
    L += ["", "## Literature context (computed from cited published values)", "",
          f"- ion KE peaks {f['published_peaks_eV']} eV quoted from Crowe & McConkey 1975 (most likely N^2+, not DI N+; PROXY "
          f"only, verify): largest / smallest measured D = {f['proxy_max_peak_over_min_measured_D']:.3f}; largest / smallest "
          f"model N+ deficit = {f['proxy_max_peak_over_min_model_Np_deficit']:.3f}. DI N+ fragment KE: TBD",
          f"- Gurciullo 2019 XeAir-3 (Z-70, 30 cm): u(N+)/u(N2+) = {g['u_ratio_Np_N2p']:.3f}, R = {g['R_from_rounded_velocities']:.3f} "
          "from velocities rounded to 1 km/s", ""]
    return "\n".join(L) + "\n"


def serialize(out):
    """Deterministic: sorted keys; the per-run table is written one run per line."""
    runs = out["runs"]
    head = dict(out)
    head["runs"] = "__RUNS__"
    txt = json.dumps(head, indent=1, sort_keys=True, ensure_ascii=False)
    body = ('{\n  "columns": ' + json.dumps(runs["columns"]) + ',\n  "rows": [\n'
            + ",\n".join("   " + json.dumps(r, ensure_ascii=False) for r in runs["rows"]) + "\n  ]\n }")
    return txt.replace('"__RUNS__"', body) + "\n"


def main(argv):
    out, _ = build()
    js, md = serialize(out), tables_md(out)
    if "--check" in argv:
        ok = open(OUT_JSON).read() == js and open(OUT_MD).read() == md
        print("exb_physics outputs current:", ok)
        return 0 if ok else 1
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT_JSON, "w") as f:
        f.write(js)
    with open(OUT_MD, "w") as f:
        f.write(md)
    rep = out["reproduction_of_official_O5"]
    print("wrote", os.path.relpath(OUT_JSON, ROOT), "and", os.path.relpath(OUT_MD, ROOT))
    print("reproduction:", json.dumps(rep))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
